### ISSUE TITLE
The explanation library seems to use a version of the OWL API that is incompatible with the one used by Protege

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#100]
A stack trace from Tim.

```
WARN  Error logged  org.protege.editor.core.ui.error.ErrorLog[Classification Thread]
java.lang.NoClassDefFoundError: uk/ac/manchester/cs/owl/explanation/ordering/DefaultExplanationOrderer
	at uk.ac.manchester.cs.owl.explanation.JustificationFormattingManager.init(JustificationFormattingManager.java:60)
	at uk.ac.manchester.cs.owl.explanation.JustificationFormattingManager.initIfNecessary(JustificationFormattingManager.java:82)
	at uk.ac.manchester.cs.owl.explanation.JustificationFormattingManager.getOrdering(JustificationFormattingManager.java:148)
	at uk.ac.manchester.cs.owl.explanation.JustificationFrameSection.refill(JustificationFrameSection.java:64)
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.setRootObject(AbstractOWLFrameSection.java:310)
	at org.protege.editor.owl.ui.frame.AbstractOWLFrame.refill(AbstractOWLFrame.java:94)
	at org.protege.editor.owl.ui.frame.AbstractOWLFrame.setRootObject(AbstractOWLFrame.java:86)
	at uk.ac.manchester.cs.owl.explanation.JustificationFrameExplanationDisplay.<init>(JustificationFrameExplanationDisplay.java:47)
	at uk.ac.manchester.cs.owl.explanation.WorkbenchPanel.createExplanationDisplay(WorkbenchPanel.java:277)
	at uk.ac.manchester.cs.owl.explanation.WorkbenchPanel.refill(WorkbenchPanel.java:299)
	at uk.ac.manchester.cs.owl.explanation.WorkbenchPanel.<init>(WorkbenchPanel.java:111)
	at uk.ac.manchester.cs.owl.explanation.InconsistentOntologyExplanationPluginImpl.explain(InconsistentOntologyExplanationPluginImpl.java:43)
	at org.protege.editor.owl.ui.explanation.io.InconsistentOntologyManager.explain(InconsistentOntologyManager.java:48)
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.installRunningReasoner(OWLReasonerManagerImpl.java:436)
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:375)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: uk.ac.manchester.cs.owl.explanation.ordering.DefaultExplanationOrderer not found by org.semanticweb.owl.owlapi [14]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1374)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1553)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1484)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 16 more
```

**Comment by sesuncedu** [comment]
The dependency is on a class that is not included in  the  owlapi-osgidistribution.jar  that came in with 3.5.1 (the class is deprecated, but lives on in the test classes). 

There is a lot of owlapi version 3 oddness;  this mixes in felix for added fun.   If you update the jar file adding in the contents of owlapi-contract-3.5.1.jar, the mansplainer works.

**Comment by matthewhorridge** [comment]
Quick update:  I've already updated the library to account for the renaming of DefaultExplanationOrderer to ExplanationOrdererImpl (not sure this was necessary!) and I just need to integrate this into the explanation plugin and release a new version.
