### ISSUE TITLE
AWT Event Loop error loading ontologies

### ISSUE THREAD

**Issue by rpgoldman** [protegeproject/protege#1018]
I'm seeing the following error in my logs when I load an OWL ontology from a Turtle file (I don't know if this would happen loading from another format file):

```
  ERROR  09:57:57  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.IllegalArgumentException: Can't add attribute to 0-length text
	at java.text.AttributedString.addAttribute(AttributedString.java:325) ~[na:1.8.0_121]
	at org.protege.editor.owl.ui.renderer.layout.Paragraph.<init>(Paragraph.java:61) ~[na:na]
	at org.protege.editor.owl.ui.renderer.layout.Paragraph.<init>(Paragraph.java:55) ~[na:na]
	at org.protege.editor.owl.ui.renderer.layout.Paragraph.<init>(Paragraph.java:43) ~[na:na]
	at org.protege.editor.owl.ui.renderer.layout.Page.addParagraph(Page.java:46) ~[na:na]
	at org.protege.editor.owl.ui.ontology.imports.OntologyImportsItemRenderer.render(OntologyImportsItemRenderer.java:54) ~[na:na]
	at org.protege.editor.owl.ui.ontology.imports.OntologyImportsItemRenderer.fillPage(OntologyImportsItemRenderer.java:29) ~[na:na]
	at org.protege.editor.owl.ui.renderer.layout.PageCellRenderer.getListCellRendererComponent(PageCellRenderer.java:93) ~[na:na]
	at org.protege.editor.owl.ui.ontology.imports.OntologyImportsItemRenderer.getListCellRendererComponent(OntologyImportsItemRenderer.java:35) ~[na:na]
	at org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:275) ~[na:na]
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361) ~[na:1.8.0_121]
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311) ~[na:1.8.0_121]
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578) ~[na:1.8.0_121]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662) ~[na:1.8.0_121]
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791) ~[na:1.8.0_121]
	at java.awt.Container.layout(Container.java:1510) ~[na:1.8.0_121]
	at java.awt.Container.doLayout(Container.java:1499) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1695) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_121]
	at java.awt.Container.validate(Container.java:1630) ~[na:1.8.0_121]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711) ~[na:1.8.0_121]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) ~[na:1.8.0_121]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) ~[na:1.8.0_121]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [na:1.8.0_121]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) ~[na:1.8.0_121]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229) ~[na:1.8.0_121]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227) ~[na:1.8.0_121]
	at java.awt.Dialog.show(Dialog.java:1084) ~[na:1.8.0_121]
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869) ~[na:1.8.0_121]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) ~[na:1.8.0_121]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) ~[na:1.8.0_121]
	at org.protege.editor.owl.ui.action.ReloadActiveOntologyAction.actionPerformed(ReloadActiveOntologyAction.java:35) ~[na:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) ~[na:1.8.0_121]
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125) ~[na:1.8.0_121]
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669) ~[na:1.8.0_121]
	at java.awt.MenuItem.processEvent(MenuItem.java:628) ~[na:1.8.0_121]
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:355) ~[na:1.8.0_121]
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:343) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]
```
This does not seem to indicate any real problem, so maybe it should just be caught and discarded?

The real reason I am reporting this, is that when I load an ontology it gives me a false positive error warning in the lower right of the Protege window. That's undesirable because either:

1. I will keep looking at these and wasting time or
2. I will start ignoring the "warning light" and eventually I will miss a *real* bug in my code.

**Comment by matthewhorridge** [comment]
Are you able to share the ontology?  This is a bug, for sure, even if it doesn't impact the operation of Protege

**Comment by rpgoldman** [comment]
@matthewhorridge I'm seeing this when I load the following ontology: https://github.com/rpgoldman/container-ontology/blob/444ad1ffde53ae2b0b58228722e6c352b3af9547/owl/container-ontology.ttl

**Comment by rpgoldman** [comment]
Here is the log file, if that helps.

[protege.log](https://github.com/protegeproject/protege/files/6895571/protege.log)
