### ISSUE TITLE
Anomalous screen display after import

### ISSUE THREAD

**Issue by rpgoldman** [protegeproject/protege#1019]
I imported the attached RDF file, `sbolowl.rdf`, into my Protege workspace.  When I do this, I see the following:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/3274/127404831-6ccbc938-c980-4ebf-9867-dad1aba5ada6.png">

The above is anomalous because one of the ontologies I imported, `om-subset` is shown with information about it being loaded from my local filesystem.

However, the ontology that I loaded from `sbolowl.rdf` is *not* shown with information about its presence in the local filesystem. I think this is a bug, because both ontologies were loaded in the same way, but it still seems like the `sbols3.org` ontology is loaded correctly.

**Comment by rpgoldman** [comment]
This issue seems to have an unfortunate knock-on effect. When I try to use the `compare ontologies` tool to see what I have changed in this ontology, the comparison tool errors out because instead of loading the `http://sbols.org/v3` ontology from local storage, it tries to load it from the web, and fails.  This is a fatal error, because that's an in-progress ontology, and the developers are not willing to put it on the web. So it's load from local or bust.

Here's the corroborating error message:

```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://sbols.org/v3> Cause: https://sbols.org/v3
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1878)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1651)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:278)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1554)
	at org.semanticweb.owlapi.rio.RioOWLRDFConsumerAdapter.handleStatement(RioOWLRDFConsumerAdapter.java:122)
	at org.semanticweb.owlapi.rio.RioParserImpl$RioParserRDFHandler.handleStatement(RioParserImpl.java:341)
	at org.openrdf.rio.turtle.TurtleParser.reportStatement(TurtleParser.java:1157)
	at org.openrdf.rio.turtle.TurtleParser.parseObject(TurtleParser.java:504)
	at org.openrdf.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:427)
	at org.openrdf.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:420)
	at org.openrdf.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:384)
	at org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:260)
	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:215)
	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:159)
	at org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:257)
	at org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:191)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:221)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1262)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1215)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1158)
	at org.protege.editor.owl.diff.ui.boot.OntologyInAltWorkspaceFactory.loadOntology(OntologyInAltWorkspaceFactory.java:72)
	at org.protege.editor.owl.diff.ui.boot.OntologyInAltWorkspaceFactory.loadInSeparateSynchronizedWorkspace(OntologyInAltWorkspaceFactory.java:39)
	at org.protege.editor.owl.diff.ui.boot.StartDiff.calculateDiffs(StartDiff.java:65)
	at org.protege.editor.owl.diff.ui.boot.StartDiff.access$000(StartDiff.java:19)
	at org.protege.editor.owl.diff.ui.boot.StartDiff$1.run(StartDiff.java:54)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: https://sbols.org/v3
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:231)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1262)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1215)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1115)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1833)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1871)
	... 25 more
Caused by: java.io.FileNotFoundException: https://sbols.org/v3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:179)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:141)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:264)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:221)
	... 30 more
Caused by: java.io.FileNotFoundException: https://sbols.org/v3
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at java.net.URLConnection.getContentEncoding(URLConnection.java:523)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:410)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:136)
	... 33 more
```

This *may* be related to what looks like a garbled catalog file:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <uri id="Imports Wizard Entry" name="http://sbols.org/v3" uri="sbolowl3.rdf"/>
    <uri id="Imports Wizard Entry" name="http://sbols.org/v3" uri="file:/Users/rpg/Downloads/sbolowl3.rdf"/>
    <uri id="Imports Wizard Entry" name="http://www.semanticweb.org/rpg/ontologies/2021/5/om-subset" uri="om-subset.owl"/>
    <uri id="Imports Wizard Entry" name="http://www.ontology-of-units-of-measure.org/resource/om-2" uri="om-2.0.rdf"/>
    <uri id="Imports Wizard Entry" name="http://sbols.org/v3" uri="sbolowl3.rdf"/>
    <uri id="Imports Wizard Entry" name="http://www.semanticweb.org/rpg/ontologies/2021/5/container-ontology" uri="container-ontology.ttl"/>
    <group id="Folder Repository, directory=, recursive=true, Auto-Update=true, version=2" prefer="public" xml:base="">
        <uri id="Automatically generated entry, Timestamp=1624053947438" name="http://purl.obolibrary.org/obo/uo.owl" uri="uo.owl"/>
        <uri id="Automatically generated entry, Timestamp=1624053947438" name="http://sbols.org/v3" uri="sbolowl3.rdf"/>
        <uri id="Automatically generated entry, Timestamp=1624053947438" name="http://www.ontology-of-units-of-measure.org/resource/om-2/" uri="om-2.0.rdf"/>
    </group>
</catalog>
```

I will see if tearing out the redundant entries improves matters.
