### ISSUE TITLE
Protégé not responding when saving/opening a file

### ISSUE THREAD

**Issue by JasperDeLandsheere** [protegeproject/protege#1079]
I save an (empty) OWL file and protégé (5.5.0) starts to freeze, every now and then it's usable for a very brief moment of time. I have no prior experience in protégé. 

Java: JVM 1.8.0_121-b13  Memory: 466M
Language: en, Country: US
Framework: Apache Software Foundation (1.8)
OS: windows10 (10.0)
Processor: x86-64

------------------------------------ Plugins -----------------------------------
Plugin: Cellfie Protege 5.0+ Plugin (2.1.0)
Plugin: OWL Code Generation Plug-in (2.0.0)
Plugin: Existential Query (2.0.0)
Plugin: Explanation Workbench (3.0.0)
Plugin: OntoGraf (2.0.3)
Plugin: DL Query (4.0.1)
Plugin: HermiT Reasoner (1.4.3.456)
Plugin: Browser View (OWLDoc) (3.0.3)
Plugin: OWLViz (5.0.3)
Plugin: OWLAPI RDF Library (3.0.0)
Plugin: SPARQL Query Plugin (3.0.0)
Plugin: SWRLTab Protege 5.0+ Plugin (2.0.6)

### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
Creating and setting up empty (default) editor kit
OWL API Version: 4.5.9.2019-02-01T07:24:44Z
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/jaspe/ontologies/2022/9/untitled-ontology-13. URI scheme is not "file"
------------------------------- Auto-update Check ------------------------------
Auto-update last performed: Thu Oct 27 16:13:55 CEST 2022
Auto-update has been performed today.  Not performing it again.

Saving GameOntology
Saving ontology to temp file: C:\Users\jaspe\AppData\Local\Temp\temp-ontology6101720112207630148
[GitRepo] Git repository detected: C:\Users\jaspe\.git
Copying ontology from temp file (C:\Users\jaspe\AppData\Local\Temp\temp-ontology6101720112207630148) to actual destination (C:\Users\jaspe\Protege-5.5.0\Protege files\GamesOntology.owl)
Removing temp file: C:\Users\jaspe\AppData\Local\Temp\temp-ontology6101720112207630148
[GitRepo] On branch: master
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:57) ~[na:1.8.0_121]
        at java.nio.CharBuffer.allocate(CharBuffer.java:335) ~[na:1.8.0_121]
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:795) ~[na:1.8.0_121]
        at org.eclipse.jgit.util.RawParseUtils.decode(RawParseUtils.java:1130) ~[na:na]
        at org.eclipse.jgit.util.RawParseUtils.decodeNoFallback(RawParseUtils.java:1073) ~[na:na]
        at org.eclipse.jgit.util.RawParseUtils.decode(RawParseUtils.java:1033) ~[na:na]
        at org.eclipse.jgit.treewalk.TreeWalk.pathOf(TreeWalk.java:1352) ~[na:na]
        at org.eclipse.jgit.treewalk.TreeWalk.getPathString(TreeWalk.java:1037) ~[na:na]
        at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:518) ~[na:na]
        at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:380) ~[na:na]
        at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:149) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepositoryManager.getModifiedOntologyDocumentPaths(GitRepositoryManager.java:168) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepositoryManager.isAnyOntologyDocumentModified(GitRepositoryManager.java:153) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepoStatusPresenter.updateStatusView(GitRepoStatusPresenter.java:76) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepoStatusPresenter.update(GitRepoStatusPresenter.java:63) ~[na:na]
        at org.protege.editor.owl.model.OWLWorkspace.handleActivated(OWLWorkspace.java:248) ~[na:na]
        at org.protege.editor.core.ui.workspace.WorkspaceFrame$1.windowActivated(WorkspaceFrame.java:71) ~[na:na]
        at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
        at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
        at java.awt.Window.processWindowEvent(Window.java:2066) ~[na:1.8.0_121]
        at javax.swing.JFrame.processWindowEvent(JFrame.java:305) ~[na:1.8.0_121]
        at java.awt.Window.processEvent(Window.java:2013) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
        at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
        at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) ~[na:1.8.0_121]
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:995) ~[na:1.8.0_121]
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:488) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEventImpl(Component.java:4760) ~[na:1.8.0_121]
        at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
        at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
Saved ontology OntologyID(OntologyIRI(<http://www.semanticweb.org/jaspe/ontologies/2022/9/GameOntology>) VersionIRI(<null>)) to file:/C:/Users/jaspe/Protege-5.5.0/Protege%20files/GamesOntology.owl in Turtle Syntax format
[GitRepo] Git repository detected: C:\Users\jaspe\.git
[GitRepo] On branch: master
Exception thrown by listener: org.protege.editor.owl.model.git.GitRepoStatusPresenter$$Lambda$94/1779252987.  Detatching bad listener.
[GitRepo] Git repository detected: C:\Users\jaspe\.git
[GitRepo] On branch: master
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664) ~[na:1.8.0_121]
        at java.lang.String.<init>(String.java:207) ~[na:1.8.0_121]
        at java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:567) ~[na:1.8.0_121]
        at java.nio.CharBuffer.toString(CharBuffer.java:1241) ~[na:1.8.0_121]
        at org.eclipse.jgit.util.RawParseUtils.decode(RawParseUtils.java:1130) ~[na:na]
        at org.eclipse.jgit.util.RawParseUtils.decodeNoFallback(RawParseUtils.java:1073) ~[na:na]
        at org.eclipse.jgit.util.RawParseUtils.decode(RawParseUtils.java:1033) ~[na:na]
        at org.eclipse.jgit.treewalk.TreeWalk.pathOf(TreeWalk.java:1352) ~[na:na]
        at org.eclipse.jgit.treewalk.TreeWalk.getPathString(TreeWalk.java:1037) ~[na:na]
        at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:518) ~[na:na]
        at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:380) ~[na:na]
        at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:149) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepositoryManager.getModifiedOntologyDocumentPaths(GitRepositoryManager.java:168) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepositoryManager.isAnyOntologyDocumentModified(GitRepositoryManager.java:153) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepoStatusPresenter.updateStatusView(GitRepoStatusPresenter.java:76) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepoStatusPresenter.update(GitRepoStatusPresenter.java:63) ~[na:na]
        at org.protege.editor.owl.model.OWLWorkspace.handleActivated(OWLWorkspace.java:248) ~[na:na]
        at org.protege.editor.core.ui.workspace.WorkspaceFrame$1.windowActivated(WorkspaceFrame.java:71) ~[na:na]
        at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
        at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
        at java.awt.Window.processWindowEvent(Window.java:2066) ~[na:1.8.0_121]
        at javax.swing.JFrame.processWindowEvent(JFrame.java:305) ~[na:1.8.0_121]
        at java.awt.Window.processEvent(Window.java:2013) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
        at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
        at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) ~[na:1.8.0_121]
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:995) ~[na:1.8.0_121]
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:488) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEventImpl(Component.java:4760) ~[na:1.8.0_121]
        at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
[GitRepo] Git repository detected: C:\Users\jaspe\.git
[GitRepo] On branch: master
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664) ~[na:1.8.0_121]
        at java.lang.String.<init>(String.java:207) ~[na:1.8.0_121]
        at java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:567) ~[na:1.8.0_121]
        at java.nio.CharBuffer.toString(CharBuffer.java:1241) ~[na:1.8.0_121]
        at org.eclipse.jgit.util.RawParseUtils.decode(RawParseUtils.java:1130) ~[na:na]
        at org.eclipse.jgit.util.RawParseUtils.decodeNoFallback(RawParseUtils.java:1073) ~[na:na]
        at org.eclipse.jgit.util.RawParseUtils.decode(RawParseUtils.java:1033) ~[na:na]
        at org.eclipse.jgit.treewalk.TreeWalk.pathOf(TreeWalk.java:1352) ~[na:na]
        at org.eclipse.jgit.treewalk.TreeWalk.getPathString(TreeWalk.java:1037) ~[na:na]
        at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:518) ~[na:na]
        at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:380) ~[na:na]
        at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:149) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepositoryManager.getModifiedOntologyDocumentPaths(GitRepositoryManager.java:168) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepositoryManager.isAnyOntologyDocumentModified(GitRepositoryManager.java:153) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepoStatusPresenter.updateStatusView(GitRepoStatusPresenter.java:76) ~[na:na]
        at org.protege.editor.owl.model.git.GitRepoStatusPresenter.update(GitRepoStatusPresenter.java:63) ~[na:na]
        at org.protege.editor.owl.model.OWLWorkspace.handleActivated(OWLWorkspace.java:248) ~[na:na]
        at org.protege.editor.core.ui.workspace.WorkspaceFrame$1.windowActivated(WorkspaceFrame.java:71) ~[na:na]
        at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
        at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
        at java.awt.Window.processWindowEvent(Window.java:2066) ~[na:1.8.0_121]
        at javax.swing.JFrame.processWindowEvent(JFrame.java:305) ~[na:1.8.0_121]
        at java.awt.Window.processEvent(Window.java:2013) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
        at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
        at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) ~[na:1.8.0_121]
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:995) ~[na:1.8.0_121]
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:488) ~[na:1.8.0_121]
        at java.awt.Component.dispatchEventImpl(Component.java:4760) ~[na:1.8.0_121]
        at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
[GitRepo] Git repository detected: C:\Users\jaspe\.git
[GitRepo] On branch: master
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by JasperDeLandsheere** [comment]
Downgraded and it worked.
