### ISSUE TITLE
A consistency check should be performed before asking for super/subclasses in the inferred hierarchy

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#144]
```
org.semanticweb.owlapi.reasoner.InconsistentOntologyException: Inconsistent ontology
	at org.semanticweb.HermiT.Reasoner.throwInconsistentOntologyExceptionIfNecessary(Reasoner.java:2187)
	at org.semanticweb.HermiT.Reasoner.checkPreConditions(Reasoner.java:2179)
	at org.semanticweb.HermiT.Reasoner.isSatisfiable(Reasoner.java:755)
	at org.protege.editor.owl.model.hierarchy.cls.InferredOWLClassHierarchyProvider.getParents(InferredOWLClassHierarchyProvider.java:145)
	at org.protege.editor.owl.model.hierarchy.cls.InferredOWLClassHierarchyProvider.getParents(InferredOWLClassHierarchyProvider.java:42)
	at uk.ac.man.cs.mig.coode.owlviz.model.AbstractOWLClassGraphModel.getParents(AbstractOWLClassGraphModel.java:100)
	at uk.ac.man.cs.mig.coode.owlviz.model.AbstractOWLClassGraphModel.getParents(AbstractOWLClassGraphModel.java:118)
	at uk.ac.man.cs.mig.util.graph.controller.impl.DefaultVisualisedObjectManager$VisualisedObjectCache.updateInfo(DefaultVisualisedObjectManager.java:1392)
	at uk.ac.man.cs.mig.util.graph.controller.impl.DefaultVisualisedObjectManager$VisualisedObjectCache.addObject(DefaultVisualisedObjectManager.java:1027)
	at uk.ac.man.cs.mig.util.graph.controller.impl.DefaultVisualisedObjectManager.showObject(DefaultVisualisedObjectManager.java:309)
	at uk.ac.man.cs.mig.coode.owlviz.ui.OWLVizGraphPanel$3.selectionChanged(OWLVizGraphPanel.java:153)
	at uk.ac.man.cs.mig.coode.owlviz.ui.OWLVizSelectionModel.fireSelectionChanged(OWLVizSelectionModel.java:69)
	at uk.ac.man.cs.mig.coode.owlviz.ui.OWLVizSelectionModel.setSelectedClass(OWLVizSelectionModel.java:54)
	at uk.ac.man.cs.mig.coode.owlviz.ui.OWLVizView.updateView(OWLVizView.java:90)
	at org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.updateView(AbstractOWLClassViewComponent.java:36)
	at org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.updateView(AbstractOWLClassViewComponent.java:19)
	at org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.updateViewContentAndHeader(AbstractOWLSelectionViewComponent.java:202)
	at org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent$1.selectionChanged(AbstractOWLSelectionViewComponent.java:80)
	at org.protege.editor.owl.model.selection.OWLSelectionModelImpl.fireSelectionChanged(OWLSelectionModelImpl.java:192)
	at org.protege.editor.owl.model.selection.OWLSelectionModelImpl.updateSelectedObject(OWLSelectionModelImpl.java:180)
	at org.protege.editor.owl.model.selection.OWLSelectionModelImpl.setSelectedObject(OWLSelectionModelImpl.java:171)
	at org.protege.editor.owl.model.selection.OWLSelectionModelImpl.setSelectedEntity(OWLSelectionModelImpl.java:203)
	at org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.setGlobalSelection(AbstractOWLSelectionViewComponent.java:135)
	at org.protege.editor.owl.ui.view.AbstractOWLEntityHierarchyViewComponent.transmitSelection(AbstractOWLEntityHierarchyViewComponent.java:212)
	at org.protege.editor.owl.ui.view.AbstractOWLEntityHierarchyViewComponent$6.valueChanged(AbstractOWLEntityHierarchyViewComponent.java:197)
	at javax.swing.JTree.fireValueChanged(JTree.java:2926)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3387)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.JTree.setSelectionInterval(JTree.java:2549)
	at javax.swing.plaf.basic.BasicTreeUI$Actions.increment(BasicTreeUI.java:4359)
	at javax.swing.plaf.basic.BasicTreeUI$Actions.actionPerformed(BasicTreeUI.java:4031)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2879)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2926)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2842)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by matthewhorridge** [comment]
Fixed by 074a292d06d8a44580337e60297f6127aedf9c7f
