### ISSUE TITLE
Issue when opening ontology

### ISSUE THREAD

**Issue by skchrko** [protegeproject/protege#268]
Hello, I have a couple of ontologies that work fine with Protege 4.x (they've been created with Protege 4.x). I have issues opening some of them in Protege 5.0.0-beta-17. Unfortunately, I do not have permission to share these ontologies, let's call them "somesecretontology".

I'm opening one of the ontologies mentioned, http://somesecretontology.com/core, and Protege answers back:
```
RuntimeException: java.lang.RuntimeException: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>))
```
(full stack is attached below).

That "core" ontology depends on http://somesecretontology.com/provenance, and provenance ontology depends on W3C PROV ontology. All this stuff works via catalog-v0001.xml resolution that looks like 
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <uri id="User Entered Import Resolution" name="http://somesecretontology.com/base" uri="base.ttl"/>
    <uri id="User Entered Import Resolution" name="http://somesecretontology.com/core" uri="../sso/core.ttl"/>
    <uri id="User Entered Import Resolution" name="http://somesecretontology.com/provenance" uri="../sso/provenance.ttl"/>
<...>
</catalog>
```

Ok, I know that ontologies are fine and it looks like some problem with Protege workspace, let's try to trick Protege: 
1) Let's open http://www.w3.org/ns/prov ontology - it works
2) let's open http://somesecretontology.com/provenance in the same window - it works
3) Then let's open http://somesecretontology.com/core ontology again - it works without exceptions!
Ok, let's restart Protege and then open http://somesecretontology.com/core using "clean" Protege. The same exception:

```
loading OntologyID(Anonymous-0) from file:/home/sk/dev/ontology/sso/core.ttl
loading OntologyID(OntologyIRI(<http://somesecretontology.com/datatype>)) from file:/home/sk/dev/ontology/sso/datatype.ttl
loading OntologyID(OntologyIRI(<http://purl.org/dc/elements/1.1/>)) from file:/home/sk/dev/ontology/dep/dc_owl2dl/dc.ttl
loading OntologyID(OntologyIRI(<http://www.w3.org/2004/02/skos/core>)) from file:/home/sk/dev/ontology/dep/skos/skos.rdf
loading OntologyID(OntologyIRI(<http://somesecretontology.com/tolo#>)) from file:/home/sk/dev/ontology/dep-fork/tolo/typedorderedlistontology.ttl
loading OntologyID(OntologyIRI(<http://www.w3.org/2003/06/sw-vocab-status/ns>)) from http://www.w3.org/2003/06/sw-vocab-status/ns
loading OntologyID(OntologyIRI(<http://somesecretontology.com/genetics>)) from file:/home/sk/dev/ontology/sso/genetics.ttl
loading OntologyID(OntologyIRI(<http://semanticscience.org/ontology/sio.owl>)) from file:/home/sk/dev/ontology/dep/sio/sio.owl
Oct 29, 2015 4:18:24 PM org.semanticweb.owlapi.rdf.syntax.RDFParser$StartRDF startElement
INFO: Notice: root element does not have an xml:base. Relative IRIs will be resolved against file:/home/sk/dev/ontology/dep/sio/sio.owl
loading OntologyID(OntologyIRI(<http://www.loria.fr/~coulet/ontology/snpontology/version1.6/snpontology_full.owl>)) from file:/home/sk/dev/ontology/dep/snpo/snpontology_full.owl
loading OntologyID(OntologyIRI(<http://purl.org/obo/owl/sequence>)) from http://purl.org/obo/owl/sequence
loading OntologyID(OntologyIRI(<http://somesecretontology.com/provenance>)) from file:/home/sk/dev/ontology/sso/provenance.ttl
loading OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>)) from http://www.w3.org/ns/prov#
Oct 29, 2015 4:18:29 PM org.semanticweb.owlapi.rdf.syntax.RDFParser$StartRDF startElement
INFO: Notice: root element does not have an xml:base. Relative IRIs will be resolved against http://www.w3.org/ns/prov#
loading OntologyID(OntologyIRI(<http://www.w3.org/ns/prov-o#>)) from http://www.w3.org/ns/prov-o#
loading OntologyID(OntologyIRI(<http://www.w3.org/ns/prov-o-inverses#>)) from http://www.w3.org/ns/prov-o-inverses#
Oct 29, 2015 4:18:32 PM org.semanticweb.owlapi.rdf.syntax.RDFParser$StartRDF startElement
INFO: Notice: root element does not have an xml:base. Relative IRIs will be resolved against http://www.w3.org/ns/prov-o-inverses#
loading OntologyID(OntologyIRI(<http://www.w3.org/ns/prov-aq#>)) from http://www.w3.org/ns/prov-aq#
Oct 29, 2015 4:18:32 PM org.semanticweb.owlapi.rdf.syntax.RDFParser$StartRDF startElement
INFO: Notice: root element does not have an xml:base. Relative IRIs will be resolved against http://www.w3.org/ns/prov-aq#
Error logged
java.lang.RuntimeException: java.lang.RuntimeException: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>))
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.callWithWriteLockUnchecked(ProtegeOWLOntologyManager.java:193)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.applyChange(ProtegeOWLOntologyManager.java:137)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.applyChange(OWLRDFConsumer.java:1159)
	at org.coode.owlapi.rdfxml.parser.TypeOntologyHandler.handleTriple(TypeOntologyHandler.java:71)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.handleStreaming(OWLRDFConsumer.java:2299)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:2274)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.statementWithResourceValue(RDFParser.java:574)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser$NodeElement.startElement(RDFParser.java:905)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser$NodeElementList.startElement(RDFParser.java:841)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.startElement(RDFParser.java:239)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser$1.startElement(RDFXMLParser.java:93)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.parse(RDFParser.java:163)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:124)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:212)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:867)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:778)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1276)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1310)
	at org.coode.owlapi.rdfxml.parser.TPImportsHandler.handleTriple(TPImportsHandler.java:86)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.handleStreaming(OWLRDFConsumer.java:2319)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:2274)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.statementWithResourceValue(RDFParser.java:574)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser$EmptyPropertyElement.startElement(RDFParser.java:1082)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser$PropertyElementList.startElement(RDFParser.java:964)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.startElement(RDFParser.java:239)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser$1.startElement(RDFXMLParser.java:93)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.parse(RDFParser.java:163)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:124)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:212)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:867)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:778)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1276)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1310)
	at org.coode.owlapi.rdfxml.parser.TPImportsHandler.handleTriple(TPImportsHandler.java:86)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.handleStreaming(OWLRDFConsumer.java:2319)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:2274)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.OWLRDFConsumerAdapter.handleTriple(OWLRDFConsumerAdapter.java:110)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseObject(TurtleParser.java:372)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseObjectList(TurtleParser.java:354)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parsePredicateObjectList(TurtleParser.java:285)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseTriples(TurtleParser.java:161)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseStatement(TurtleParser.java:154)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseDocument(TurtleParser.java:106)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleOntologyParser.parse(TurtleOntologyParser.java:120)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:212)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:867)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:778)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1276)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1310)
	at org.coode.owlapi.rdfxml.parser.TPImportsHandler.handleTriple(TPImportsHandler.java:86)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.handleStreaming(OWLRDFConsumer.java:2319)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:2274)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.OWLRDFConsumerAdapter.handleTriple(OWLRDFConsumerAdapter.java:110)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseObject(TurtleParser.java:372)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseObjectList(TurtleParser.java:354)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parsePredicateObjectList(TurtleParser.java:285)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseTriples(TurtleParser.java:161)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseStatement(TurtleParser.java:154)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleParser.parseDocument(TurtleParser.java:106)
	at uk.ac.manchester.cs.owl.owlapi.turtle.parser.TurtleOntologyParser.parse(TurtleOntologyParser.java:120)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:212)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:867)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:796)
	at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:299)
	at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:207)
	at org.protege.editor.owl.OWLEditorKit.handleLoadRequest(OWLEditorKit.java:201)
	at org.protege.editor.core.ProtegeManager.openAndSetupEditorKit(ProtegeManager.java:173)
	at org.protege.editor.core.ui.action.OpenAction.openInNewWorkspace(OpenAction.java:57)
	at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:216)
	at org.protege.editor.core.ui.action.OpenAction.actionPerformed(OpenAction.java:33)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>))
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.callWithWriteLockUnchecked(ProtegeOWLOntologyManager.java:193)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.applyChanges(ProtegeOWLOntologyManager.java:150)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChange(OWLOntologyManagerImpl.java:544)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.applyChangeSuper(ProtegeOWLOntologyManager.java:132)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.access$200(ProtegeOWLOntologyManager.java:25)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager$3.call(ProtegeOWLOntologyManager.java:140)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager$3.call(ProtegeOWLOntologyManager.java:137)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.callWithWriteLock(ProtegeOWLOntologyManager.java:180)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.callWithWriteLockUnchecked(ProtegeOWLOntologyManager.java:190)
	... 134 more
Caused by: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>))
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.checkForOntologyIDChange(OWLOntologyManagerImpl.java:597)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.enactChangeApplication(OWLOntologyManagerImpl.java:481)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:502)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.applyChangesSuper(ProtegeOWLOntologyManager.java:146)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.access$300(ProtegeOWLOntologyManager.java:25)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager$4.call(ProtegeOWLOntologyManager.java:153)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager$4.call(ProtegeOWLOntologyManager.java:150)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.callWithWriteLock(ProtegeOWLOntologyManager.java:180)
	at org.protege.owlapi.model.ProtegeOWLOntologyManager.callWithWriteLockUnchecked(ProtegeOWLOntologyManager.java:190)
	... 142 more

```

**Comment by tudorache** [comment]
Initially, I thought that this is related to an issue that was already closed (#12), which was actually an OWL API issue (https://github.com/owlcs/owlapi/issues/53), but I don't think it is the case, see below.

(Just a note: the parsing and handling of the ontologies in Protege is done using the OWL API, not by a Protege itself).
It turns out that there are several issues with the prov ontology (http://www.w3.org/ns/prov.owl), and the OWL API is right to give an error.

If you inspect the prov ontology (http://www.w3.org/ns/prov) that you are importing, it is a little bit curious: it imports prov-o, and all the extensions, but also copy-n-pastes the content of the imports in the same document (containing multiple owl:Ontology statements), which is unusual, and does not validate as an OWL 2 ontology. So, basically, http://www.w3.org/ns/prov is a merge of prov-o and all its extensions.

However, the real issue is that when the OWL API is loading the prov ontology (the merged one), it will find to have the ontology id (http://www.w3.org/ns/prov#), and then imports prov-aq, which has the same ontology id (http://www.w3.org/ns/prov#). Different ontologies should have different ontology ids. That is why the OWL API is complaining, and rightly so.

The issue with prov and its extensions is that several of them contain multiple owl:Ontology statements.

For example:
The prov ontology (http://www.w3.org/ns/prov) has the following ontology statements:
![screenshot - 10292015 - 03 01 22 pm](https://cloud.githubusercontent.com/assets/2709502/10833274/ef5f6214-7e4d-11e5-91e5-cf4650dbe6e8.png)


The prov-o ontology (http://www.w3.org/ns/prov-o) has the following ontology statements:
![screenshot - 10292015 - 03 02 21 pm](https://cloud.githubusercontent.com/assets/2709502/10833303/2193aa74-7e4e-11e5-9e78-2aceb6c09b50.png)

The prov-aq ontology (http://www.w3.org/ns/prov-aq) has the following ontology statements:
![screenshot - 10292015 - 03 03 48 pm](https://cloud.githubusercontent.com/assets/2709502/10833329/4770dab4-7e4e-11e5-8cd6-9081ea79f7dd.png)

And the parsers are left to choose from the multiple owl:ontology statements, which one is the ontology id. I did not find this in the OWL 2 specification, but my guess is that the parsers will take the first ontology statement to be the ontology id. So, the first owl:ontology statement that is found, it will win. Therefore, both the prov ontology and prov-aq will have the same ontology id (see screenshots above).

It is not clear to me why the prov ontologies have multiple owl:ontology statements, as it seems to be a mistake.

To make the long story short, the workaround is not to import http://www.w3.org/ns/prov, but to import the core prov ontology http://www.w3.org/ns/prov-o, or one or more of its extensions directly.
