### ISSUE TITLE
PatternSyntaxException when I try to enter parentheses into search request

### ISSUE THREAD

**Issue by jgrzebyta** [protegeproject/protege#279]
When I try to enter parentheses into search query I have uncaught exception.

Log:
```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.util.regex.PatternSyntaxException: Unmatched closing ')' near index 9
experiment)
         ^
	at java.util.regex.Pattern.error(Pattern.java:1955) ~[na:1.8.0_40]
	at java.util.regex.Pattern.compile(Pattern.java:1700) ~[na:1.8.0_40]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[na:1.8.0_40]
	at java.util.regex.Pattern.compile(Pattern.java:1054) ~[na:1.8.0_40]
	at org.protege.editor.owl.ui.search.SearchPanel.createSearchRequest(SearchPanel.java:109) ~[na:na]
	at org.protege.editor.owl.ui.search.SearchPanel.doSearch(SearchPanel.java:121) ~[na:na]
	at org.protege.editor.owl.ui.search.SearchPanel.setSearchString(SearchPanel.java:72) ~[na:na]
	at org.protege.editor.owl.ui.search.SearchDialogPanel.performSearch(SearchDialogPanel.java:90) ~[na:na]
	at org.protege.editor.owl.ui.search.SearchDialogPanel.access$200(SearchDialogPanel.java:20) ~[na:na]
	at org.protege.editor.owl.ui.search.SearchDialogPanel$2.insertUpdate(SearchDialogPanel.java:61) ~[na:na]
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201) ~[na:1.8.0_40]
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748) ~[na:1.8.0_40]
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707) ~[na:1.8.0_40]
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130) ~[na:1.8.0_40]
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669) ~[na:1.8.0_40]
```

**Comment by matthewhorridge** [comment]
This was fixed in beta 21.
