### ISSUE TITLE
Error at rendering ontology in different syntaxes

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#286]
Protege 5.0 beta 18 snapshot: Window menu -> Views -> Ontology views, add any of the Manchester, OWL/XML, Functional rendering, and an exception is logged in the console. See below.

```
/Protege-5.0.0-beta-18-SNAPSHOT$ ./run.sh
******************************************************************************** 
**                                  Protégé                                   ** 
******************************************************************************** 
 
----------------- Initialising and Starting the OSGi Framework ----------------- 
FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory 
 
The OSGi framework has been initialised 
------------------------------- Starting Bundles ------------------------------- 
Starting bundle org.protege.common 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle org.eclipse.equinox.common 
Starting bundle org.protege.editor.core.application 
Starting bundle org.eclipse.equinox.registry 
Starting bundle org.apache.servicemix.bundles.aopalliance 
Starting bundle com.google.guava 
Starting bundle org.apache.servicemix.bundles.javax-inject 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle org.eclipse.equinox.common 
Starting bundle org.protege.ontograf 
Starting bundle org.protege.common 
Starting bundle log4j.over.slf4j 
Starting bundle ch.qos.logback.classic 
Starting bundle ca.uvic.cs.chisel.cajun 
Starting bundle org.protege.editor.core.application 
Starting bundle org.apache.commons.io 
Not starting bundle com.google.inject.assistedinject explicitly because it is a fragment bundle. 
Starting bundle ch.qos.logback.core 
Starting bundle org.semanticweb.owl.owlapi 
Starting bundle jul.to.slf4j 
Starting bundle com.google.inject 
Not starting bundle com.google.inject.multibindings explicitly because it is a fragment bundle. 
Starting bundle slf4j.api 
Starting bundle org.protege.editor.owl 
Starting bundle org.eclipse.equinox.registry 
The OSGi framework has been started 
 
------------------------------------ Protégé ----------------------------------- 
Protégé Desktop 
Version 5.0.0, Build beta-18-SNAPSHOT 
 
 
----------------------------------- Platform ----------------------------------- 
Java: JVM 1.8.0_60-b27  Memory: 466M 
Language: en, Country: US 
Framework: Apache Software Foundation (1.7)  
OS: linux (3.8.0-35-generic) 
Processor: x86-64
 
 
------------------------------------ Plugins ----------------------------------- 
No plugins installed 
 
OWL API Version: 4.1.3.20151118-2017 
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/ttania/ontologies/2015/11/untitled-ontology-11 
------------------------------- Auto-update Check ------------------------------ 
Auto-update last performed: Thu Dec 03 00:11:34 PST 2015 
Auto-update has been performed today.  Not performing it again. 
 
OWL API Version: 4.1.3.20151118-2017 
------------------------------- Loading Ontology ------------------------------- 
Loading ontology from http://protege.cim3.net/file/pub/ontologies/koala/koala.owl 
dumping remaining triples 
done dumping remaining triples 
Loading for ontology and imports closure successfully completed in 273 ms 
 
---------------------------- Disposing of Workspace ---------------------------- 
Saved tab state for 'Entities' tab 
Saved tab state for 'Active Ontology' tab 
Saved tab state for 'Individuals by class' tab 
Saved workspace 
Disposed of 'Entities' tab 
Disposed of 'Active Ontology' tab 
Disposed of 'Individuals by class' tab 
Disposed of workspace 
 
error rendering ontology 
org.semanticweb.owlapi.io.OWLRendererIOException: java.io.InterruptedIOException
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.flush(AbstractRenderer.java:93) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxFrameRenderer.writeOntology(ManchesterOWLSyntaxFrameRenderer.java:354) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxRenderer.render(ManchesterOWLSyntaxRenderer.java:37) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.ManchesterSyntaxRenderingViewComponent.renderOntology(ManchesterSyntaxRenderingViewComponent.java:25) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$2.run(AbstractOntologyRenderingViewComponent.java:120) ~[na:na]
Caused by: java.io.InterruptedIOException: null
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$TextAreaWriter.write(AbstractOntologyRenderingViewComponent.java:251) ~[na:na]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[na:1.8.0_60]
	at java.io.BufferedWriter.flush(BufferedWriter.java:253) ~[na:1.8.0_60]
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.flush(AbstractRenderer.java:91) ~[na:na]
	... 4 common frames omitted
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]
error rendering ontology 
org.semanticweb.owlapi.io.OWLRendererIOException: java.io.InterruptedIOException
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.flush(AbstractRenderer.java:93) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxFrameRenderer.writeOntology(ManchesterOWLSyntaxFrameRenderer.java:354) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxRenderer.render(ManchesterOWLSyntaxRenderer.java:37) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.ManchesterSyntaxRenderingViewComponent.renderOntology(ManchesterSyntaxRenderingViewComponent.java:25) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$2.run(AbstractOntologyRenderingViewComponent.java:120) ~[na:na]
Caused by: java.io.InterruptedIOException: null
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$TextAreaWriter.write(AbstractOntologyRenderingViewComponent.java:251) ~[na:na]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[na:1.8.0_60]
	at java.io.BufferedWriter.flush(BufferedWriter.java:253) ~[na:1.8.0_60]
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.flush(AbstractRenderer.java:91) ~[na:na]
	... 4 common frames omitted
error rendering ontology 
org.semanticweb.owlapi.model.OWLRuntimeException: java.io.InterruptedIOException
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLWriter.writeEndElement(OWLXMLWriter.java:191) ~[na:na]
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLObjectRenderer.visit(OWLXMLObjectRenderer.java:505) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLClassImpl.accept(OWLClassImpl.java:253) ~[na:na]
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLObjectRenderer.visit(OWLXMLObjectRenderer.java:224) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLClassAssertionAxiomImpl.accept(OWLClassAssertionAxiomImpl.java:123) ~[na:na]
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLObjectRenderer.visit(OWLXMLObjectRenderer.java:195) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.accept(OWLImmutableOntologyImpl.java:852) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.accept(ConcurrentOWLOntologyImpl.java:396) ~[na:na]
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLRenderer.render(OWLXMLRenderer.java:86) ~[na:na]
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLRenderer.render(OWLXMLRenderer.java:98) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.OWLXMLRenderingViewComponent.renderOntology(OWLXMLRenderingViewComponent.java:24) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$2.run(AbstractOntologyRenderingViewComponent.java:120) ~[na:na]
Caused by: java.io.InterruptedIOException: null
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$TextAreaWriter.write(AbstractOntologyRenderingViewComponent.java:251) ~[na:na]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[na:1.8.0_60]
	at java.io.BufferedWriter.write(BufferedWriter.java:230) ~[na:1.8.0_60]
	at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_60]
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeAttribute(XMLWriterImpl.java:409) ~[na:na]
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeAttributes(XMLWriterImpl.java:419) ~[na:na]
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeElementStart(XMLWriterImpl.java:335) ~[na:na]
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeElementEnd(XMLWriterImpl.java:389) ~[na:na]
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl.writeEndElement(XMLWriterImpl.java:169) ~[na:na]
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLWriter.writeEndElement(OWLXMLWriter.java:189) ~[na:na]
	... 11 common frames omitted
error rendering ontology 
org.semanticweb.owlapi.model.OWLRuntimeException: java.io.InterruptedIOException
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.flush(FunctionalSyntaxObjectRenderer.java:158) ~[na:na]
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.visit(FunctionalSyntaxObjectRenderer.java:230) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.accept(OWLImmutableOntologyImpl.java:852) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.accept(ConcurrentOWLOntologyImpl.java:396) ~[na:na]
	at org.semanticweb.owlapi.functional.renderer.OWLFunctionalSyntaxRenderer.render(OWLFunctionalSyntaxRenderer.java:38) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.OWLFunctionalSyntaxRenderingViewComponent.renderOntology(OWLFunctionalSyntaxRenderingViewComponent.java:20) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$2.run(AbstractOntologyRenderingViewComponent.java:120) ~[na:na]
Caused by: java.io.InterruptedIOException: null
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$TextAreaWriter.write(AbstractOntologyRenderingViewComponent.java:251) ~[na:na]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[na:1.8.0_60]
	at java.io.BufferedWriter.flush(BufferedWriter.java:253) ~[na:1.8.0_60]
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.flush(FunctionalSyntaxObjectRenderer.java:156) ~[na:na]
	... 6 common frames omitted


```

**Comment by matthewhorridge** [comment]
I can't reproduce this.  Closing for now.  Please re-open if it's reproducible with a certain ontology.

**Comment by tudorache** [comment]
Can reproduce consistently with P 5 RC. 

Window -> View -> Miscellaneous View -> Manchester Syntax entity rendering

```
error rendering ontology 
org.semanticweb.owlapi.model.OWLRuntimeException: java.io.InterruptedIOException
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.write(AbstractRenderer.java:136) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.writeTab(AbstractRenderer.java:116) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.writeNewLine(AbstractRenderer.java:163) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxFrameRenderer.writeSection(ManchesterOWLSyntaxFrameRenderer.java:1198) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxFrameRenderer.write(ManchesterOWLSyntaxFrameRenderer.java:518) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxFrameRenderer.writeOntology(ManchesterOWLSyntaxFrameRenderer.java:278) ~[na:na]
	at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxRenderer.render(ManchesterOWLSyntaxRenderer.java:37) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.ManchesterSyntaxRenderingViewComponent.renderOntology(ManchesterSyntaxRenderingViewComponent.java:25) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$1.run(AbstractOntologyRenderingViewComponent.java:116) ~[na:na]
Caused by: java.io.InterruptedIOException: null
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$TextAreaWriter.write(AbstractOntologyRenderingViewComponent.java:244) ~[na:na]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[na:1.8.0_91]
	at java.io.BufferedWriter.write(BufferedWriter.java:230) ~[na:1.8.0_91]
	at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_91]
	at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.write(AbstractRenderer.java:134) ~[na:na]
	... 8 common frames omitted
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]
```

**Comment by tudorache** [comment]
Duplicate of #336 
Closing.
