### ISSUE TITLE
Import ontology throws invalid URI scheme for "file" protocol

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege#312]
Steps to reproduce:
 1. In "Active Ontology" tab, add "Direct Imports",
 2. Select the first option "Import an ontology contained in a specific file",
 3. Pick a file,
 4. A confirm dialog will appear before the final "Finish" selection. Note the file source location is written incorrectly, e.g., `file:/Users/jhardi/Desktop/Ontology1.owl`. The file protocol should have double-slash,
 5. An error dialog will appear with message:
```
An exception has occurred when loading input file.
Message: URI scheme is not "file"

###################################################
##    Debugging information (for the authors)    ##
###################################################

	at org.semanticweb.ontop.protege.core.OBDAModelManager$OBDAPLuginOWLModelManagerListener.handleChange(OBDAModelManager.java:551)
	at org.protege.editor.owl.model.OWLModelManagerImpl.fireEvent(OWLModelManagerImpl.java:778)
	at org.protege.editor.owl.ui.ontology.imports.OntologyImportsList.handleAdd(OntologyImportsList.java:119)
	at org.protege.editor.core.ui.list.MList$2.actionPerformed(MList.java:48)
	at org.protege.editor.core.ui.list.MList.handleMouseClick(MList.java:217)
	at org.protege.editor.core.ui.list.MList.access$200(MList.java:19)
	at org.protege.editor.core.ui.list.MList$6.mouseReleased(MList.java:108)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        ...
```
I suppose the bug comes from the ill-written URI address when locating the source file.

**Comment by matthewhorridge** [comment]
Actually, there is no exception here.  There is a warning in the OWL API that is logged as an error.  This causes the error triangle in Protege to appear.  I've filed an issue on the OWL API tracker.  Also, ```file:/Users/blah``` is fine.
