### ISSUE TITLE
Setting ranges of datatype properties using the "Data range expression" editor is broken

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#325]
When trying to set the range of a datatype property to something like {"A", "B", "C"} using the "Data range expression" editor, it throws a nullPointerException:

`An error occurred whilst checking an expression. Expression: { 
java.lang.NullPointerException: null
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.getToken(ManchesterOWLSyntaxParserImpl.java:462) ~[owlapi-osgidistribution.jar:4.1.3.20151118-2017]
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.peekToken(ManchesterOWLSyntaxParserImpl.java:435) ~[owlapi-osgidistribution.jar:4.1.3.20151118-2017]
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseDataRangePrimary(ManchesterOWLSyntaxParserImpl.java:771) ~[owlapi-osgidistribution.jar:4.1.3.20151118-2017]
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseDataUnionOf(ManchesterOWLSyntaxParserImpl.java:756) ~[owlapi-osgidistribution.jar:4.1.3.20151118-2017]
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseDataIntersectionOf(ManchesterOWLSyntaxParserImpl.java:737) ~[owlapi-osgidistribution.jar:4.1.3.20151118-2017]
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseDataRange(ManchesterOWLSyntaxParserImpl.java:729) ~[owlapi-osgidistribution.jar:4.1.3.20151118-2017]
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLDataRangeChecker.createObject(OWLDataRangeChecker.java:44) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLDataRangeChecker.check(OWLDataRangeChecker.java:36) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.checkExpression(ExpressionEditor.java:213) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.handleTimer(ExpressionEditor.java:227) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.access$100(ExpressionEditor.java:45) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor$2.actionPerformed(ExpressionEditor.java:113) [protege-editor-owl.jar:na]
	at javax.swing.Timer.fireActionPerformed(Timer.java:313) [na:1.8.0_40]
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245) [na:1.8.0_40]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) [na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
`

![protege_data_range_expression_editor](https://cloud.githubusercontent.com/assets/2441046/13021662/35ed9d22-d191-11e5-9145-9eccee540b92.png)

This works properly in 5.0.0-beta-16.

**Comment by csnyulas** [comment]
Duplicate of #308
