### ISSUE TITLE
Render by Prefixed Annotation Property displays two consecutive prefixes

### ISSUE THREAD

**Issue by wismill** [protegeproject/protege#327]
Hi, the entity renderer displays two consecutive prefixes for the classes: "owl:owl:Thing", "skos:skos:Concept".

This happens when using the option "Render by prefixed annotation property" of the entity rendering. By the way, the classes are always displayed prefixed but not the individuals, regardless to the option chosen.

I am using the latest development version of Protégé.

**Comment by csnyulas** [comment]
This is very unusual. We have never have such thing reported. Could you send us a screen shot?
Here is a few additional questions to try to debug it:
- Is the repeated prefix only for this 2 classes, or for your own classes as well?
- Can you send us all the different settings you chose in the entity rendering (maybe a screen shot)?
- Is there any error message on the console (when you start Protege or when you change settings)? 
- What prefixes do you have declared in your ontology? 
- When you say latest development version you mean 5.0.0-beta-21?
- What is your OS? Java? Protege distribution?

**Comment by matthewhorridge** [comment]
I know what has caused this.  A fix should be in beta-23.

**Comment by wismill** [comment]
- OS: Linux and Windows
- Java: 1.8
- Protégé: git/master
- I have not observed this behaviour for my own classes.
- I have enclosed some screenshots.

**Prefixes:**
```
@prefix :        <http://example.org/ontologies/mathematics/lattice%20theory/0.1/> .
@prefix math:    <http://example.org/ontologies/mathematics/0.1/> .
@prefix rel:     <http://example.org/ontologies/mathematics/relations/0.1/> .
@prefix set:     <http://example.org/ontologies/mathematics/set%20theory/0.1/> .
@prefix algebra: <http://example.org/ontologies/mathematics/universal%20algebra/0.1/> .
@prefix graph:   <http://example.org/ontologies/mathematics/graph%20theory/0.1/> .
@prefix cat:     <http://example.org/ontologies/mathematics/category%20theory/0.1/> .
@prefix order:   <http://example.org/ontologies/mathematics/order%20theory/0.1/> .

@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .
@prefix skoxl: <http://www.w3.org/2008/05/skos-xl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix dct:   <http://purl.org/dc/terms/> .
```

**Log:**

```

C:\repositories\protege\protege-desktop\target\protege-5.0.0-beta-23-SNAPSHOT-platform-independent\Protege-5.0.0-beta-23-SNAPSHOT>setlocal

C:\repositories\protege\protege-desktop\target\protege-5.0.0-beta-23-SNAPSHOT-platform-independent\Protege-5.0.0-beta-23-SNAPSHOT>cd /d C:\repositories\protege\protege-desktop\target\protege-5.0.0-beta-23-SNAPSHOT-platform-independent\Protege-5.0.0-beta-23-SNAPSHOT\ 

C:\repositories\protege\protege-desktop\target\protege-5.0.0-beta-23-SNAPSHOT-platform-independent\Protege-5.0.0-beta-23-SNAPSHOT>java -Xmx500M -Xms200M -XX:CompileCommand=exclude,javax/swing/text/GlyphView,getBreakSpot -DentityExpansionLimit=100000000 -Dlogback.configurationFile=conf/logback.xml -Dfile.encoding=utf-8 -Dorg.protege.plugin.dir=plugins -classpath bundles/guava.jar;bundles/jansi.jar;bundles/logback-classic.jar;bundles/logback-core.jar;bundles/slf4j-api.jar;bin/org.apache.felix.main.jar;bin/protege-launcher.jar org.protege.osgi.framework.Launcher  
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
17:11:05,905 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [conf/logback.xml] at [file:/C:/repositories/protege/protege-desktop/target/protege-5.0.0-beta-23-SNAPSHOT-platform-independent/Protege-5.0.0-beta-23-SNAPSHOT/conf/logback.xml]
17:11:05,959 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:11:05,965 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeFilter scanning period to 10 seconds
17:11:05,965 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[C:\repositories\protege\protege-desktop\target\protege-5.0.0-beta-23-SNAPSHOT-platform-independent\Protege-5.0.0-beta-23-SNAPSHOT\conf\logback.xml]] every 10 seconds. 
17:11:05,965 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
17:11:05,974 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:11:05,977 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
17:11:06,016 |-INFO in ch.qos.logback.core.ConsoleAppender[stdout] - Enabling JANSI WindowsAnsiOutputStream for the console.
17:11:06,140 |-WARN in ch.qos.logback.core.ConsoleAppender[stdout] - Failed to create WindowsAnsiOutputStream. Falling back on the default stream. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.fusesource.jansi.WindowsAnsiOutputStream
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.fusesource.jansi.WindowsAnsiOutputStream
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:73)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:42)
	at 	at ch.qos.logback.core.ConsoleAppender.getTargetStreamForWindows(ConsoleAppender.java:94)
	at 	at ch.qos.logback.core.ConsoleAppender.start(ConsoleAppender.java:85)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at 	at org.protege.osgi.framework.Launcher.<init>(Launcher.java:33)
	at 	at org.protege.osgi.framework.Launcher.main(Launcher.java:242)
Caused by: java.lang.reflect.InvocationTargetException
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:68)
	at 	... 22 common frames omitted
Caused by: java.io.IOException: Could not get the screen info: D e r   V o r g a n g   w u r d e   e r f o l g r e i c h   b e e n d e t . 
 
                                                                                 
	at 	at org.fusesource.jansi.WindowsAnsiOutputStream.getConsoleInfo(WindowsAnsiOutputStream.java:104)
	at 	at org.fusesource.jansi.WindowsAnsiOutputStream.<init>(WindowsAnsiOutputStream.java:97)
	at 	... 27 common frames omitted
17:11:06,141 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
17:11:06,142 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [files]
17:11:06,168 |-INFO in ch.qos.logback.core.FileAppender[files] - File property is set to [C:\Users\user123/.protege/logs/protege.log]
17:11:06,170 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
17:11:06,170 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
17:11:06,170 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [files] to Logger[ROOT]
17:11:06,170 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:11:06,171 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3ecf72fd - Registering current configuration as safe fallback point

[34m********************************************************************************[0;39m 
[34m**                                  Protege                                   **[0;39m 
[34m********************************************************************************[0;39m 
[34m[0;39m 
[34m----------------- Initialising and Starting the OSGi Framework -----------------[0;39m 
[34mFrameworkFactory Class: org.apache.felix.framework.FrameworkFactory[0;39m 
[34m[0;39m 
[34mThe OSGi framework has been initialised[0;39m 
[34m------------------------------- Starting Bundles -------------------------------[0;39m 
[34mStarting bundle org.protege.common[0;39m 
[34mStarting bundle org.eclipse.equinox.common[0;39m 
[34mStarting bundle org.eclipse.equinox.supplement[0;39m 
[34mStarting bundle org.eclipse.equinox.registry[0;39m 
[34mStarting bundle org.protege.editor.core.application[0;39m 
[34mStarting bundle org.apache.commons.io[0;39m 
[34mStarting bundle com.google.guava[0;39m 
[34mNot starting bundle com.google.inject.assistedinject explicitly because it is a fragment bundle.[0;39m 
[34mNot starting bundle com.google.inject.multibindings explicitly because it is a fragment bundle.[0;39m 
[34mStarting bundle com.google.inject[0;39m 
[34mStarting bundle org.fusesource.jansi[0;39m 
[34mStarting bundle jul.to.slf4j[0;39m 
[34mStarting bundle log4j.over.slf4j[0;39m 
[34mStarting bundle ch.qos.logback.classic[0;39m 
[34mStarting bundle ch.qos.logback.core[0;39m 
[34mStarting bundle org.apache.servicemix.bundles.aopalliance[0;39m 
[34mStarting bundle org.apache.servicemix.bundles.javax-inject[0;39m 
[34mStarting bundle org.eclipse.equinox.common[0;39m 
[34mStarting bundle org.eclipse.equinox.registry[0;39m 
[34mStarting bundle org.eclipse.equinox.supplement[0;39m 
[34mStarting bundle org.semanticweb.owl.owlapi[0;39m 
[34mStarting bundle org.protege.common[0;39m 
[34mStarting bundle org.protege.editor.core.application[0;39m 
[34mStarting bundle org.protege.editor.owl[0;39m 
[34mStarting bundle slf4j.api[0;39m 
17:11:06,589 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [conf/logback.xml] at [file:/C:/repositories/protege/protege-desktop/target/protege-5.0.0-beta-23-SNAPSHOT-platform-independent/Protege-5.0.0-beta-23-SNAPSHOT/conf/logback.xml]
17:11:06,613 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:11:06,616 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeFilter scanning period to 10 seconds
17:11:06,616 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[C:\repositories\protege\protege-desktop\target\protege-5.0.0-beta-23-SNAPSHOT-platform-independent\Protege-5.0.0-beta-23-SNAPSHOT\conf\logback.xml]] every 10 seconds. 
17:11:06,616 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
17:11:06,618 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:11:06,619 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
17:11:06,654 |-INFO in ch.qos.logback.core.ConsoleAppender[stdout] - Enabling JANSI WindowsAnsiOutputStream for the console.
17:11:06,654 |-WARN in ch.qos.logback.core.ConsoleAppender[stdout] - Failed to create WindowsAnsiOutputStream. Falling back on the default stream. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.fusesource.jansi.WindowsAnsiOutputStream
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.fusesource.jansi.WindowsAnsiOutputStream
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:73)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:42)
	at 	at ch.qos.logback.core.ConsoleAppender.getTargetStreamForWindows(ConsoleAppender.java:94)
	at 	at ch.qos.logback.core.ConsoleAppender.start(ConsoleAppender.java:85)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
	at 	at org.protege.common.Activator.<init>(Activator.java:10)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at 	at java.lang.Class.newInstance(Unknown Source)
	at 	at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:4362)
	at 	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2149)
	at 	at org.apache.felix.framework.Felix.startBundle(Felix.java:2072)
	at 	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at 	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at 	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.WindowsAnsiOutputStream not found by ch.qos.logback.classic [14]
	at 	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
	at 	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
	at 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
	at 	at java.lang.ClassLoader.loadClass(Unknown Source)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:60)
	at 	... 33 common frames omitted
17:11:06,655 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
17:11:06,655 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [files]
17:11:06,660 |-INFO in ch.qos.logback.core.FileAppender[files] - File property is set to [C:\Users\user123/.protege/logs/protege.log]
17:11:06,661 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
17:11:06,661 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
17:11:06,662 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [files] to Logger[ROOT]
17:11:06,662 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:11:06,662 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4d16667c - Registering current configuration as safe fallback point

[34mThe OSGi framework has been started[0;39m 
[34m[0;39m 
[34m------------------------------------ Protégé -----------------------------------[0;39m 
[34mProtégé Desktop[0;39m 
[34mVersion 5.0.0, Build beta-23-SNAPSHOT[0;39m 
[34m[0;39m 
[34m[0;39m 
[34m----------------------------------- Platform -----------------------------------[0;39m 
[34mJava: JVM 1.8.0_73-b02  Memory: 466M[0;39m 
[34mLanguage: de, Country: DE[0;39m 
[34mFramework: Apache Software Foundation (1.7) [0;39m 
[34mOS: windows7 (6.1)[0;39m 
[34mProcessor: x86-64
[0;39m 
[34m[0;39m 
[34m------------------------------------ Plugins -----------------------------------[0;39m 
[34mNo plugins installed[0;39m 
[34m[0;39m 
.\run.bat : févr. 17, 2016 5:11:07 PM java.util.prefs.WindowsPreferences <init>
In Zeile:1 Zeichen:1
+ .\run.bat 2>&1 1> "c:\user123\protégé.log"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (févr. 17, 2016 ...ferences <init>:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

[34mOWL API Version: 4.1.3.20151118-2017[0;39m 
[31mCannot generate ontology catalog for ontology at http://www.semanticweb.org/user123/ontologies/2016/1/untitled-ontology-9[0;39m 
[34m------------------------------- Auto-update Check ------------------------------[0;39m 
[34mAuto-update last performed: Wed Feb 17 12:29:12 CET 2016[0;39m 
[34mAuto-update has been performed today.  Not performing it again.[0;39m 
[34m[0;39m 
### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
[34mOWL API Version: 4.1.3.20151118-2017[0;39m 
[34m------------------------------- Loading Ontology -------------------------------[0;39m 
[34mLoading ontology from file:/C:/FILES/user123/+thesis/voc/mathematics/lattice%20theory.ttl[0;39m 
[31mFolder repository probably came from another system[0;39m 
[31mCould not be updated because directory C:\user123\P71 Thèse\ontologies does not exist[0;39m 
[1;31mBad ontology library declaration - check logs. Warnings now disabled for this session.[0;39m 
java.io.IOException: null
	at org.protege.editor.owl.model.library.folder.FolderGroupManager.isSuitable(FolderGroupManager.java:96) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.model.library.OntologyCatalogManager.update(OntologyCatalogManager.java:157) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.model.library.OntologyCatalogManager.ensureCatalogExists(OntologyCatalogManager.java:115) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.model.library.OntologyCatalogManager.addFolder(OntologyCatalogManager.java:188) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.model.OWLModelManagerImpl.addRootFolder(OWLModelManagerImpl.java:319) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:274) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.OWLEditorKit.handleLoadRecentRequest(OWLEditorKit.java:189) [protege-editor-owl.jar:na]
	at org.protege.editor.core.ProtegeManager.openAndSetupRecentEditorKit(ProtegeManager.java:263) [protege-editor-core.jar:na]
	at org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.openInNewWorkspace(OpenRecentAction.java:90) [protege-editor-core.jar:na]
	at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:210) [protege-editor-core.jar:na]
	at org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.actionPerformed(OpenRecentAction.java:76) [protege-editor-core.jar:na]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.8.0_73]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [na:1.8.0_73]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [na:1.8.0_73]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.8.0_73]
	at javax.swing.AbstractButton.doClick(Unknown Source) [na:1.8.0_73]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) [na:1.8.0_73]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source) [na:1.8.0_73]
	at java.awt.Component.processMouseEvent(Unknown Source) [na:1.8.0_73]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.Component.processEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.Container.processEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
	at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
	at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
	at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
	at java.awt.EventQueue.access$500(Unknown Source) [na:1.8.0_73]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_73]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_73]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_73]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_73]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_73]
	at java.awt.EventQueue$4.run(Unknown Source) [na:1.8.0_73]
	at java.awt.EventQueue$4.run(Unknown Source) [na:1.8.0_73]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_73]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_73]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.8.0_73]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_73]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_73]
	at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_73]
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]
[31mFolder repository probably came from another system[0;39m 
[31mCould not be updated because directory C:\user123\P71 thesis\voc does not exist[0;39m 
[34mLoading OntologyID(Anonymous-0) from file:/C:/FILES/user123/+thesis/voc/mathematics/lattice%20theory.ttl[0;39m 
[34mdumping remaining triples[0;39m 
[34mdone dumping remaining triples[0;39m 
[34mLoading for ontology and imports closure successfully completed in 198 ms[0;39m 
[34m[0;39m 
[34m---------------------------- Disposing of Workspace ----------------------------[0;39m 
[34mSaved tab state for 'Active Ontology' tab[0;39m 
[34mSaved tab state for 'Individuals by class' tab[0;39m 
[34mSaved tab state for 'Entities' tab[0;39m 
[34mSaved tab state for 'Annotation Properties' tab[0;39m 
[34mSaved tab state for 'Data Properties' tab[0;39m 
[34mSaved tab state for 'Object Properties' tab[0;39m 
[34mSaved tab state for 'Classes' tab[0;39m 
[34mSaved workspace[0;39m 
[34mDisposed of 'Active Ontology' tab[0;39m 
[34mDisposed of 'Individuals by class' tab[0;39m 
[34mDisposed of 'Entities' tab[0;39m 
[34mDisposed of 'Annotation Properties' tab[0;39m 
[34mDisposed of 'Data Properties' tab[0;39m 
[34mDisposed of 'Object Properties' tab[0;39m 
[34mDisposed of 'Classes' tab[0;39m 
[34mDisposed of workspace[0;39m 
[34m[0;39m 
[34m---------------------------- Disposing of Workspace ----------------------------[0;39m 
[34mSaved tab state for 'Active Ontology' tab[0;39m 
[34mSaved tab state for 'Object Properties' tab[0;39m 
[34mSaved tab state for 'Individuals by class' tab[0;39m 
[34mSaved tab state for 'Data Properties' tab[0;39m 
[34mSaved tab state for 'Annotation Properties' tab[0;39m 
[34mSaved tab state for 'Classes' tab[0;39m 
[34mSaved tab state for 'Entities' tab[0;39m 
[34mSaved workspace[0;39m 
[34mDisposed of 'Active Ontology' tab[0;39m 
[34mDisposed of 'Object Properties' tab[0;39m 
[34mDisposed of 'Individuals by class' tab[0;39m 
[34mDisposed of 'Data Properties' tab[0;39m 
[34mDisposed of 'Annotation Properties' tab[0;39m 
[34mDisposed of 'Classes' tab[0;39m 
[34mDisposed of 'Entities' tab[0;39m 
[34mDisposed of workspace[0;39m 
[34m[0;39m 
```
**Screenshots:**

![duplicate prefixes for annotations](https://cloud.githubusercontent.com/assets/3842915/13115635/dac718b8-d598-11e5-8c81-551e83c1dfea.png)
![duplicate prefixes for classess](https://cloud.githubusercontent.com/assets/3842915/13115633/da8bd4ba-d598-11e5-83a2-84fe8fc82e95.png)
![renderer advanced settings](https://cloud.githubusercontent.com/assets/3842915/13115632/da8b4a68-d598-11e5-90ac-63ae7df4ae25.png)
![renderer settings](https://cloud.githubusercontent.com/assets/3842915/13115631/da8ac548-d598-11e5-80ff-9b5b50a31cec.png)
