### ISSUE TITLE
Drag-n-drop does not work in the class hierarchy

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#333]
Any drag-n-drop in the class hierarchy does not work. The icon of the cursor is changed in the "interdicted" sign. See exception below.

Probably related to this fix #321. 

Protege 5.0.0-b23.

```
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
******************************************************************************** 
**                                  Protege                                   ** 
******************************************************************************** 
 
----------------- Initialising and Starting the OSGi Framework ----------------- 
FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory 
 
The OSGi framework has been initialised 
------------------------------- Starting Bundles ------------------------------- 
Starting bundle org.protege.common 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle org.eclipse.equinox.common 
Starting bundle org.protege.editor.core.application 
Starting bundle org.eclipse.equinox.registry 
Starting bundle org.protege.editor.core.application 
Starting bundle org.eclipse.equinox.registry 
Starting bundle org.apache.commons.io 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle org.protege.editor.owl 
Starting bundle slf4j.api 
Starting bundle com.google.guava 
Starting bundle org.eclipse.equinox.common 
Starting bundle jul.to.slf4j 
Starting bundle ch.qos.logback.classic 
Starting bundle org.apache.servicemix.bundles.javax-inject 
Starting bundle org.semanticweb.owl.owlapi 
Starting bundle ch.qos.logback.core 
Not starting bundle com.google.inject.assistedinject explicitly because it is a fragment bundle. 
Starting bundle log4j.over.slf4j 
Not starting bundle com.google.inject.multibindings explicitly because it is a fragment bundle. 
Starting bundle org.protege.common 
Starting bundle com.google.inject 
Starting bundle org.apache.servicemix.bundles.aopalliance 
Starting bundle org.semanticweb.hermit 
Starting bundle code-generation 
Starting bundle org.coode.owlviz 
Starting bundle org.protege.owl.rdf 
Starting bundle cellfie 
Starting bundle existentialquery 
Starting bundle org.protege.editor.owl.rdf 
Starting bundle org.protege.ontograf 
Starting bundle uk.ac.manchester.cs.owl.explanation 
Starting bundle org.coode.dlquery 
Starting bundle swrltab-plugin 
Starting bundle org.coode.browser 
The OSGi framework has been started 
 
------------------------------------ Protégé ----------------------------------- 
Protégé Desktop 
Version 5.0.0, Build beta-23 
 
 
----------------------------------- Platform ----------------------------------- 
Java: JVM 1.8.0_40-b26  Memory: 466M 
Language: en, Country: US 
Framework: Apache Software Foundation (1.7)  
OS: linux (3.13.0-77-generic) 
Processor: x86-64
 
 
------------------------------------ Plugins ----------------------------------- 
Plugin: HermiT (1.3.8.413) 
Plugin: OWL Code Generation Plug-in (2.0.0) 
Plugin: OWLViz (5.0.1) 
Plugin: OWLAPI RDF Library (2.0.1) 
Plugin: Cellfie Protege 5.0+ Plugin (2.0.0.beta-6) 
Plugin: Existential Query (2.0.0) 
Plugin: Protege SPARQL Plugin (2.0.1) 
Plugin: OntoGraf (2.0.2) 
Plugin: Explanation Workbench (3.0.0) 
Plugin: DL Query (3.0.1) 
Plugin: SWRLTab Protege 5.0+ Plugin (1.0.0.beta-10) 
Plugin: OWLDoc (3.0.2) 
 
	OWLAPI RDF Library Plugin has no plugin.xml resource 
OWL API Version: 4.1.3.20151118-2017 
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/ttania/ontologies/2016/1/untitled-ontology-162 
### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
------------------------------- Auto-update Check ------------------------------ 
Auto-update last performed: Mon Feb 22 12:23:33 PST 2016 
Auto-update has been performed today.  Not performing it again. 
 
OWL API Version: 4.1.3.20151118-2017 
------------------------------- Loading Ontology ------------------------------- 
Loading ontology from http://protege.stanford.edu/ontologies/pizza/pizza.owl 
Loading OntologyID(Anonymous-0) from http://protege.stanford.edu/ontologies/pizza/pizza.owl 
URL connection input stream is compressed using gzip 
dumping remaining triples 
_:genid419 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid413 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid395 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid407 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid401 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
done dumping remaining triples 
Loading for ontology and imports closure successfully completed in 385 ms 
 
---------------------------- Disposing of Workspace ---------------------------- 
Saved tab state for 'Active Ontology' tab 
Saved tab state for 'Entities' tab 
Saved tab state for 'DL Query' tab 
Saved tab state for 'Individuals by class' tab 
Saved workspace 
Disposed of 'Active Ontology' tab 
Disposed of 'Entities' tab 
Disposed of 'DL Query' tab 
Disposed of 'Individuals by class' tab 
Disposed of workspace 
 
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.awt.dnd.InvalidDnDOperationException: Drag and drop in progress
	at sun.awt.dnd.SunDragSourceContextPeer.setDragDropInProgress(SunDragSourceContextPeer.java:358) ~[na:1.8.0_40]
	at java.awt.dnd.DragSource.startDrag(DragSource.java:301) ~[na:1.8.0_40]
	at java.awt.dnd.DragSource.startDrag(DragSource.java:426) ~[na:1.8.0_40]
	at java.awt.dnd.DragGestureEvent.startDrag(DragGestureEvent.java:263) ~[na:1.8.0_40]
	at org.protege.editor.owl.ui.transfer.OWLObjectDragGestureListener.dragGestureRecognized(OWLObjectDragGestureListener.java:55) ~[na:na]
	at java.awt.dnd.DragGestureRecognizer.fireDragGestureRecognized(DragGestureRecognizer.java:361) ~[na:1.8.0_40]
	at sun.awt.X11.XMouseDragGestureRecognizer.mouseDragged(XMouseDragGestureRecognizer.java:219) ~[na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:320) ~[na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319) ~[na:1.8.0_40]
	at java.awt.Component.processMouseMotionEvent(Component.java:6573) ~[na:1.8.0_40]
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342) ~[na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6294) ~[na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4550) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2278) ~[na:1.8.0_40]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) ~[na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:724) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) ~[na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]

```

**Comment by rsgoncalves** [comment]
I managed to replicate this, even if for the same class it sometimes allowed me to drag & drop and other times not. Additionally, in some seemingly arbitrary cases, as you drag a class to owl:Thing, it appears to get deleted.

**Comment by matthewhorridge** [comment]
It looks like the ```setDragEnabled(true);``` in the changes related to #321 caused this.  The exception is thrown because of a double drag.  The setDragEnabled causes the JTree default drag and drop implementation to be used, but the drag gesture is recognised again by the OWLObjectDragGestureListener and a second drag is started.    In my understanding, setDragEnabled on a Tree should not be used with the custom drag gesture listener.

@bdionne Before we move forward on this, please can you explain the motivation for the changes in relation to #321 in a bit more detail?

**Comment by bdionne** [comment]
I wish to subclass `ToldOWLClassHierarchyViewComponent` and disable drag/drop. Disabled should be the default for `JTree` according to the docs. `OWLObjectTreeDragGestureListener` hard coded `canPerformDrag` to return true, which prevented me from disabling it

**Comment by matthewhorridge** [comment]
Thanks for the clarification.  Here's a followup question: Is the subclassing just/primarily to disable drag and drop?  Also, do you want to disable drag and drop everywhere in the UI?  If so, we could add a UI preference for this.

**Comment by bdionne** [comment]
We'll be using drag/drop in a few places, we just need to disable within the classes tree. The issue in the past has been modelers accidentally re-treeing things.

We'll also be adding popup menus on right clicks on the concepts to invoke actions, so subclassing seemed reasonable unless there's a better way to expose that functionality

**Comment by matthewhorridge** [comment]
o.k. I'll add an option for disabling drag and drop in (all) hierarchies.  

With regards to the popup menus, I could add a new plugin type for this.  You could then specify actions for the popup menu in a similar way to specifying actions for regular menus.

**Comment by bdionne** [comment]
both of those would be great , thanks. Looking this over again I see how I broke the other hierarchies, sorry about that.
