### ISSUE TITLE
Activating a syntax rendering view throws an exception

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege#336]
To reproduce, activate the RDF/XML, OWL/XML or functional syntax rendering view.

    error rendering ontology 
    java.lang.RuntimeException: java.lang.InterruptedException
    	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2141) ~[org.apache.felix.main.jar:na]
    	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1524) ~[org.apache.felix.main.jar:na]
    	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77) ~[org.apache.felix.main.jar:na]
    	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993) ~[org.apache.felix.main.jar:na]
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLWriter.startDocument(OWLXMLWriter.java:149) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLRenderer.render(OWLXMLRenderer.java:56) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLRenderer.render(OWLXMLRenderer.java:98) ~[na:na]
    	at org.protege.editor.owl.ui.view.ontology.OWLXMLRenderingViewComponent.renderOntology(OWLXMLRenderingViewComponent.java:20) ~[na:na]
    	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$1.run(AbstractOntologyRenderingViewComponent.java:116) ~[na:na]
    Caused by: java.lang.InterruptedException: null
    	at java.lang.Object.wait(Native Method) ~[na:1.8.0_74]
    	at java.lang.Object.wait(Object.java:502) ~[na:1.8.0_74]
    	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2136) ~[org.apache.felix.main.jar:na]
    	... 9 common frames omitted
    LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]

**Comment by rsgoncalves** [comment]
Triggering the OWL/XML rendering view on the koala ontology (http://protege.cim3.net/file/pub/ontologies/koala/koala.owl) results in the exception below.

    error rendering ontology 
    org.semanticweb.owlapi.model.OWLRuntimeException: java.io.InterruptedIOException
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLWriter.writeStartElement(OWLXMLWriter.java:182) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLObjectRenderer.visit(OWLXMLObjectRenderer.java:503) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.OWLClassImpl.accept(OWLClassImpl.java:253) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLObjectRenderer.visit(OWLXMLObjectRenderer.java:480) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.OWLSubClassOfAxiomImpl.accept(OWLSubClassOfAxiomImpl.java:117) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLObjectRenderer.visit(OWLXMLObjectRenderer.java:195) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.accept(OWLImmutableOntologyImpl.java:852) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.accept(ConcurrentOWLOntologyImpl.java:396) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLRenderer.render(OWLXMLRenderer.java:86) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLRenderer.render(OWLXMLRenderer.java:98) ~[na:na]
    	at org.protege.editor.owl.ui.view.ontology.OWLXMLRenderingViewComponent.renderOntology(OWLXMLRenderingViewComponent.java:20) ~[na:na]
    	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$1.run(AbstractOntologyRenderingViewComponent.java:116) ~[na:na]
    Caused by: java.io.InterruptedIOException: null
    	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$TextAreaWriter.write(AbstractOntologyRenderingViewComponent.java:244) ~[na:na]
    	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[na:1.8.0_74]
    	at java.io.BufferedWriter.write(BufferedWriter.java:230) ~[na:1.8.0_74]
    	at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_74]
    	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeElementStart(XMLWriterImpl.java:334) ~[na:na]
    	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl.writeStartElement(XMLWriterImpl.java:158) ~[na:na]
    	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLWriter.writeStartElement(OWLXMLWriter.java:180) ~[na:na]
    	... 11 common frames omitted
    LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]

**Comment by matthewhorridge** [comment]
I think I might ditch these views.  They don't offer any functionality beyond saving the ontology in a particular syntax.

**Comment by rsgoncalves** [comment]
They're useful to see how the ontology serialization will look like in different syntaxes without actually saving it. Purely for convenience, but nice anyway imo.

**Comment by csnyulas** [comment]
I also think is a nice feature. I don't know how many users are using it, but I definitely like it, and sometimes it helps debugging problems.

**Comment by tudorache** [comment]
Keeping this one, closing #286 
They are duplicate.

**Comment by tudorache** [comment]
Reported on the mailing list (2016-06-04):

I have installed 5.0.0 Desktop on an Ubuntu 15.10 Linux, after lengthy use of 5.0.0-beta-17. When I load my ontology and select the Entities tab, Protege behaves well but always throws the Exception below.  I imagine that something left over from my beta-17 installation is referencings some no-longer supplied renderer.  In any case, is there something I can do about this to robustly make it go away?

```
error rendering ontology
java.lang.RuntimeException: java.lang.InterruptedException
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2141) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1524) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993) ~[org.apache.felix.main.jar:na]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
    at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLObjectInverseOf(OWLDataFactoryImpl.java:1520) ~[na:na]
    at org.semanticweb.owlapi.rdf.RDFRendererBase$1.visit(RDFRendererBase.java:541) ~[na:na]
    at uk.ac.manchester.cs.owl.owlapi.OWLObjectPropertyImpl.accept(OWLObjectPropertyImpl.java:125) ~[na:na]
    at org.semanticweb.owlapi.rdf.RDFRendererBase.createGraph(RDFRendererBase.java:465) ~[na:na]
    at org.semanticweb.owlapi.rdf.RDFRendererBase.renderEntities(RDFRendererBase.java:251) ~[na:na]
    at org.semanticweb.owlapi.rdf.RDFRendererBase.renderInOntologySignatureEntities(RDFRendererBase.java:223) ~[na:na]
    at org.semanticweb.owlapi.rdf.RDFRendererBase.renderOntologyComponents(RDFRendererBase.java:209) ~[na:na]
    at org.semanticweb.owlapi.rdf.RDFRendererBase.render(RDFRendererBase.java:204) ~[na:na]
    at org.protege.editor.owl.ui.view.ontology.RDFXMLRenderingViewComponent.renderOntology(RDFXMLRenderingViewComponent.java:21) ~[na:na]
    at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$1.run(AbstractOntologyRenderingViewComponent.java:116) ~[na:na]
Caused by: java.lang.InterruptedException: null
    at java.lang.Object.wait(Native Method) ~[na:1.8.0_40]
    at java.lang.Object.wait(Object.java:502) ~[na:1.8.0_40]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2136) ~[org.apache.felix.main.jar:na]
    ... 14 common frames omitted
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]
error rendering ontology
org.semanticweb.owlapi.io.OWLRendererIOException: java.io.InterruptedIOException
    at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.flush(AbstractRenderer.java:93) ~[na:na]
    at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxFrameRenderer.writeOntology(ManchesterOWLSyntaxFrameRenderer.java:354) ~[na:na]
    at org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterOWLSyntaxRenderer.render(ManchesterOWLSyntaxRenderer.java:37) ~[na:na]
    at org.protege.editor.owl.ui.view.ontology.ManchesterSyntaxRenderingViewComponent.renderOntology(ManchesterSyntaxRenderingViewComponent.java:25) ~[na:na]
    at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$1.run(AbstractOntologyRenderingViewComponent.java:116) ~[na:na]
Caused by: java.io.InterruptedIOException: null
    at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$TextAreaWriter.write(AbstractOntologyRenderingViewComponent.java:244) ~[na:na]
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[na:1.8.0_40]
    at java.io.BufferedWriter.flush(BufferedWriter.java:253) ~[na:1.8.0_40]
    at org.semanticweb.owlapi.manchestersyntax.renderer.AbstractRenderer.flush(AbstractRenderer.java:91) ~[na:na]
    ... 4 common frames omitted
```

**Comment by tudorache** [comment]
Maybe a deadlock. From the mailing list:

I have somehow put 5.0.0 into a state with several (separate?) problems: (1)
Protege starts but shows no tabs (2) On my Ubuntu 15.10, there is no (?) way
to stop Protege except kill -9.  

~/.protege contains only logs directory.  Removing it does not inhibit the
above mentioned behavior

protege.log
<http://protege-project.136.n4.nabble.com/file/n4665792/protege.log>  

If another linux user starts Protege, the problem does not occur.

---

Screenshot_2016-07-11_19-38-43.png
<http://protege-project.136.n4.nabble.com/file/n4665796/Screenshot_2016-07-11_19-38-43.png>  
threadDump.txt
<http://protege-project.136.n4.nabble.com/file/n4665796/threadDump.txt>  

In the shell window that started Protege via run.sh, CTRL-C is ignored. 
From another shell, sig HUP via kill -1 <pid> is ignored with no message.

You suggest "removing these views from your default editor layout (since the
culprit view is initialized with the editor in your case)".  How do I do
this?  I am clueless what is keeping the state of my previous execution of
Protege.  I find nothing in ~/.protege but logs, so I imagined that sig KILL
followed by removing ~/.protege would be rather like a new installation, but
the frozen behavior recurs.

Note that if I create a new Linux user and start Protege from the same
installation, there is no freezing behavior.

**Comment by matthewhorridge** [comment]
Remove in 6.0.0.  Save the ontology to file instead in the syntax of choice and look at it in the text editor of choice (with syntax highlighting).
