### ISSUE TITLE
Loading import should not throw exception before attempting to resolve missing import

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege#360]
The exception below is thrown right before the prompt to 'Resolve missing import'. To replicate: create ontology 'O' with an import to some ontology in the file system. Close and reopen Protege. Load 'O'.

    ------------------------------- Loading Ontology ------------------------------- 
    Loading ontology from file:/Users/rgoncalves/Documents/ontologies/import/testImport.owl 
    Loading OntologyID(Anonymous-0) from file:/Users/rgoncalves/Documents/ontologies/import/testImport.owl 
    Cannot open a stream to http://protege.stanford.edu/ontologies/groceries. 
    java.io.FileNotFoundException: http://protege.stanford.edu/ontologies/groceries
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836) ~[na:1.8.0_74]
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_74]
    	at org.protege.editor.owl.model.io.WebConnectionIRIMapper.getDocumentIRI(WebConnectionIRIMapper.java:42) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.getDocumentIRIFromMappers(OWLOntologyManagerImpl.java:1382) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:931) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1563) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1599) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1568) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:200) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1507) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:365) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:253) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:692) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:196) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:357) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) [na:1.8.0_74]
    	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327) [na:1.8.0_74]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:140) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:212) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1035) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:972) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:278) [protege-editor-owl.jar:na]
    	at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201) [protege-editor-owl.jar:na]
    	at org.protege.editor.owl.OWLEditorKit.handleLoadRequest(OWLEditorKit.java:195) [protege-editor-owl.jar:na]
    	at org.protege.editor.core.ProtegeManager.openAndSetupEditorKit(ProtegeManager.java:207) [protege-editor-core.jar:na]
    	at org.protege.editor.core.ui.action.OpenAction.openInNewWorkspace(OpenAction.java:53) [protege-editor-core.jar:na]
    	at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:210) [protege-editor-core.jar:na]
    	at org.protege.editor.core.ui.action.OpenAction.actionPerformed(OpenAction.java:29) [protege-editor-core.jar:na]
    	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [na:1.8.0_74]
    	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [na:1.8.0_74]
    	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.8.0_74]
    	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [na:1.8.0_74]
    	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) [na:1.8.0_74]
    	at javax.swing.AbstractButton.doClick(AbstractButton.java:356) [na:1.8.0_74]
    	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802) [na:1.8.0_74]
    	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663) [na:1.8.0_74]
    	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882) [na:1.8.0_74]
    	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699) [na:1.8.0_74]
    	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) [na:1.8.0_74]
    	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) [na:1.8.0_74]
    	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677) [na:1.8.0_74]
    	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307) [na:1.8.0_74]
    	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293) [na:1.8.0_74]
    	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974) [na:1.8.0_74]
    	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966) [na:1.8.0_74]
    	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845) [na:1.8.0_74]
    	at javax.swing.JComboBox.processKeyEvent(JComboBox.java:1418) [na:1.8.0_74]
    	at java.awt.Component.processEvent(Component.java:6312) [na:1.8.0_74]
    	at java.awt.Container.processEvent(Container.java:2236) [na:1.8.0_74]
    	at java.awt.Component.dispatchEventImpl(Component.java:4891) [na:1.8.0_74]
    	at java.awt.Container.dispatchEventImpl(Container.java:2294) [na:1.8.0_74]
    	at java.awt.Component.dispatchEvent(Component.java:4713) [na:1.8.0_74]
    	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) [na:1.8.0_74]
    	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806) [na:1.8.0_74]
    	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074) [na:1.8.0_74]
    	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945) [na:1.8.0_74]
    	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771) [na:1.8.0_74]
    	at java.awt.Component.dispatchEventImpl(Component.java:4762) [na:1.8.0_74]
    	at java.awt.Container.dispatchEventImpl(Container.java:2294) [na:1.8.0_74]
    	at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_74]
    	at java.awt.Component.dispatchEvent(Component.java:4713) [na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [na:1.8.0_74]
    	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:709) [na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:703) [na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:731) [na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:729) [na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_74]

**Comment by matthewhorridge** [comment]
I'm not able to reproduce this with the head of master

**Comment by matthewhorridge** [comment]
This was (it's changed now) just a log message - no exception was actually thrown, it was just logged.
