### ISSUE TITLE
org.semanticweb.owlapi.model.OWLRuntimeException: Not OWLDataProperty

### ISSUE THREAD

**Issue by wismill** [protegeproject/protege#370]
I faced an error `org.semanticweb.owlapi.model.OWLRuntimeException: Not OWLDataProperty` using Protégé git master (402839a556d289901a30787ba5ffbb1cd8860193) but *not* with protégé 5.0.0-beta-23. There is an error windows opening but empty and the Turtle file (see below) is not loaded.

- OS: Windows 7 64 bits
- Java 8

File:
```
@prefix : <http://www.test.org/qudt#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix qudt: <http://qudt.org/schema/qudt#> .


<http://www.test.org/qudt>
  a owl:Ontology ;
  owl:imports <http://qudt.org/1.1/vocab/dimensionalunit> .

:hasQuantityKind
  a owl:ObjectProperty ;
  owl:propertyChainAxiom (
    qudt:quantityValue
    qudt:unit
    qudt:quantityKind
  ) .
```

Error message from the console:

```
An error was thrown: Not OWLDataProperty
org.semanticweb.owlapi.model.OWLRuntimeException: Not OWLDataProperty
        at uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl.asOWLDataProperty(OWLAnnotationPropertyImpl.java:123) ~[na:na]
        at org.semanticweb.owlapi.util.OWLAnnotationPropertyTransformer.visit(OWLAnnotationPropertyTransformer.java:859) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLSubAnnotationPropertyOfAxiomImpl.accept(OWLSubAnnotationPropertyOfAxiomImpl.java:119) ~[na:na]
        at org.semanticweb.owlapi.util.OWLAnnotationPropertyTransformer.transformObject(OWLAnnotationPropertyTransformer.java:96) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.fixIllegalPunnings(OWLOntologyManagerImpl.java:1116) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1062) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1610) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1646) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1558) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1507) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:365) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:235) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:655) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:196) ~[na:na]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source) ~[na:1.8.0_73]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:140) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1610) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1646) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1558) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1507) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:365) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:235) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:655) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:196) ~[na:na]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source) ~[na:1.8.0_73]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:140) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1610) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1646) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1558) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1507) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:365) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:235) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:655) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:196) ~[na:na]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[na:1.8.0_73]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source) ~[na:1.8.0_73]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:140) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1610) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1646) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1558) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194) ~[na:na]
        at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1507) ~[na:na]
        at org.semanticweb.owlapi.rio.RioOWLRDFConsumerAdapter.handleStatement(RioOWLRDFConsumerAdapter.java:122) ~[na:na]
        at org.semanticweb.owlapi.rio.RioParserImpl$RioParserRDFHandler.handleStatement(RioParserImpl.java:341) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.reportStatement(TurtleParser.java:1157) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.parseObject(TurtleParser.java:504) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:427) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:420) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:384) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:260) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:215) ~[na:na]
        at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:159) ~[na:na]
        at org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:257) ~[na:na]
        at org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:191) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:960) ~[na:na]
        at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:278) ~[na:na]
        at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201) ~[na:na]
        at org.protege.editor.owl.OWLEditorKit.handleLoadRecentRequest(OWLEditorKit.java:189) ~[na:na]
        at org.protege.editor.core.ProtegeManager.openAndSetupRecentEditorKit(ProtegeManager.java:263) ~[na:na]
        at org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.openInNewWorkspace(OpenRecentAction.java:90) ~[na:na]
        at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:210) ~[na:na]
        at org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.actionPerformed(OpenRecentAction.java:76) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [na:1.8.0_73]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [na:1.8.0_73]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [na:1.8.0_73]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [na:1.8.0_73]
        at javax.swing.AbstractButton.doClick(Unknown Source) [na:1.8.0_73]
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) [na:1.8.0_73]
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source) [na:1.8.0_73]
        at java.awt.Component.processMouseEvent(Unknown Source) [na:1.8.0_73]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.Component.processEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.Container.processEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
        at java.awt.Window.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
        at java.awt.Component.dispatchEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_73]
        at java.awt.EventQueue.access$500(Unknown Source) [na:1.8.0_73]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_73]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_73]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_73]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_73]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_73]
        at java.awt.EventQueue$4.run(Unknown Source) [na:1.8.0_73]
        at java.awt.EventQueue$4.run(Unknown Source) [na:1.8.0_73]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_73]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_73]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.8.0_73]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_73]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_73]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_73]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_73]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_73]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_73]
```

**Comment by ignazio1977** [comment]
This is an OWLAPI bug.

**Comment by wismill** [comment]
Ok. Should we let this issue open until OWLAPI is updated in Protégé?

**Comment by jgrzebyta** [comment]
I have very similar error but in my case it is ***Not OWLObjectProperty***.

* Protege: Version 5.0.0, Build beta-24
Build beta-23 works fine.
* Java: 8
* OS: Ubuntu 
* Ontology accessible at https://dl.dropboxusercontent.com/u/16044174/AdaMeta-integrated.owl

stackTrace:

```
Message:     An error was thrown: Not OWLObjectProperty
org.semanticweb.owlapi.model.OWLRuntimeException
StackTrace:  
    uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl.asOWLObjectProperty(OWLAnnotationPropertyImpl.java:138)
    org.semanticweb.owlapi.util.OWLAnnotationPropertyTransformer.visit(OWLAnnotationPropertyTransformer.java:855)
    uk.ac.manchester.cs.owl.owlapi.OWLSubAnnotationPropertyOfAxiomImpl.accept(OWLSubAnnotationPropertyOfAxiomImpl.java:119)
    org.semanticweb.owlapi.util.OWLAnnotationPropertyTransformer.transformObject(OWLAnnotationPropertyTransformer.java:96)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.fixIllegalPunnings(OWLOntologyManagerImpl.java:1116)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1062)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:960)
    org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:278)
    org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201)
    org.protege.editor.owl.OWLEditorKit.handleLoadRequest(OWLEditorKit.java:195)
    org.protege.editor.core.ProtegeManager.openAndSetupEditorKit(ProtegeManager.java:207)
    org.protege.editor.core.ui.action.OpenAction.openInNewWorkspace(OpenAction.java:53)
    org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:210)
    org.protege.editor.core.ui.action.OpenAction.actionPerformed(OpenAction.java:29)
    javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    java.awt.Component.processMouseEvent(Component.java:6525)
    javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    java.awt.Component.processEvent(Component.java:6290)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    java.awt.Container.dispatchEventImpl(Container.java:2278)
    java.awt.Window.dispatchEventImpl(Window.java:2750)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:702)
    java.awt.EventQueue$3.run(EventQueue.java:696)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.awt.EventQueue$4.run(EventQueue.java:724)
    java.awt.EventQueue$4.run(EventQueue.java:722)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
