### ISSUE TITLE
Protege crashes when rendering annotation values that are IRIs that render as empty strings

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#400]
Loading PROV-O ontology form its official location ( https://www.w3.org/ns/prov-o.owl ) into Protege causes it to throw the follwoing exception over and over again, while the UI will stop refreshing, and Protege basically becomes unusable.

```
Level:       ERROR
Time:        1462001516702
Message:     Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.IllegalArgumentException
StackTrace:  
    java.text.AttributedString.addAttribute(AttributedString.java:325)
    org.protege.editor.owl.ui.renderer.layout.Paragraph.setSize(Paragraph.java:152)
    org.protege.editor.owl.ui.renderer.layout.Paragraph.<init>(Paragraph.java:63)
    org.protege.editor.owl.ui.renderer.layout.Paragraph.<init>(Paragraph.java:47)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderEntities(OWLAnnotationCellRenderer2.java:436)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderIRI(OWLAnnotationCellRenderer2.java:347)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.access$000(OWLAnnotationCellRenderer2.java:35)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2$1.visit(OWLAnnotationCellRenderer2.java:314)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2$1.visit(OWLAnnotationCellRenderer2.java:312)
    org.semanticweb.owlapi.model.IRI.accept(IRI.java:543)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderAnnotationValue(OWLAnnotationCellRenderer2.java:312)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderCellValue(OWLAnnotationCellRenderer2.java:196)
    org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.fillPage(OWLAnnotationCellRenderer2.java:160)
    org.protege.editor.owl.ui.renderer.layout.PageCellRenderer.getListCellRendererComponent(PageCellRenderer.java:93)
    org.protege.editor.owl.ui.framelist.OWLFrameListRenderer.getListCellRendererComponent(OWLFrameListRenderer.java:150)
    org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:260)
    org.protege.editor.owl.ui.framelist.OWLFrameList$OWLFrameListUI.updateLayoutState(OWLFrameList.java:837)
    javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
    javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:264)
    javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:240)
    javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    javax.swing.JComponent.paintComponent(JComponent.java:780)
    org.protege.editor.core.ui.list.MList.paintComponent(MList.java:400)
    javax.swing.JComponent.paint(JComponent.java:1056)
    javax.swing.JComponent.paintToOffscreen(JComponent.java:5219)
    javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1572)
    javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1495)
    javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306)
    javax.swing.RepaintManager.paint(RepaintManager.java:1265)
    javax.swing.JComponent._paintImmediately(JComponent.java:5167)
    javax.swing.JComponent.paintImmediately(JComponent.java:4978)
    javax.swing.RepaintManager$4.run(RepaintManager.java:824)
    javax.swing.RepaintManager$4.run(RepaintManager.java:807)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807)
    javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782)
    javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731)
    javax.swing.RepaintManager.access$1300(RepaintManager.java:64)
    javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720)
    java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:702)
    java.awt.EventQueue$3.run(EventQueue.java:696)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This may be a bad ontology, containing some illegal information (although it's a quite important one), however, a tool should not become unusable just because the content it tries to display is unexpected. Exceptions should be caught and handled graciously, if possible.

**Comment by csnyulas** [comment]
from the console:
```
java.lang.IllegalArgumentException: Can't add attribute to 0-length text
	at java.text.AttributedString.addAttribute(AttributedString.java:325) ~[na:1.8.0_40]
	at org.protege.editor.owl.ui.renderer.layout.Paragraph.setSize(Paragraph.java:152) ~[na:na]
	at org.protege.editor.owl.ui.renderer.layout.Paragraph.<init>(Paragraph.java:63) ~[na:na]
	at org.protege.editor.owl.ui.renderer.layout.Paragraph.<init>(Paragraph.java:47) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderEntities(OWLAnnotationCellRenderer2.java:436) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderIRI(OWLAnnotationCellRenderer2.java:347) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.access$000(OWLAnnotationCellRenderer2.java:35) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2$1.visit(OWLAnnotationCellRenderer2.java:314) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2$1.visit(OWLAnnotationCellRenderer2.java:312) ~[na:na]
	at org.semanticweb.owlapi.model.IRI.accept(IRI.java:543) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderAnnotationValue(OWLAnnotationCellRenderer2.java:312) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.renderCellValue(OWLAnnotationCellRenderer2.java:196) ~[na:na]
	at org.protege.editor.owl.ui.renderer.OWLAnnotationCellRenderer2.fillPage(OWLAnnotationCellRenderer2.java:160) ~[na:na]
	at org.protege.editor.owl.ui.renderer.layout.PageCellRenderer.getListCellRendererComponent(PageCellRenderer.java:93) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameListRenderer.getListCellRendererComponent(OWLFrameListRenderer.java:150) ~[na:na]
	at org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:260) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList$OWLFrameListUI.updateLayoutState(OWLFrameList.java:837) ~[na:na]
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311) ~[na:1.8.0_40]
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578) ~[na:1.8.0_40]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662) ~[na:1.8.0_40]
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791) ~[na:1.8.0_40]
	at java.awt.Container.layout(Container.java:1508) ~[na:1.8.0_40]
	at java.awt.Container.doLayout(Container.java:1497) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1693) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validateTree(Container.java:1702) ~[na:1.8.0_40]
	at java.awt.Container.validate(Container.java:1628) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:704) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:702) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:701) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1719) ~[na:1.8.0_40]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) ~[na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) ~[na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
Uncaught Exception in thread 'AWT-EventQueue-0' 
```

**Comment by matthewhorridge** [comment]
This is exhibited when the rendering manager returns an empty string for the rendering.  It arises with prov because prov adds isDefinedBy annotations with an IRI value equal to the prov prefix.  The renderer turns this into an empty string.
