### ISSUE TITLE
Scrambled UI after waking up from suspend

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#411]
Got this exception thrown over and over again after waking up from suspend on Ubuntu.
Protege surface was also scrambled, and only parts of them rendered.

```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
	at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:145) ~[na:1.8.0_40]
	at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:353) ~[na:1.8.0_40]
	at sun.java2d.SurfaceDataProxy.updateSurfaceData(SurfaceDataProxy.java:498) ~[na:1.8.0_40]
	at sun.java2d.SurfaceDataProxy.replaceData(SurfaceDataProxy.java:455) ~[na:1.8.0_40]
	at sun.java2d.SurfaceData.getSourceSurfaceData(SurfaceData.java:233) ~[na:1.8.0_40]
	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:566) ~[na:1.8.0_40]
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67) ~[na:1.8.0_40]
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014) ~[na:1.8.0_40]
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318) ~[na:1.8.0_40]
	at sun.awt.image.ImageRepresentation.drawToBufImage(ImageRepresentation.java:813) ~[na:1.8.0_40]
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1021) ~[na:1.8.0_40]
	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186) ~[na:1.8.0_40]
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318) ~[na:1.8.0_40]
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296) ~[na:1.8.0_40]
	at javax.swing.ImageIcon.paintIcon(ImageIcon.java:425) ~[na:1.8.0_40]
	at javax.swing.plaf.IconUIResource.paintIcon(IconUIResource.java:72) ~[na:1.8.0_40]
	at javax.swing.plaf.basic.BasicButtonUI.paintIcon(BasicButtonUI.java:292) ~[na:1.8.0_40]
	at javax.swing.plaf.basic.BasicButtonUI.paint(BasicButtonUI.java:216) ~[na:1.8.0_40]
	at com.jgoodies.looks.plastic.PlasticButtonUI.update(PlasticButtonUI.java:98) ~[na:na]
	at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1056) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_40]
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_40]
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5226) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1572) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1495) ~[na:1.8.0_40]
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306) ~[na:1.8.0_40]
	at javax.swing.RepaintManager.paint(RepaintManager.java:1265) ~[na:1.8.0_40]
	at javax.swing.JComponent.paint(JComponent.java:1042) ~[na:1.8.0_40]
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39) ~[na:1.8.0_40]
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79) ~[na:1.8.0_40]
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116) ~[na:1.8.0_40]
	at java.awt.Container.paint(Container.java:1973) ~[na:1.8.0_40]
	at java.awt.Window.paint(Window.java:3912) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:835) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:807) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807) ~[na:1.8.0_40]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782) ~[na:1.8.0_40]
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731) ~[na:1.8.0_40]
	at javax.swing.RepaintManager.access$1300(RepaintManager.java:64) ~[na:1.8.0_40]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720) ~[na:1.8.0_40]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) ~[na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) ~[na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
```

**Comment by matthewhorridge** [comment]
This is a JDK problem:  http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7172749
