### ISSUE TITLE
General class axiom editor throws exceptions on other types of axioms

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#450]
To reproduce:
* Create a new ontology
* Add a new object property R
* Go to Active Ontology > General class axiom > Add (+)
* Enter "Transitive R" in the editor

Protege throws exception:

`java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLTransitiveObjectPropertyAxiomImpl cannot be cast to org.semanticweb.owlapi.model.OWLClassAxiom
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassAxiomChecker.createObject(OWLClassAxiomChecker.java:45) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassAxiomChecker.check(OWLClassAxiomChecker.java:35) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.checkExpression(ExpressionEditor.java:211) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.handleTimer(ExpressionEditor.java:225) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.lambda$new$60(ExpressionEditor.java:112) [protege-editor-owl.jar:na]
	at javax.swing.Timer.fireActionPerformed(Timer.java:313) ~[na:1.8.0_77]
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245) ~[na:1.8.0_77]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_77]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[na:1.8.0_77]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_77]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_77]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_77]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_77]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_77]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) ~[na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) ~[na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) ~[na:1.8.0_77]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) ~[na:1.8.0_77]`

**Comment by matthewhorridge** [comment]
This editor only allows axioms of the form C SubClassOf D, C EquivalentTo D and C DisjointWith D to be edited but the parser allows any kind of axiom to be entered.  Unfortunately, the parser does not support just class axiom parsing.
