### ISSUE TITLE
Removing the active ontology causes problems

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege#479]
When a user logs out and then back in, [exceptions](https://gist.github.com/bdionne/d9946b2336d1337ba7407a5d786496bd) are thrown, almost always null pointers in the `NoOpReasoner`.

**Comment by matthewhorridge** [comment]
@bdionne is the a Protege issue or a Protege-Client/Server issue?

**Comment by bdionne** [comment]
Not sure, I dug into it a bit and the problem occurs when this [method](https://github.com/protegeproject/protege-client/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/client/ClientSession.java#L108) is called. Perhaps we shouldn't be closing ontologies? The errors seem to come from a couple of places, .eg. the metrics table model in the active ontology panel.

**Comment by matthewhorridge** [comment]
> Perhaps we shouldn't be closing ontologies?

Yes.  For historical reasons there is an assumption that there is always an active ontology.  We wouldn't do things this way now, but we are kind of stuck with it for Protege 5.

**Comment by bdionne** [comment]
I see, I'll take this to the client then, thanks

**Comment by bdionne** [comment]
I dug into this a lot deeper and it appears this [NoOpReasoner](https://github.com/protegeproject/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/model/inference/NoOpReasoner.java#L195) is getting a null from the call to `getOWLOntologyManager`. Not sure, but at a glance it looks like the `dispose` method needs to be implemented.

**Comment by matthewhorridge** [comment]
This makes sense.  In previous versions of the OWL API removing an ontology from its manager would not remove the reference to the manager from the ontology.  Now this is set to null and hence the NPE.  Will take a look.  In any case, I need to add some code to ensure that there is always one ontology left in the manager and if not dispose of the workspace/editor kit.

**Comment by rsgoncalves** [comment]
When I logout while in the 'Active Ontology' tab, where the Metrics view is placed by default, I get the exception below. It comes from the Metrics view.

    Exception thrown by listener: org.protege.editor.owl.ui.view.AbstractActiveOntologyViewComponent$$Lambda$68/875452801.  Detatching bad listener. 
    Uncaught Exception in thread 'AWT-EventQueue-0' 
    java.lang.NullPointerException: null
    	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getImportsClosure(OWLImmutableOntologyImpl.java:842) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getImportsClosure(ConcurrentOWLOntologyImpl.java:190) ~[na:na]
    	at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getOntologies(AbstractOWLMetric.java:99) ~[na:na]
    	at org.semanticweb.owlapi.metrics.AxiomCount.recomputeMetric(AxiomCount.java:42) ~[na:na]
    	at org.semanticweb.owlapi.metrics.AxiomCount.recomputeMetric(AxiomCount.java:27) ~[na:na]
    	at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:82) ~[na:na]
    	at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:36) ~[na:na]
    	at org.protege.editor.owl.ui.metrics.MetricsTableModel.getValueAt(MetricsTableModel.java:46) ~[na:na]
    	at org.protege.editor.owl.ui.metrics.MetricsPanel$3.getTableCellRendererComponent(MetricsPanel.java:155) ~[na:na]
    	at javax.swing.JTable.prepareRenderer(JTable.java:5723) ~[na:1.8.0_74]
    	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114) ~[na:1.8.0_74]
    	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016) ~[na:1.8.0_74]
    	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812) ~[na:1.8.0_74]
    	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[na:1.8.0_74]
    	at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[na:1.8.0_74]
    	at javax.swing.JComponent.paint(JComponent.java:1056) ~[na:1.8.0_74]
    	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager.paint(RepaintManager.java:1272) ~[na:1.8.0_74]
    	at javax.swing.JComponent._paintImmediately(JComponent.java:5158) ~[na:1.8.0_74]
    	at javax.swing.JComponent.paintImmediately(JComponent.java:4969) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager$4.run(RepaintManager.java:831) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager$4.run(RepaintManager.java:814) ~[na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) ~[na:1.8.0_74]
    	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732) ~[na:1.8.0_74]
    	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[na:1.8.0_74]
    	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_74]
    LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]

**Comment by matthewhorridge** [comment]
Related to #488.
