### ISSUE TITLE
UI exception is thrown in some cases after committing changes to a server

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege#491]
I don't have a precise set of steps to replicate this. It happened in the Entities tab, after committing some changes to the server.

    Uncaught Exception in thread 'AWT-EventQueue-0' 
    java.lang.NullPointerException: null
    	at org.coode.mdock.HorizontalSplitter.convertToLocation(HorizontalSplitter.java:78) ~[na:na]
    	at org.coode.mdock.Splitter.endDragging(Splitter.java:157) ~[na:na]
    	at org.coode.mdock.Splitter$1.mouseReleased(Splitter.java:79) ~[na:na]
    	at java.awt.Component.processMouseEvent(Component.java:6535) ~[na:1.8.0_74]
    	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_74]
    	at java.awt.Component.processEvent(Component.java:6300) ~[na:1.8.0_74]
    	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_74]
    	at java.awt.Component.dispatchEventImpl(Component.java:4891) ~[na:1.8.0_74]
    	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_74]
    	at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_74]
    	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_74]
    	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[na:1.8.0_74]
    	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_74]
    	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_74]
    	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_74]
    	at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_74]
    	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_74]
    LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]

**Comment by matthewhorridge** [comment]
Filed this as an mdock issue:  https://github.com/matthewhorridge/mdock/issues/2
