### ISSUE TITLE
Protege behaves badly when reopening an ontology

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege#509]
Steps to reproduce:
1. Open 2 ontologies in the same Protege window,
2. Go to "Entities" tab,
3. Close one of the ontologies using "File > Loaded ontology sources" menu. To close an ontology: choose the ontology and click the close (X) icon,
4. Open the ontology that was closed before. Make sure you are still in the "Entities" tab,
5. Protege behaved badly.

(The same error will happen even you open a different ontology)

Error log shows:

```
2016-08-11 14:15:51.116 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
    at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getImportsClosure(OWLImmutableOntologyImpl.java:842) ~[na:na]
    at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getImportsClosure(ConcurrentOWLOntologyImpl.java:190) ~[na:na]
    at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getOntologies(AbstractOWLMetric.java:99) ~[na:na]
    at org.semanticweb.owlapi.metrics.AxiomCount.recomputeMetric(AxiomCount.java:42) ~[na:na]
    at org.semanticweb.owlapi.metrics.AxiomCount.recomputeMetric(AxiomCount.java:27) ~[na:na]
    at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:82) ~[na:na]
    at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:36) ~[na:na]
    at org.protege.editor.owl.ui.metrics.MetricsTableModel.getValueAt(MetricsTableModel.java:46) ~[na:na]
    at org.protege.editor.owl.ui.metrics.MetricsPanel$3.getTableCellRendererComponent(MetricsPanel.java:155) ~[na:na]
    at javax.swing.JTable.prepareRenderer(JTable.java:5723) ~[na:1.8.0_40]
    at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114) ~[na:1.8.0_40]
    at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016) ~[na:1.8.0_40]
...
```

Other possible error:

```
2016-07-22 13:48:31.242 [AWT-EventQueue-0] WARN  OWLCellRenderer    An error occurred whilst highlighting an unsatisfiable property: {}
java.lang.NullPointerException: null
    at org.protege.editor.owl.model.inference.NoOpReasoner.getBottomObjectPropertyNode(NoOpReasoner.java:195) ~[protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.renderer.OWLCellRenderer.lambda$highlightPropertyIfUnsatisfiable$18(OWLCellRenderer.java:913) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.model.inference.DisplayedInferencePreferences.executeTask(DisplayedInferencePreferences.java:118) ~[protege-editor-owl.jar:na]
    at org.protege.editor.owl.model.inference.ReasonerPreferences.executeTask(ReasonerPreferences.java:182) ~[protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.renderer.OWLCellRenderer.highlightPropertyIfUnsatisfiable(OWLCellRenderer.java:908) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.renderer.OWLCellRenderer.renderToken(OWLCellRenderer.java:807) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.renderer.OWLCellRenderer.highlightText(OWLCellRenderer.java:743) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.renderer.OWLCellRenderer.prepareTextPane(OWLCellRenderer.java:715) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.renderer.OWLCellRenderer.prepareRenderer(OWLCellRenderer.java:483) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.renderer.OWLCellRenderer.getTreeCellRendererComponent(OWLCellRenderer.java:369) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.tree.OWLObjectTreeCellRenderer.getTreeCellRendererComponent(OWLObjectTreeCellRenderer.java:34) [protege-editor-owl.jar:na]
    at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807) [na:1.8.0_66]
...
```

The error is observable in Protege 5.0.0.

**Comment by johardi** [comment]
The unit tests related to NoOpReasoner are failing
```
Tests run: 12, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.069 sec <<< FAILURE!
shouldGetBottomDataPropertyNode(org.protege.editor.owl.model.inference.NoOpReasoner_TestCase)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <[owlBottomDataProperty]>
     but: was <[owl:bottomDataProperty]>
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
       	at org.protege.editor.owl.model.inference.NoOpReasoner_TestCase.shouldGetBottomDataPropertyNode(NoOpReasoner_TestCase.java:94)

shouldGetBottomObjectPropertyNode(org.protege.editor.owl.model.inference.NoOpReasoner_TestCase)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <[owlBottomObjectProperty]>
     but: was <[owl:bottomObjectProperty]>
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
       	at org.protege.editor.owl.model.inference.NoOpReasoner_TestCase.shouldGetBottomObjectPropertyNode(NoOpReasoner_TestCase.java:82)

shouldGetTopDataPropertyNode(org.protege.editor.owl.model.inference.NoOpReasoner_TestCase)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <[owlTopDataProperty]>
     but: was <[owl:topDataProperty]>
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
       	at org.protege.editor.owl.model.inference.NoOpReasoner_TestCase.shouldGetTopDataPropertyNode(NoOpReasoner_TestCase.java:88)

shouldGetBottomClassNode(org.protege.editor.owl.model.inference.NoOpReasoner_TestCase)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <[owlNothing]>
     but: was <[owl:Nothing]>
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
       	at org.protege.editor.owl.model.inference.NoOpReasoner_TestCase.shouldGetBottomClassNode(NoOpReasoner_TestCase.java:70)

shouldGetTopObjectPropertyNode(org.protege.editor.owl.model.inference.NoOpReasoner_TestCase)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <[owlTopObjectProperty]>
     but: was <[owl:topObjectProperty]>
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
       	at org.protege.editor.owl.model.inference.NoOpReasoner_TestCase.shouldGetTopObjectPropertyNode(NoOpReasoner_TestCase.java:76)

shouldGetTopClassNode(org.protege.editor.owl.model.inference.NoOpReasoner_TestCase)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <[owlThing]>
     but: was <[owl:Thing]>
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
       	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
       	at org.protege.editor.owl.model.inference.NoOpReasoner_TestCase.shouldGetTopClassNode(NoOpReasoner_TestCase.java:64)
```

**Comment by matthewhorridge** [comment]
Seems to be working now
