### ISSUE TITLE
Exception on start: libFaCTPlusPlusJNI.so: libstdc++.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by danbst** [protegeproject/protege#540]
I've installed FaCT plugin, but don't have the binaries in PATH yet. After Protege restart, I got this

```
org.semanticweb.owlapi.model.OWLRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/ProtegeCache-ae3d8c63-fddc-4f42-9b90-c33ee7b8a045/bundle34/version0.0/bundle.jar-lib/0/lib/native/32bit/libFaCTPlusPlusJNI.so: libstdc++.so.6: cannot open shared object file: No such file or directory
	at uk.ac.manchester.cs.factplusplus.protege.FaCTPlusPlusFactory.getReasonerFactory(Unknown Source)
	at org.protege.editor.owl.model.inference.ReasonerInfoComparator.compare(ReasonerInfoComparator.java:9)
	at org.protege.editor.owl.model.inference.ReasonerInfoComparator.compare(ReasonerInfoComparator.java:5)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.protege.editor.owl.model.OWLWorkspace.rebuildReasonerMenu(OWLWorkspace.java:558)
	at org.protege.editor.owl.model.OWLWorkspace.initialiseExtraMenuItems(OWLWorkspace.java:434)
	at org.protege.editor.core.ui.workspace.WorkspaceFrame.createUI(WorkspaceFrame.java:140)
	at org.protege.editor.core.ui.workspace.WorkspaceFrame.<init>(WorkspaceFrame.java:54)
	at org.protege.editor.core.ui.workspace.WorkspaceManager.addWorkspace(WorkspaceManager.java:47)
	at org.protege.editor.core.editorkit.EditorKitManager.addEditorKit(EditorKitManager.java:44)
	at org.protege.editor.core.ProtegeManager.createAndSetupNewEditorKit(ProtegeManager.java:139)
	at org.protege.editor.core.ProtegeManager.createAndSetupNewEditorKit(ProtegeManager.java:129)
	at org.protege.editor.core.ProtegeApplication.createAndSetupDefaultEditorKit(ProtegeApplication.java:470)
	at org.protege.editor.core.ProtegeApplication.startApplication(ProtegeApplication.java:414)
	at org.protege.editor.core.ProtegeApplication.reallyStart(ProtegeApplication.java:108)
	at org.protege.editor.core.ProtegeApplication.lambda$start$8(ProtegeApplication.java:89)
	at org.apache.felix.framework.util.EventDispatcher.invokeFrameworkListenerCallback(EventDispatcher.java:836)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:786)
	at org.apache.felix.framework.util.EventDispatcher.run(EventDispatcher.java:1099)
	at org.apache.felix.framework.util.EventDispatcher.access$000(EventDispatcher.java:55)
	at org.apache.felix.framework.util.EventDispatcher$1.run(EventDispatcher.java:102)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/ProtegeCache-ae3d8c63-fddc-4f42-9b90-c33ee7b8a045/bundle34/version0.0/bundle.jar-lib/0/lib/native/32bit/libFaCTPlusPlusJNI.so: libstdc++.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1837)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at uk.ac.manchester.cs.factplusplus.FaCTPlusPlus.<clinit>(Unknown Source)
	... 26 more
```

Protege 5.0.0

**Comment by tsarkov** [comment]
All FaCT++ binaries comes with the plugin. What is missing here is a standard C++ library. A simple way to get it is to install a relatively recent GCC (version 4.8 or later).

**Comment by danbst** [comment]
Thanks, after setting correct LD_LIBRARY_PATH plugin loads and runs.
