### ISSUE TITLE
java.io.InvalidClassException: org.protege.editor.core.editorkit.EditorKitDescriptor; local class incompatible: stream classdesc serialVersionUID = 3407968599072820006

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#552]
Observed in 5.1.0 Snapshot from 20161003 in Windows (potentially also in Linux):

Sometimes I get this exception when I start Protege:
```
...
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
********************************************************************************
**                                  Protege                                   **
********************************************************************************

----------------- Initialising and Starting the OSGi Framework -----------------
FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory

The OSGi framework has been initialised
------------------------------- Starting Bundles -------------------------------
Starting bundle org.protege.common
...
The OSGi framework has been started
------------------------------------ Protege -----------------------------------

Protege Desktop
Version 5.1.0, Build SNAPSHOT


----------------------------------- Platform -----------------------------------
Java: JVM 1.8.0_40-b26  Memory: 506M
Language: en, Country: US
Framework: Apache Software Foundation (1.7)
OS: windows7 (6.1)
Processor: x86


------------------------------------ Plugins -----------------------------------
Plugin: Browser View (OWLDoc) (3.0.3)
Plugin: Explanation Workbench (3.0.0)
Plugin: OntoGraf (2.0.3)
Plugin: Existential Query (2.0.0)
Plugin: SWRLTab Protege 5.0+ Plugin (1.0.3)
Plugin: OWLViz (5.0.3)
Plugin: DL Query (4.0.0)
Plugin: Protege SPARQL Plugin (2.0.1)
Plugin: Cellfie Protege 5.0+ Plugin (2.1.0.SNAPSHOT)
Plugin: OWL Code Generation Plug-in (2.0.0)
Plugin: OWLAPI RDF Library (2.0.2)
Plugin: HermiT (1.3.8.413)
Plugin: HermiT Reasoner (1.3.8)

An error occurred whilst loading the list of recent items: org.protege.editor.core.editorkit.EditorKitDescriptor; local class incompatible: stream classdesc serialVersionUID = 3407968599072820006, local class serialVersionUID = 1
java.io.InvalidClassException: org.protege.editor.core.editorkit.EditorKitDescriptor; local class incompatible: stream classdesc serialVersionUID = 3407968599072820006, local class serialVersionUID = 1
        at java.io.ObjectStreamClass.initNonProxy(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readClassDesc(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[na:1.8.0_40]
        at java.util.ArrayList.readObject(Unknown Source) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectStreamClass.invokeReadObject(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[na:1.8.0_40]
        at org.protege.editor.core.editorkit.RecentEditorKitManager.load(RecentEditorKitManager.java:104) ~[protege-editor-core.jar:na]
        at org.protege.editor.core.ProtegeApplication.loadRecentEditorKits(ProtegeApplication.java:290) [protege-editor-core.jar:na]
        at org.protege.editor.core.ProtegeApplication.initApplication(ProtegeApplication.java:259) [protege-editor-core.jar:na]
        at org.protege.editor.core.ProtegeApplication.reallyStart(ProtegeApplication.java:101) [protege-editor-core.jar:na]
        at org.protege.editor.core.ProtegeApplication.lambda$start$15(ProtegeApplication.java:90) [protege-editor-core.jar:na]
        at org.protege.editor.core.ProtegeApplication$$Lambda$24/5507077.frameworkEvent(Unknown Source) [protege-editor-core.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.invokeFrameworkListenerCallback(EventDispatcher.java:836) [org.apache.felix.main.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:786) [org.apache.felix.main.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.run(EventDispatcher.java:1099) [org.apache.felix.main.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.access$000(EventDispatcher.java:55) [org.apache.felix.main.jar:na]
        at org.apache.felix.framework.util.EventDispatcher$1.run(EventDispatcher.java:102) [org.apache.felix.main.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_40]
Creating and setting up empty (default) editor kit
OWL API Version: 4.2.6.20160910-2108
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/bmir/ontologies/2016/9/untitled-ontology-43
```

The exception may or may not be related to the automatic plugin update mechanism, as they were thrown the very first time I executed `run.bat`, but not at subsequent runs.

**Comment by rsgoncalves** [comment]
I am getting the same error on MacOS.

**Comment by matthewhorridge** [comment]
This is due to the fact that we changed some fields on EditorKitDescriptor and we use Java serialization to save editor kit descriptors.  I've added an id for serialization stability and also changed this from an error logging level to info.
