### ISSUE TITLE
[DL query]: uncaught parser exception when clicking on checkboxes

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#553]
If I enter into DL query tab something not parsable and then click on some check-boxes (e.g., "Direct subclasses", see screenshot), Protege throws a parser exception

![screen shot 2016-10-05 at 12 39 29](https://cloud.githubusercontent.com/assets/2140361/19110242/2bf08f60-8af9-11e6-938c-7668f1d72867.png)

org.protege.editor.owl.model.classexpression.OWLExpressionParserException: Encountered blah at line 1 column 1. Expected one of:
	Class name
	Object property name
	Data property name
	inverse
	not
	(
	{

	at org.protege.editor.owl.model.parser.ParserUtil.convertException(ParserUtil.java:27) ~[na:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassExpressionChecker.createObject(OWLClassExpressionChecker.java:51) ~[protege-editor-owl/:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassExpressionChecker.createObject(OWLClassExpressionChecker.java:1) ~[protege-editor-owl/:na]
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.createObject(ExpressionEditor.java:169) ~[protege-editor-owl/:na]
	at org.coode.dlquery.OWLClassExpressionEditorViewComponent.doQuery(OWLClassExpressionEditorViewComponent.java:242) [org.coode.dlquery-3.0.1.jar:na]
	at org.coode.dlquery.OWLClassExpressionEditorViewComponent.access$200(OWLClassExpressionEditorViewComponent.java:54) [org.coode.dlquery-3.0.1.jar:na]
	at org.coode.dlquery.OWLClassExpressionEditorViewComponent$4.actionPerformed(OWLClassExpressionEditorViewComponent.java:193) [org.coode.dlquery-3.0.1.jar:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [na:1.8.0_77]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [na:1.8.0_77]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.8.0_77]
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308) [na:1.8.0_77]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [na:1.8.0_77]
	at java.awt.Component.processMouseEvent(Component.java:6535) [na:1.8.0_77]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_77]
	at java.awt.Component.processEvent(Component.java:6300) [na:1.8.0_77]
	at java.awt.Container.processEvent(Container.java:2236) [na:1.8.0_77]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) [na:1.8.0_77]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [na:1.8.0_77]
	at java.awt.Component.dispatchEvent(Component.java:4713) [na:1.8.0_77]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [na:1.8.0_77]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [na:1.8.0_77]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [na:1.8.0_77]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [na:1.8.0_77]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_77]
	at java.awt.Component.dispatchEvent(Component.java:4713) [na:1.8.0_77]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [na:1.8.0_77]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_77]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [na:1.8.0_77]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [na:1.8.0_77]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_77]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_77]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_77]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [na:1.8.0_77]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [na:1.8.0_77]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_77]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_77]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_77]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_77]

**Comment by ykazakov** [comment]
Also, if I entered a valid (parsable) query, but do not press "Execute" and instead check one of the flags on the right, the query is still being executed.
I think the query results should be updated only after pressing "Execute" and not when changing the flags.
