### ISSUE TITLE
FaCT++ Kernel: unsupported facet 'getPattern'.

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#556]
Observed in 5.1.0 Snapshot from 20161003, with latest Fact++ plugin (version 1.6.4):
```
------------------------------- Running Reasoner ------------------------------- 
 
An error occurred during reasoning: FaCT++ Kernel: unsupported facet 'getPattern'. 
org.semanticweb.owlapi.reasoner.ReasonerInternalException: FaCT++ Kernel: unsupported facet 'getPattern'
	at uk.ac.manchester.cs.factplusplus.FaCTPlusPlus.getPattern(Native Method) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner$DataRangeTranslator.visit(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner$DataRangeTranslator.visit(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLDatatypeRestrictionImpl.accept(OWLDatatypeRestrictionImpl.java:151) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner.toDataTypeExpressionPointer(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner$ClassExpressionTranslator.visit(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner$ClassExpressionTranslator.visit(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataSomeValuesFromImpl.accept(OWLDataSomeValuesFromImpl.java:92) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner.toClassPointer(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner$AxiomTranslator.visit(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner$AxiomTranslator.visit(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLSubClassOfAxiomImpl.accept(OWLSubClassOfAxiomImpl.java:122) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner.loadAxiom(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner.loadReasonerAxioms(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasoner.<init>(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasonerFactory.createReasoner(Unknown Source) ~[na:na]
	at uk.ac.manchester.cs.factplusplus.owlapiv3.FaCTPlusPlusReasonerFactory.createReasoner(Unknown Source) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
```

Some log messages from an earlier run of Protege, when I installed the latest version of the Fact++ plugin:
```
----------------------- Downloading and Installing Plugin ---------------------- 
Downloading the FaCT++ reasoner plugin (Version 1.6.4) 
Downloading the FaCT++ reasoner plugin from: https://bitbucket.org/dtsarkov/factplusplus/downloads/uk.ac.manchester.cs.owl.factplusplus-P5.0-v1.6.4.jar 
The FaCT++ reasoner plugin has been downloaded to /tmp/uk.ac.manchester.cs.owl.factplusplus4907649033581328456.jar 
Copied the FaCT++ reasoner plugin to uk.ac.manchester.cs.owl.factplusplus-1.6.4.jar in the plugins directory 
Installing the FaCT++ reasoner plugin 
```

**Comment by matthewhorridge** [comment]
This isn't a protege issue, it's just that FaCT++ doesn't implement this part of the OWL spec.  It's possible that the FaCT++ plugin itself could handle unsupported constructs in a different way, but we don't have control of this.

**Comment by csnyulas** [comment]
I know it is a Fact++ issue, but I reported here because I thought this may be related to some changes in Protege. I do not remember getting such error messages in earlier releases.
Basically, when I started testing Protege with a certain ontology, I got these errors from Fact++, and Pellet was not able to run either (see issue #557), so I got concerned that something has changed in Protege that requires some kind of inferences that the reasoners can't provide any more. However with further tests using different ontologies, this issue did not come up with subsequent tests.

The problematic ontology was the one attached to this issue: owlcs/owlapi#562

**Comment by matthewhorridge** [comment]
> I know it is not a Fact++ issue, 

Assuming you meant "is"...

> but I reported here because I thought this may be related to some changes in Protege.

Yes, always best to report things like this.

 I do not remember getting such error messages in earlier releases.

You'd only encounter this particular error if you ontology contained something like this
```
hasName some xsd:String [xsd:pattern "M+"]
```
Perhaps Pellet doesn't support these facets on Strings.

**Comment by csnyulas** [comment]
Yes, yes, yes, I meant "is" a Fact++, later I corrected to "is not" because I thought I am talking about Protege. Sorry, for being confused. I'll revert the issue description back, as it was.
