### ISSUE TITLE
Exceptions thrown when starting Pellet: java.lang.UnsupportedOperationException: null 

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#557]
Observed in 5.1.0 Snapshot from 20161003, with latest Pellet plugin (version 2.2.0):

When I start the reasoner I got this exception (repeating parts of the exceptions have been extracted for better overview, see below)

```
------------------------------- Running Reasoner ------------------------------- 
Pre-computing inferences: 
    - class hierarchy 
    - object property hierarchy 
    - data property hierarchy 
    - class assertions 
    - object property assertions 
    - same individuals 

An error occurred during reasoning: null. 
<UnsupOpException_1>
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.checkSatisfiability(CDOptimizedTaxonomyBuilder.java:763) ~[na:na]
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:814) ~[na:na]
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:265) ~[na:na]
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:217) ~[na:na]
    at org.mindswap.pellet.KnowledgeBase.classify(KnowledgeBase.java:2095) ~[na:na]
    at com.clarkparsia.pellet.owlapiv3.PelletReasoner.precomputeInferences(PelletReasoner.java:1067) ~[na:na]
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.precompute(OWLReasonerManagerImpl.java:447) ~[na:na]
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:388) ~[na:na]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
<UnsupOpException_21>
<UnsupOpException_21>
An error occurred whilst filling the org.protege.editor.owl.ui.frame.cls.OWLSubClassAxiomFrameSection frame with inferred information: {} 
<UnsupOpException_11>
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.lambda$installRunningReasoner$147(OWLReasonerManagerImpl.java:459) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner$$Lambda$264/23026159.run(Unknown Source) [protege-editor-owl.jar:na]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) [na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
<UnsupOpException_22>
<UnsupOpException_22>
An error occurred whilst filling the org.protege.editor.owl.ui.frame.cls.OWLSubClassAxiomFrameSection frame with inferred information: {} 
<UnsupOpException_11>
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl.lambda$fireReclassified$146(OWLReasonerManagerImpl.java:341) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$$Lambda$259/122220048.run(Unknown Source) [protege-editor-owl.jar:na]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) [na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [na:1.8.0_40]
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) [na:1.8.0_40]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) [na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
```

where `UnsupOpException_1` is:

```
java.lang.UnsupportedOperationException: null
    at com.clarkparsia.pellet.datatypes.types.text.RestrictedTextDatatype.applyConstrainingFacet(RestrictedTextDatatype.java:93) ~[na:na]
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.getDataRange(DatatypeReasonerImpl.java:440) ~[na:na]
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.normalizeVarRanges(DatatypeReasonerImpl.java:1049) ~[na:na]
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.isSatisfiable(DatatypeReasonerImpl.java:721) ~[na:na]
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.isSatisfiable(DatatypeReasonerImpl.java:665) ~[na:na]
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.isSatisfiable(DatatypeReasonerImpl.java:626) ~[na:na]
    at org.mindswap.pellet.Literal.checkClash(Literal.java:369) ~[na:na]
    at org.mindswap.pellet.Literal.addType(Literal.java:261) ~[na:na]
    at org.mindswap.pellet.tableau.completion.CompletionStrategy.addType(CompletionStrategy.java:438) ~[na:na]
    at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.applySomeValuesRule(SomeValuesRule.java:180) ~[na:na]
    at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.apply(SomeValuesRule.java:64) ~[na:na]
    at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.expand(EmptySRIQStrategy.java:303) ~[na:na]
    at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.complete(EmptySRIQStrategy.java:162) ~[na:na]
    at org.mindswap.pellet.ABox.isConsistent(ABox.java:1423) ~[na:na]
    at org.mindswap.pellet.ABox.isSatisfiable(ABox.java:595) ~[na:na]
```

`UnsupOpException_11` is:

```
<UnsupOpException_1>
    at org.mindswap.pellet.ABox.isSatisfiable(ABox.java:554) ~[na:na]
    at org.mindswap.pellet.KnowledgeBase.isSatisfiable(KnowledgeBase.java:2714) ~[na:na]
    at com.clarkparsia.pellet.owlapiv3.PelletReasoner.isSatisfiable(PelletReasoner.java:888) ~[na:na]
    at org.protege.editor.owl.ui.frame.cls.OWLSubClassAxiomFrameSection.refillInferred(OWLSubClassAxiomFrameSection.java:65) ~[protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.setRootObject(AbstractOWLFrameSection.java:264) ~[protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.frame.AbstractOWLFrame.refill(AbstractOWLFrame.java:91) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.frame.AbstractOWLFrame.setRootObject(AbstractOWLFrame.java:83) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.framelist.OWLFrameList.setRootObject(OWLFrameList.java:290) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.framelist.OWLFrameList.lambda$new$55(OWLFrameList.java:146) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.ui.framelist.OWLFrameList$$Lambda$148/1758104200.handleChange(Unknown Source) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.model.OWLModelManagerImpl.lambda$fireEvent$224(OWLModelManagerImpl.java:766) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.model.OWLModelManagerImpl$$Lambda$34/368003468.run(Unknown Source) [protege-editor-owl.jar:na]
    at org.protege.editor.owl.model.OWLModelManagerImpl.fireEvent(OWLModelManagerImpl.java:774) [protege-editor-owl.jar:na]
```

`UnsupOpException_2` is:

```
java.lang.UnsupportedOperationException
    at com.clarkparsia.pellet.datatypes.types.text.RestrictedTextDatatype.applyConstrainingFacet(RestrictedTextDatatype.java:93)
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.getDataRange(DatatypeReasonerImpl.java:440)
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.normalizeVarRanges(DatatypeReasonerImpl.java:1049)
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.isSatisfiable(DatatypeReasonerImpl.java:721)
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.isSatisfiable(DatatypeReasonerImpl.java:665)
    at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.isSatisfiable(DatatypeReasonerImpl.java:626)
    at org.mindswap.pellet.Literal.checkClash(Literal.java:369)
    at org.mindswap.pellet.Literal.addType(Literal.java:261)
    at org.mindswap.pellet.tableau.completion.CompletionStrategy.addType(CompletionStrategy.java:438)
    at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.applySomeValuesRule(SomeValuesRule.java:180)
    at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.apply(SomeValuesRule.java:64)
    at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.expand(EmptySRIQStrategy.java:303)
    at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.complete(EmptySRIQStrategy.java:162)
    at org.mindswap.pellet.ABox.isConsistent(ABox.java:1423)
    at org.mindswap.pellet.ABox.isSatisfiable(ABox.java:595)
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.checkSatisfiability(CDOptimizedTaxonomyBuilder.java:763)
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:814)
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:265)
    at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:217)
    at org.mindswap.pellet.KnowledgeBase.classify(KnowledgeBase.java:2095)
    at org.mindswap.pellet.KnowledgeBase.getAllEquivalentClasses(KnowledgeBase.java:3525)
    at com.clarkparsia.pellet.owlapiv3.PelletReasoner.getEquivalentClasses(PelletReasoner.java:514)
    at org.protege.editor.owl.model.hierarchy.cls.InferredOWLClassHierarchyProvider.getEquivalents(InferredOWLClassHierarchyProvider.java:170)
    at org.protege.editor.owl.model.hierarchy.cls.InferredOWLClassHierarchyProvider.getEquivalents(InferredOWLClassHierarchyProvider.java:27)
    at org.protege.editor.owl.ui.tree.OWLObjectTree.createTreeNode(OWLObjectTree.java:459)
    at org.protege.editor.owl.ui.tree.OWLObjectTreeRootNode.loadChildrenIfNecessary(OWLObjectTreeRootNode.java:52)
    at org.protege.editor.owl.ui.tree.OWLObjectTreeNode.getChildCount(OWLObjectTreeNode.java:104)
    at org.protege.editor.owl.ui.tree.OWLObjectTreeNode.isLeaf(OWLObjectTreeNode.java:126)
    at javax.swing.tree.DefaultTreeModel.isLeaf(DefaultTreeModel.java:203)
    at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2808)
    at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360)
    at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:738)
    at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
    at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
    at javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:365)
    at javax.swing.tree.DefaultTreeModel.setRoot(DefaultTreeModel.java:135)
    at org.protege.editor.owl.ui.tree.OWLObjectTree.reload(OWLObjectTree.java:333)
    at org.protege.editor.owl.ui.tree.OWLModelManagerTree.reload(OWLModelManagerTree.java:64)
    at org.protege.editor.owl.ui.tree.OWLObjectTree$1.hierarchyChanged(OWLObjectTree.java:100)
    at org.protege.editor.owl.model.hierarchy.AbstractOWLObjectHierarchyProvider.fireHierarchyChanged(AbstractOWLObjectHierarchyProvider.java:258)
    at org.protege.editor.owl.model.hierarchy.cls.InferredOWLClassHierarchyProvider.lambda$new$191(InferredOWLClassHierarchyProvider.java:44)
    at org.protege.editor.owl.model.hierarchy.cls.InferredOWLClassHierarchyProvider$$Lambda$130/1741746580.handleChange(Unknown Source)
    at org.protege.editor.owl.model.OWLModelManagerImpl.lambda$fireEvent$224(OWLModelManagerImpl.java:766)
    at org.protege.editor.owl.model.OWLModelManagerImpl$$Lambda$34/368003468.run(Unknown Source)
    at org.protege.editor.owl.model.OWLModelManagerImpl.fireEvent(OWLModelManagerImpl.java:774)
```

`UnsupOpException_21` is:

```
<UnsupOpException_2>
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.lambda$installRunningReasoner$147(OWLReasonerManagerImpl.java:459)
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner$$Lambda$264/23026159.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

and `UnsupOpException_22` is:

```
<UnsupOpException_2>
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl.lambda$fireReclassified$146(OWLReasonerManagerImpl.java:341)
    at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$$Lambda$259/122220048.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by csnyulas** [comment]
May be related to #541

**Comment by matthewhorridge** [comment]
My guess is that it's not related to #541.  
I think the clue is here: ```RestrictedTextDatatype.applyConstrainingFacet(RestrictedTextDatatype.java:93)```
What constructs do you have in the ontology with regards to datatypes?

**Comment by csnyulas** [comment]
The problematic ontology was the one attached to this issue: owlcs/owlapi#562

**Comment by matthewhorridge** [comment]
Thanks, 

The "problem" lines are here:

```xml
<owl:Class rdf:about="http://www.semanticweb.org/ontologies/research/mid-review#LargeText">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/ontologies/research/mid-review#Text"/>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.semanticweb.org/ontologies/research/mid-review#hasPreferredFontFamily"/>
                <owl:someValuesFrom>
                    <rdfs:Datatype>
                        <owl:onDatatype rdf:resource="&xsd;string"/>
                        <owl:withRestrictions rdf:parseType="Collection">
                            <rdf:Description>
                                <xsd:pattern rdf:datatype="&xsd;string">serif</xsd:pattern>
                            </rdf:Description>
                        </owl:withRestrictions>
                    </rdfs:Datatype>
                </owl:someValuesFrom>
            </owl:Restriction>
        </rdfs:subClassOf>
    </owl:Class>
```

FaCT++ doesn't support the pattern facet for datatypes.  This could be replaced in this case with a hasValue restriction e.g. hasPreferredFontFamily value "serif" (or don't use strings to represent font families).

**Comment by csnyulas** [comment]
You mean "Pellet", right (as this issue is about the Pellet exceptions)?
The explanation as you worded it fits to #556.

**Comment by matthewhorridge** [comment]
Ah right, yes.

**Comment by vymiyai** [comment]
Are there any news related to the lack of support for string facets like pattern and length in Pellet?

**Comment by csnyulas** [comment]
I think this should be a question for the Pellet developers:
https://github.com/stardog-union/pellet

**Comment by matthewhorridge** [comment]
Closing this as I expect that it will never be fixed
