### ISSUE TITLE
Missing maven-artifact.jar from the run.bat classpath in Windows distro

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#567]
The maven-artifact.jar is not part of classpath in run.bat in the Windows distro for Protege 5.1.0. (it is part of the platform independent one). This causes problems to some people when trying to start Protege 5.1.0. It seems to happen mainly on Windows 7. Works fine on Windows 10.

Error:

```
C:\Program Files\Protégé\Protege-5.1.0>run.bat

C:\Program Files\Protégé\Protege-5.1.0>setlocal

C:\Program Files\Protégé\Protege-5.1.0>cd /d C:\Program
Files\Protégé\Protege-5.1.0\

C:\Program Files\Protégé\Protege-5.1.0>jre\bin\java -Xmx500M -Xms200M
-Xss16M -X
X:CompileCommand=exclude,javax/swing/text/GlyphView,getBreakSpot
-DentityExpansi
onLimit=100000000 -Dlogback.configurationFile=conf/logback-win.xml
-Dfile.encodi
ng=utf-8 -Dorg.protege.plugin.dir=plugins -classpath
bundles/guava.jar;bundles/l
ogback-classic.jar;bundles/logback-core.jar;bundles/slf4j-api.jar;bin/org.apache
.felix.main.jar;bin/protege-launcher.jar org.protege.osgi.framework.Launcher
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
********************************************************************************

**                                  Protege                                  
**

********************************************************************************


----------------- Initialising and Starting the OSGi Framework
-----------------

FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory

The OSGi framework has been initialised
Exception in thread "main" java.lang.NoClassDefFoundError:
org/apache/maven/artifact/versioning/ComparableVersion
        at
org.protege.osgi.framework.BundleInfo.compareByVersion(BundleInfo.java:66)
        at
org.protege.osgi.framework.BundleInfo.isNewerVersionThan(BundleInfo.java:90)
        at
org.protege.osgi.framework.BundleSearchPath.addJar(BundleSearchPath.java:93)
        at
org.protege.osgi.framework.BundleSearchPath.search(BundleSearchPath.java:72)
        at
org.protege.osgi.framework.Launcher.installBundles(Launcher.java:160)

        at org.protege.osgi.framework.Launcher.start(Launcher.java:112)
        at org.protege.osgi.framework.Launcher.main(Launcher.java:245)
Caused by: java.lang.ClassNotFoundException:
org.apache.maven.artifact.versioning.ComparableVersion
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

**Comment by hongcui** [comment]
It is a problem on my Windows 10. I added maven to the classpath and run.bat works, but not Protege.exe. I downloaded the windows version 5.1.0 today.

**Comment by jmkeil** [comment]
The fix for `run.bat` in version 5.1.0 works, but `Protege.exe` is still broken.

**Comment by antoan** [comment]
I get the same isue on Ubuntu 14.04 LTS 64 bit? Is there a workaround?

 ~ protege
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
******************************************************************************** 
**                                  Protege                                   ** 
******************************************************************************** 
 
----------------- Initialising and Starting the OSGi Framework ----------------- 
FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory 
 
The OSGi framework has been initialised 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/maven/artifact/versioning/ComparableVersion
	at org.protege.osgi.framework.BundleInfo.compareByVersion(BundleInfo.java:66)
	at org.protege.osgi.framework.BundleInfo.isNewerVersionThan(BundleInfo.java:90)
	at org.protege.osgi.framework.BundleSearchPath.addJar(BundleSearchPath.java:93)
	at org.protege.osgi.framework.BundleSearchPath.search(BundleSearchPath.java:72)
	at org.protege.osgi.framework.Launcher.installBundles(Launcher.java:160)
	at org.protege.osgi.framework.Launcher.start(Launcher.java:112)
	at org.protege.osgi.framework.Launcher.main(Launcher.java:245)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.artifact.versioning.ComparableVersion
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
