### ISSUE TITLE
protege 5.1.0 hangs during file operation on Mac OS X 10.12

### ISSUE THREAD

**Issue by mys721tx** [protegeproject/protege#619]
protege 5.1.0 hangs during file operation in Mac OS X 10.12.

Step to reproduce:
1. Open protege.
2. Save the current ontology; or, open a saved ontology file.

The crash log can [be found here](https://gist.github.com/mys721tx/907c48a23151895dddd05b7f12c38819).

**Comment by csnyulas** [comment]
These steps are not enough to reproduce the bug. As you can imagine, we and thousands of Protege users have done these two simple steps over and over again, and we did not experience this. It must be something specific to your ontology, file permissions, system setup, etc, that causes this misbehavior for you.

We need more information that would allow us to reproduce this behavior on OUR machines as well.

Here are some questions to consider:
- Have you tried opening the same ontology on a different machine?
- Do you get anything interesting in the log?
- Can you send us a recording, or a more detailed description, of what you experience when Protege is hanging? Does it ever recover? 
- How much memory have you allocated to Protege?

**Comment by mys721tx** [comment]
1. protege on my Windows 10 virtual machine opens [pizza.owl](http://protege.stanford.edu/ontologies/pizza/pizza.owl) without any problem.
2. [`Cannot generate ontology catalog for ontology at...`](https://gist.github.com/mys721tx/9a8eb141560c749777c0121e68b2d964)
3. protege hangs after saving an empty ontology. It does not recover.
3. 1. Open protege
3. 2. Save the untitled ontology without any changes.
4. 3817M

**Comment by csnyulas** [comment]
Also, are you by any chance trying to save your ontology in OBO format? I just got a heads-up that there is a known bug in OWLAPI that causes Protege (which uses OWLAPI) to hang when trying to save ontologies containing certain type of axioms in OBO format.

**Comment by mys721tx** [comment]
No, I was saving it to OWL/XML format.

**Comment by csnyulas** [comment]
Do you have write access to the folder where your ontology is loaded from. The `Cannot generate ontology catalog for ontology at...` message suggest that you may not have. I don't know how Protege would react on MacOS in such cases, but I know that in Linux it would pop up an error message.

Also, I am not sure how you experience the hanging. The fact that the "Saving ontology..." progress bar is not disappearing was reported already a few times in #576 and #574 in the past, and it is just a user interface problem (i.e. in fact, Protege does not hang), and the fix for it will be available in the next release.

**Comment by mys721tx** [comment]
Yes, I have the write permission as the ontologies are located under my home directory.

The progress bar does not appear during saving or loading.

**Comment by csnyulas** [comment]
Can you make a short recording of the problem? From the info you gave us, I still can't imagine, how you experience the hanging. I don't know what else to propose.

**Comment by mys721tx** [comment]
[a recording for the problem](https://youtu.be/GTD4ypEVezA).

**Comment by csnyulas** [comment]
Thank you very much for sending us this recording. It is very helpful!

We just repeated the same steps on one of our machine, but for us the ontology saved just fine, and Protege continued to be responsive. It is quite strange.

We will soon create another build of Protege, which will contain several bug fixes and improvements, and it would be good if you could try out that build on your machine, to see if you still get this issue. We have a hope that some of the fixes to previously reported bugs, will actually resolve also the problem that you experience.

**Comment by mys721tx** [comment]
Thanks!

I built pretoge from 2566dab following the wiki instruction. However, the hang problem still occurs.

**Comment by johardi** [comment]
Hi @mys721tx we could reproduce the error now and we are investigating the problem.
For now, try not to save the ontology into your home directory but instead create a subdirectory and save/open it there.

**Comment by tudorache** [comment]
The problem seems to be caused by the parsing of all directories and files in the home folder in order to create the ontology catalog (known problem). The workaround is to save in a subfolder of the home directory. 

Name: AWT-EventQueue-0
State: RUNNABLE
Total blocked: 324  Total waited: 929

```
Stack trace: 
java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
java.io.File.isFile(File.java:882)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:230)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:237)
org.protege.editor.owl.model.library.folder.FolderGroupManager.update(FolderGroupManager.java:117)
org.protege.editor.owl.model.library.folder.FolderGroupManager.initializeCatalog(FolderGroupManager.java:134)
org.protege.editor.owl.model.library.OntologyCatalogManager.ensureCatalogExists(OntologyCatalogManager.java:124)
org.protege.editor.owl.model.OWLModelManagerImpl.ensureCatalogFileExists(OWLModelManagerImpl.java:500)
org.protege.editor.owl.model.OWLModelManagerImpl.save(OWLModelManagerImpl.java:482)
org.protege.editor.owl.OWLEditorKit.handleSaveAs(OWLEditorKit.java:360)
org.protege.editor.owl.OWLEditorKit.handleSaveAs(OWLEditorKit.java:316)
org.protege.editor.core.ProtegeManager.saveEditorKitAs(ProtegeManager.java:324)
org.protege.editor.core.ui.action.SaveAsAction.actionPerformed(SaveAsAction.java:24)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.AbstractButton.doClick(AbstractButton.java:376)
com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
java.awt.MenuItem.processActionEvent(MenuItem.java:669)
java.awt.MenuItem.processEvent(MenuItem.java:628)
java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:754)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:702)
java.awt.EventQueue$3.run(EventQueue.java:696)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
java.awt.EventQueue$4.run(EventQueue.java:724)
java.awt.EventQueue$4.run(EventQueue.java:722)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mys721tx** [comment]
@johardi confirmed! I can load and save ontologies in subdirectories without any problem.

**Comment by chamberlain93** [comment]
it is ok! just do it! @johardi

**Comment by nslinco** [comment]
This just happened to me too! It happens anytime I save/load from the Downloads file. It works from any other file, though.

**Comment by hubte1g** [comment]
@tudorache This was tremendously helpful - Thank you!

**Comment by matthewhorridge** [comment]
Needs double checking when saving as some things were put in place to try to prevent this.

**Comment by matthewhorridge** [comment]
5.5.0-beta-8 still exhibits this behaviour.

**Comment by DanielBakas** [comment]
### Problem still present for version 5.5.0

Here is my log file:

`   INFO  23:38:13  ------------------------ Saving Workspace and Ontologies -----------------------
   INFO  23:38:13  Will prompt 'Save As' for the active ontology because it was not loaded from a local file
   INFO  23:38:13  Will prompt 'Save As' for the class ontology because it was not loaded from a local file but has been modified
   INFO  23:38:20  Saving class
   INFO  23:38:20  Saving ontology to temp file: /var/folders/9b/454rtm0976n68mf3n7jhtl900000gn/T/temp-ontology2933449547752795224
   INFO  23:38:20  Copying ontology from temp file (/var/folders/9b/454rtm0976n68mf3n7jhtl900000gn/T/temp-ontology2933449547752795224) to actual destination (/Users/danielbakas/test/Test.owl)
   INFO  23:38:20  Removing temp file: /var/folders/9b/454rtm0976n68mf3n7jhtl900000gn/T/temp-ontology2933449547752795224
   INFO  23:38:20  Saved ontology OntologyID(OntologyIRI(<http://archive.semantyk.com/class/>) VersionIRI(<null>)) to file:/Users/danielbakas/test/Test.owl in Turtle Syntax format
   INFO  23:38:21  [GitRepo] Git repository detected: /Users/danielbakas/.git
   INFO  23:38:21  [GitRepo] On branch: master
   WARN  23:39:48  Exception thrown by listener: org.protege.editor.owl.model.git.GitRepoStatusPresenter$$Lambda$87/677136608.  Detatching bad listener.
   INFO  23:39:48  Saved tab state for 'Individual Hierarchy Tab' tab
   INFO  23:39:48  Saved tab state for 'Entities' tab
   INFO  23:39:48  Saved tab state for 'Individuals by class' tab
   INFO  23:39:48  Saved tab state for 'DL Query' tab
   INFO  23:39:48  Saved tab state for 'Active ontology' tab
   INFO  23:39:48  Saved workspace
   INFO  23:39:48  
   INFO  23:39:48  [GitRepo] Git repository detected: /Users/danielbakas/.git
   INFO  23:39:48  [GitRepo] On branch: master
  ERROR  23:42:15  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at sun.nio.fs.UnixPath.encode(UnixPath.java:132) ~[na:1.8.0_121]
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71) ~[na:1.8.0_121]
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281) ~[na:1.8.0_121]
	at java.io.File.toPath(File.java:2234) ~[na:1.8.0_121]
	at org.eclipse.jgit.util.FileUtils.getFileAttributesPosix(FileUtils.java:772) ~[na:na]
	at org.eclipse.jgit.util.FS_POSIX.getAttributes(FS_POSIX.java:270) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator$FileEntry.<init>(FileTreeIterator.java:365) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator.entries(FileTreeIterator.java:242) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:227) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator.createSubtreeIterator(FileTreeIterator.java:233) ~[na:na]
	at org.eclipse.jgit.treewalk.AbstractTreeIterator.createSubtreeIterator(AbstractTreeIterator.java:572) ~[na:na]
	at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:1271) ~[na:na]
	at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:835) ~[na:na]
	at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:440) ~[na:na]
	at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:380) ~[na:na]
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:149) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepositoryManager.getModifiedOntologyDocumentPaths(GitRepositoryManager.java:168) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepositoryManager.isAnyOntologyDocumentModified(GitRepositoryManager.java:153) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepoStatusPresenter.updateStatusView(GitRepoStatusPresenter.java:76) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepoStatusPresenter.update(GitRepoStatusPresenter.java:63) ~[na:na]
	at org.protege.editor.owl.model.OWLWorkspace.handleActivated(OWLWorkspace.java:248) ~[na:na]
	at org.protege.editor.core.ui.workspace.WorkspaceFrame$1.windowActivated(WorkspaceFrame.java:71) ~[na:na]
	at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
	at java.awt.Window.processWindowEvent(Window.java:2066) ~[na:1.8.0_121]
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305) ~[na:1.8.0_121]
	at java.awt.Window.processEvent(Window.java:2013) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
   INFO  23:44:32  [GitRepo] Git repository detected: /Users/danielbakas/.git
   INFO  23:44:32  [GitRepo] On branch: master
  ERROR  23:46:23  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3236) ~[na:1.8.0_121]
	at sun.nio.fs.UnixPath.encode(UnixPath.java:154) ~[na:1.8.0_121]
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71) ~[na:1.8.0_121]
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281) ~[na:1.8.0_121]
	at java.io.File.toPath(File.java:2234) ~[na:1.8.0_121]
	at org.eclipse.jgit.util.FileUtils.getFileAttributesPosix(FileUtils.java:772) ~[na:na]
	at org.eclipse.jgit.util.FS_POSIX.getAttributes(FS_POSIX.java:270) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator$FileEntry.<init>(FileTreeIterator.java:365) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator.entries(FileTreeIterator.java:242) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:227) ~[na:na]
	at org.eclipse.jgit.treewalk.FileTreeIterator.createSubtreeIterator(FileTreeIterator.java:233) ~[na:na]
	at org.eclipse.jgit.treewalk.AbstractTreeIterator.createSubtreeIterator(AbstractTreeIterator.java:572) ~[na:na]
	at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:1271) ~[na:na]
	at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:835) ~[na:na]
	at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:440) ~[na:na]
	at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:380) ~[na:na]
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:149) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepositoryManager.getModifiedOntologyDocumentPaths(GitRepositoryManager.java:168) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepositoryManager.isAnyOntologyDocumentModified(GitRepositoryManager.java:153) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepoStatusPresenter.updateStatusView(GitRepoStatusPresenter.java:76) ~[na:na]
	at org.protege.editor.owl.model.git.GitRepoStatusPresenter.update(GitRepoStatusPresenter.java:63) ~[na:na]
	at org.protege.editor.owl.model.OWLWorkspace.handleActivated(OWLWorkspace.java:248) ~[na:na]
	at org.protege.editor.core.ui.workspace.WorkspaceFrame$1.windowActivated(WorkspaceFrame.java:71) ~[na:na]
	at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389) ~[na:1.8.0_121]
	at java.awt.Window.processWindowEvent(Window.java:2066) ~[na:1.8.0_121]
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305) ~[na:1.8.0_121]
	at java.awt.Window.processEvent(Window.java:2013) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
`

**Comment by manojmsrit** [comment]
Still this problem exists. Any possible solution around this issue ? Please let me know

**Comment by lauramiron** [comment]
I experienced a similar problem, and the problem was that the .owl file was within a very large git repository. Removing the .owl file from the repository resolved the issue.

**Comment by abdulzeedo** [comment]
> I experienced a similar problem, and the problem was that the .owl file was within a very large git repository. Removing the .owl file from the repository resolved the issue.

I just found out that my project was always in a git repository and removing it from it solves the issue as mentioned by @lauramiron . In my case, my VM had a .git in the root folder... 😣
