### ISSUE TITLE
SWRLTab 2.0.0 StackOverflowError with Protege 5.2.0

### ISSUE THREAD

**Issue by daniel86** [protegeproject/protege#639]
Not sure if this is the right place reporting plugin bugs....

Protege 5.2.0 was shipped with SWRLTab 1.2 or so and it was working.
Just updated to SWRLTab 2.0.0 and now I can't use the widget anymore.
When I press the SWRLTab button some unhandled Java exception is thrown.

```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.StackOverflowError: null
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryRenderer.visit(DefaultSWRLRuleAndQueryRenderer.java:356) ~[na:na]
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryRenderer.visit(DefaultSWRLRuleAndQueryRenderer.java:357) ~[na:na]
        ...................
	at  org.swrlapi.factory.DefaultSWRLRuleAndQueryRenderer.visit(DefaultSWRLRuleAndQueryRenderer.java:357) ~[na:na]
```

Same happens for ROWLTab.

Here is the log copied from Protege log display dialog:
```
Level:       INFO
Time:        1492692823002
Message:     ------------------------------------ Protege -----------------------------------

Level:       INFO
Time:        1492692823005
Message:     Protege Desktop

Level:       INFO
Time:        1492692823005
Message:     Version 5.2.0, Build 

Level:       INFO
Time:        1492692823006
Message:     

Level:       INFO
Time:        1492692823006
Message:     

Level:       INFO
Time:        1492692823006
Message:     ----------------------------------- Platform -----------------------------------

Level:       INFO
Time:        1492692823006
Message:     Java: JVM 1.8.0_40-b26  Memory: 466M

Level:       INFO
Time:        1492692823006
Message:     Language: de, Country: DE

Level:       INFO
Time:        1492692823007
Message:     Framework: Apache Software Foundation (1.7) 

Level:       INFO
Time:        1492692823007
Message:     OS: linux (4.4.0-45-generic)

Level:       INFO
Time:        1492692823007
Message:     Processor: x86-64


Level:       INFO
Time:        1492692823007
Message:     

Level:       INFO
Time:        1492692823007
Message:     ------------------------------------ Plugins -----------------------------------

Level:       INFO
Time:        1492692823007
Message:     Plugin: DL Query (4.0.1)

Level:       INFO
Time:        1492692823007
Message:     Plugin: ROWL Protege 5.0+ Plugin (1.6.0)

Level:       INFO
Time:        1492692823007
Message:     Plugin: Cellfie Protege 5.0+ Plugin (2.1.0)

Level:       INFO
Time:        1492692823007
Message:     Plugin: SPARQL Query Plugin (2.0.2)

Level:       INFO
Time:        1492692823007
Message:     Plugin: OWLViz (5.0.3)

Level:       INFO
Time:        1492692823008
Message:     Plugin: SWRLTab Protege 5.0+ Plugin (2.0.0)

Level:       INFO
Time:        1492692823008
Message:     Plugin: OWLAPI RDF Library (2.0.3)

Level:       INFO
Time:        1492692823008
Message:     Plugin: Existential Query (2.0.0)

Level:       INFO
Time:        1492692823008
Message:     Plugin: HermiT (1.3.8.413)

Level:       INFO
Time:        1492692823008
Message:     Plugin: OWL Code Generation Plug-in (2.0.0)

Level:       INFO
Time:        1492692823008
Message:     Plugin: OntoGraf (2.0.3)

Level:       INFO
Time:        1492692823008
Message:     Plugin: Browser View (OWLDoc) (3.0.3)

Level:       INFO
Time:        1492692823008
Message:     Plugin: Explanation Workbench (3.0.0)

Level:       INFO
Time:        1492692823008
Message:     

Level:       INFO
Time:        1492692823404
Message:     Creating and setting up empty (default) editor kit

Level:       INFO
Time:        1492692823407
Message:     OWL API Version: 4.2.8.20170104-2310

Level:       WARN
Time:        1492692823858
Message:     Cannot generate ontology catalog for ontology at http://www.semanticweb.org/danielb/ontologies/2017/3/untitled-ontology-13

Level:       INFO
Time:        1492692824104
Message:     ------------------------------- Auto-update Check ------------------------------

Level:       INFO
Time:        1492692824106
Message:     Auto-update is disabled

Level:       INFO
Time:        1492692824106
Message:     

Level:       INFO
Time:        1492692830650
Message:     OWL API Version: 4.2.8.20170104-2310

Level:       INFO
Time:        1492692830702
Message:     ------------------------------- Loading Ontology -------------------------------

Level:       INFO
Time:        1492692830702
Message:     Loading ontology from file:/home/danielb/thinkpad/coding/knowrob.daniel/src/knowrob/knowrob_common/owl/swrl_test.owl

Level:       INFO
Time:        1492692830844
Message:     Finished loading file:/home/danielb/thinkpad/coding/knowrob.daniel/src/knowrob/knowrob_common/owl/swrl_test.owl

Level:       INFO
Time:        1492692830868
Message:     Loading for ontology and imports closure successfully completed in 166 ms

Level:       INFO
Time:        1492692830869
Message:     
```

**Comment by martinjoconnor** [comment]
Works fine for me. Do you have a particular ontology that demonstrates the failure?

**Comment by daniel86** [comment]
I pasted the ontology [here](https://pastebin.ca/3815147), it was created using the rules ontology view.

I tried to type in these rules in the SWRLTab but it seems that some OWL features are not supported (e.g., unionOf, complementOf, ...). Is it because common reasoner don't support it?
Using just the subset that was accepted by SWRLTab everything works fine.

**Comment by martinjoconnor** [comment]
Thanks for the ontology. It looks like this ontology is generating an infinite loop in the SWRLAPI code.

I will take a look at it.

Martin

**Comment by matthewhorridge** [comment]
Moving this to the SWRL Tab Plugin Issue Tracker
