### ISSUE TITLE
Error in Protege 5.2.1 starting up with Eclipse and Maven under Java 8 (in Linux) 

### ISSUE THREAD

**Issue by dpaleti** [protegeproject/protege#652]
Trying to Set up protege 5.2.1 in linux environment. Followed steps from the link https://github.com/protegeproject/protege/wiki/Setup-in-Eclipse

Maven Build is successful. OSGi framework started but error in org.apache.felix.main.jar file. Please see the error details below. Can some body please advise ?

Error starting file:/home/user/protege/protege-desktop/target/protege-5.2.1-SNAPSHOT-platform-independent/Protege-5.2.1-SNAPSHOT/bundles/protege-editor-core.jar 

org.osgi.framework.BundleException: Activator start error in bundle org.protege.editor.core.application [4].
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2204) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2072) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304) [org.apache.felix.main.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
Caused by: java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_102]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_102]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_102]
	at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:4362) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2149) ~[org.apache.felix.main.jar:na]
	... 4 common frames omitted
Caused by: java.awt.HeadlessException: null
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[na:1.8.0_102]
	at java.awt.Window.<init>(Window.java:536) ~[na:1.8.0_102]
	at java.awt.Frame.<init>(Frame.java:420) ~[na:1.8.0_102]
	at java.awt.Frame.<init>(Frame.java:385) ~[na:1.8.0_102]
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758) ~[na:1.8.0_102]
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1833) ~[na:1.8.0_102]
	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696) ~[na:1.8.0_102]
	at javax.swing.JOptionPane.getWindowForComponent(JOptionPane.java:1637) ~[na:1.8.0_102]
	at javax.swing.JOptionPane.createDialog(JOptionPane.java:956) ~[na:1.8.0_102]
	at javax.swing.JOptionPane.createDialog(JOptionPane.java:918) ~[na:1.8.0_102]
	at org.protege.editor.core.log.LogManager.<init>(LogManager.java:44) ~[na:na]
	at org.protege.editor.core.ProtegeApplication.<clinit>(ProtegeApplication.java:82) ~[na:na]
	... 11 common frames omitted
The OSGi framework has been started

**Comment by ykazakov** [comment]
`Caused by: java.awt.HeadlessException: null`
do you try to run Protege headless (without the X server)?

Do you obtain this error from eclipse, or also when you start from the command line?
What happens if you run this:
`protege-desktop/target/protege-5.2.1-SNAPSHOT-platform-independent/Protege-5.2.1-SNAPSHOT/run.sh`

**Comment by dpaleti** [comment]
Thanks for the quick response @ykazakov  Yes, I get the same error when i run from Eclipse as well run the script run.sh from command prompt

**Comment by ykazakov** [comment]
Which version of Linux?
Can you run the [prebuilt version](http://protege.stanford.edu/products.php)?

**Comment by ykazakov** [comment]
Please then remove Eclipse from the title and add your version of Linux.

**Comment by dpaleti** [comment]
@ykazakov I am using CentOS. I actually had to reinstall Java 8(same version before) and it works now but still wondering what would have changed.

**Comment by ykazakov** [comment]
Possibly you have originally installed a headless java. See, e.g, [here](http://stackoverflow.com/questions/5362512/unable-to-run-java-gui-programs-with-ubuntu) or [here](http://stackoverflow.com/questions/5241850/running-java-gui-application-through-linux-terminal). But now we will not find out.

**Comment by dpaleti** [comment]
Actually i ran same exact version of Java again. But will keep in mind about headless java next time. Thanks @ykazakov
