### ISSUE TITLE
After loading ontology SPARQL query tab does not work

### ISSUE THREAD

**Issue by jgrzebyta** [protegeproject/protege#662]
Protege affected version: **5.2.0**

The **SPARQL query** tab content is not displayed properly.
I have the symptoms only when I try to open SPARQL tab after loading an ontology. The error does not occur when no ontology is loaded.

Stack trace from the thread:
```
2017-06-21 14:18:52.556 [AWT-EventQueue-0] INFO  OWLEditorKit    ---------------------------- Disposing of Workspace ----------------------------
2017-06-21 14:18:52.568 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'Entities' tab
2017-06-21 14:18:52.570 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'Classes' tab
2017-06-21 14:18:52.572 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'Annotation Properties' tab
2017-06-21 14:18:52.574 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'DL Query' tab
2017-06-21 14:18:52.574 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'SPARQL Query' tab
2017-06-21 14:18:52.576 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'Object Properties' tab
2017-06-21 14:18:52.577 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'Individuals by class' tab
2017-06-21 14:18:52.579 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'Active Ontology' tab
2017-06-21 14:18:52.582 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved tab state for 'Data Properties' tab
2017-06-21 14:18:52.587 [AWT-EventQueue-0] INFO  TabbedWorkspace    Saved workspace
2017-06-21 14:18:52.588 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'Entities' tab
2017-06-21 14:18:52.596 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'Classes' tab
2017-06-21 14:18:52.596 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'Annotation Properties' tab
2017-06-21 14:18:52.598 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'DL Query' tab
2017-06-21 14:18:52.603 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'SPARQL Query' tab
2017-06-21 14:18:52.606 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'Object Properties' tab
2017-06-21 14:18:52.616 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'Individuals by class' tab
2017-06-21 14:18:52.617 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'Active Ontology' tab
2017-06-21 14:18:52.629 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'Data Properties' tab
2017-06-21 14:18:52.634 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of workspace
2017-06-21 14:18:52.636 [AWT-EventQueue-0] INFO  OWLEditorKit    
2017-06-21 14:19:00.695 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoSuchMethodError: org.semanticweb.owlapi.rdf.model.AbstractTranslator.<init>(Lorg/semanticweb/owlapi/model/OWLOntologyManager;Lorg/semanticweb/owlapi/model/OWLOntology;ZLorg/semanticweb/owlapi/util/IndividualAppearance;Lorg/semanticweb/owlapi/util/AxiomAppearance;Ljava/util/concurrent/atomic/AtomicInteger;)V
	at org.protege.owl.rdf.impl.RDFTranslator.<init>(RDFTranslator.java:93) ~[na:na]
	at org.protege.owl.rdf.impl.RDFTranslator.translate(RDFTranslator.java:55) ~[na:na]
	at org.protege.owl.rdf.impl.OwlTripleStoreImpl.addAxiom(OwlTripleStoreImpl.java:99) ~[na:na]
	at org.protege.owl.rdf.Utilities.loadOwlTripleStore(Utilities.java:48) ~[na:na]
	at org.protege.owl.rdf.Utilities.getOwlTripleStore(Utilities.java:32) ~[na:na]
	at org.protege.editor.owl.rdf.repository.BasicSparqlReasoner.precalculate(BasicSparqlReasoner.java:54) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initializeReasoner(SparqlQueryView.java:36) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initialiseOWLView(SparqlQueryView.java:26) ~[na:na]
	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
	at org.protege.editor.core.ui.view.View.createContent(View.java:424) ~[na:na]
	at org.protege.editor.core.ui.view.View.createUI(View.java:217) ~[na:na]
	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123) ~[na:na]
	at java.awt.Component.processHierarchyEvent(Component.java:6692) ~[na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6311) ~[na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.Component.createHierarchyEvents(Component.java:5541) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1443) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Component.show(Component.java:1622) ~[na:1.8.0_40]
	at java.awt.Component.show(Component.java:1654) ~[na:1.8.0_40]
	at java.awt.Component.setVisible(Component.java:1606) ~[na:1.8.0_40]
	at javax.swing.JComponent.setVisible(JComponent.java:2644) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) ~[na:1.8.0_40]
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) ~[na:1.8.0_40]
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) ~[na:1.8.0_40]
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) ~[na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) ~[na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) ~[na:1.8.0_40]
	at java.awt.Component.processMouseEvent(Component.java:6522) ~[na:1.8.0_40]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6290) ~[na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2278) ~[na:1.8.0_40]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) ~[na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:724) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) ~[na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
```

**Comment by csnyulas** [comment]
It works for me. The problem may be a dependency between **SPARQL Query Plugin** and the **OWLAPI RDF Library**. Please make sure that you have the latest version from both:
- version **2.0.2** of the  **SPARQL Query Plugin**, and 
- version **2.0.3** of the **OWLAPI RDF Library**

You can see currently installed versions of these plugin through the `Help -> About` menu.

You can install new (versions of) plug-ins using the `File -> Chefor plugins....` menu.

If this does not solve your problem please send us the ontology, so that we can take a look at it.

**Comment by jgrzebyta** [comment]
Plugins update fixed the issue.

**Comment by ying6991** [comment]
I  have checked both versions SPARQL Query Plugin and the OWLAPI RDF Library that are the latest versions, but  it still doesnot work.

**Comment by csnyulas** [comment]
@ying6991 can you send us a screen shot showing the versions of the plugins installed (or copy the output to the terminal when you start Protege)?

**Comment by ying6991** [comment]
Thanks for your reply, i send you 4 screen shots showing the versions of all the plugins installed and a SPARQL query tab.

**Comment by ying6991** [comment]
Dear csnyulas,

Thanks for your reply, I send you 4 screen shots (see attachments) showing the versions of all the plugins installed and a SPARQL query tab. 

With best regards
Yours sincerely,
Ying Zhang


2018-02-07 

张 营 



发件人：csnyulas <notifications@github.com>
发送时间：2018-02-07 01:11
主题：Re: [protegeproject/protege] After loading ontology SPARQL query tab does not work (#662)
收件人："protegeproject/protege"<protege@noreply.github.com>
抄送："ying6991"<ying_0612@163.com>,"Mention"<mention@noreply.github.com>

@ying6991 can you send us a screen shot showing the versions of the plugins installed (or copy the output to the terminal when you start Protege)?

**Comment by csnyulas** [comment]
I think the attachments don't come through if you just reply to a github notification email.
Try to upload the screen shots to the github issue:
https://github.com/protegeproject/protege/issues/662

**Comment by ying6991** [comment]
I try to upload the screen shots to the github issue, but it doesn't seem to see the attachments as well. So i copy the versions of all the plugins installed.

version 2.0.2 of the SPARQL Query Plugin,
version 2.0.2 of the SPARQL Query Plugin,
version 2.0.2 of the SPARQL Query Plugin,

2018-02-07 

张 营 



发件人：csnyulas <notifications@github.com>
发送时间：2018-02-07 10:16
主题：Re: [protegeproject/protege] After loading ontology SPARQL query tab does not work (#662)
收件人："protegeproject/protege"<protege@noreply.github.com>
抄送："ying6991"<ying_0612@163.com>,"Mention"<mention@noreply.github.com>

I think the attachments don't come through if you just reply to a github notification email.
Try to upload the screen shots to the github issue:
#662

**Comment by ying6991** [comment]
I try to upload the screen shots to the github issue, but it doesn't seem to see the attachments as well. So i copy the versions of all the plugins installed.

version 3.0.3 of the Browser View (OWLDoc), 
version 2.1.0 of the Cellfie Protege 5.0+ Plugin, 
version 4.0.1 of the DL Query,
version 2.0.0 of the Existential Query,
version 3.0.0 of the Explanation Workbench,
version 1.3.8 of the Hermit,
version 2.0.3 of the Existential Query,
version 2.0.0 of the OWL Code Generation Plug-in,
version 2.0.3 of the OWLAPI RDF Library,
version 5.0.3 of the OWLViz,
version 2.2.0 of the Pellet Reasoner Plug-in,
version 1.0.1 of the Properties in the Domain Class View,
version 5.0.1 of the snap-sparql-query-plugin,
version 2.0.2 of the SPARQL Query Plugin, and
version 1.0.3 of the SWRLTab Protege 5.0+ Plugin

2018-02-07 

张 营 



发件人：csnyulas <notifications@github.com>
发送时间：2018-02-07 10:16
主题：Re: [protegeproject/protege] After loading ontology SPARQL query tab does not work (#662)
收件人："protegeproject/protege"<protege@noreply.github.com>
抄送："ying6991"<ying_0612@163.com>,"Mention"<mention@noreply.github.com>

I think the attachments don't come through if you just reply to a github notification email.
Try to upload the screen shots to the github issue:
#662

**Comment by csnyulas** [comment]
This looks good to me. I have two suggestions you can try:
1. Select the *SPARQL Query* tab, and choose the `Window -> Reset selected tab to default state` menu option
2. Simply drop the *SPARQL query* view in the *SPARQL Query* tab, by selecting it from the `Window -> Views -> Query views -> SPARQL query` menu (see also: https://www.youtube.com/watch?v=JObQC-L2piA)

**Comment by ying6991** [comment]
@csnyulas 
Thanks very much for your guidance. After using the first your suggestion, the SPARQL Query tab started working.

**Comment by amin101** [comment]
I'm running protege 5.5.0-beta ,but still have this issue
Sparql query plugin : 2.0.2
OWLAPI RDF library : 2.0.3
