### ISSUE TITLE
Resizing the Protege window to minimum breaks Protege

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#664]
**WARNING: Do not try to reproduce this problem unless you have a full backup of your data. After doing this, Protege stops working and I do not know how to restore the normal behaviour except for restoring from the backup!**

Open Protege and shrink its window as much as possible to something like this:

![screen shot 2017-06-30 at 12 23 31](https://user-images.githubusercontent.com/2140361/27731851-0f214474-5d8f-11e7-9e1c-8c501dc10599.png)

This causes lot's of exceptions thrown like:

```
java.lang.IllegalArgumentException: Width and height must be >= 0
	at javax.swing.plaf.basic.BasicHTML.getHTMLBaseline(BasicHTML.java:86) ~[na:1.8.0_77]
	at javax.swing.plaf.basic.BasicHTML.getBaseline(BasicHTML.java:104) ~[na:1.8.0_77]
	at javax.swing.plaf.basic.BasicLabelUI.getBaseline(BasicLabelUI.java:293) ~[na:1.8.0_77]
	at javax.swing.JComponent.getBaseline(JComponent.java:2564) ~[na:1.8.0_77]
	at javax.swing.plaf.basic.BasicComboBoxUI.getBaseline(BasicComboBoxUI.java:999) ~[na:1.8.0_77]
	at javax.swing.JComponent.getBaseline(JComponent.java:2564) ~[na:1.8.0_77]
	at java.awt.GridBagLayout.alignOnBaseline(GridBagLayout.java:1829) ~[na:1.8.0_77]
	at java.awt.GridBagLayout.AdjustForGravity(GridBagLayout.java:1656) ~[na:1.8.0_77]
	at java.awt.GridBagLayout.adjustForGravity(GridBagLayout.java:1610) ~[na:1.8.0_77]
	at java.awt.GridBagLayout.ArrangeGrid(GridBagLayout.java:2200) ~[na:1.8.0_77]
	at java.awt.GridBagLayout.arrangeGrid(GridBagLayout.java:2031) ~[na:1.8.0_77]
	at java.awt.GridBagLayout.layoutContainer(GridBagLayout.java:812) ~[na:1.8.0_77]
	at java.awt.Container.layout(Container.java:1510) ~[na:1.8.0_77]
	at java.awt.Container.doLayout(Container.java:1499) ~[na:1.8.0_77]
	at java.awt.Container.validateTree(Container.java:1695) ~[na:1.8.0_77]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_77]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_77]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_77]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_77]
	at java.awt.Container.validateTree(Container.java:1704) ~[na:1.8.0_77]
	at java.awt.Container.validate(Container.java:1630) ~[na:1.8.0_77]
	at java.awt.Window.dispatchEventImpl(Window.java:2748) ~[na:1.8.0_77]
	at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_77]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_77]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_77]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_77]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_77]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_77]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_77]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_77]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_77]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_77]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_77]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_77]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_77]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_77]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_77]
```

**Comment by ykazakov** [comment]
Actually, after getting this error, Protege can no longer start. Probably the window size is saved between the runs in some preferences. Where?

![screen shot 2017-06-30 at 14 20 09](https://user-images.githubusercontent.com/2140361/27735640-f41c3032-5da0-11e7-959c-c59e5c6c4a4e.png)

**Comment by jasonww85** [comment]
I also encountered this problem today(windows 10). Don't know how it came up, maybe I have put too many views under a tab.
The solution is to clear windows regidt32 : 
https://protegewiki.stanford.edu/wiki/ClearingP4Preferences

**Comment by marksem** [comment]
> Actually, after getting this error, Protege can no longer start. Probably the window size is saved between the runs in some preferences. Where?
> 
> ![screen shot 2017-06-30 at 14 20 09](https://user-images.githubusercontent.com/2140361/27735640-f41c3032-5da0-11e7-959c-c59e5c6c4a4e.png)

It is saved in the windows registry.  Do a find in the registry for protege, and when you find registry entries with names like  \L\O\C_\X, etc as in this picture below, change them to reasonable values like in the picture.  Then re-launch protege and it should come up.

![image](https://user-images.githubusercontent.com/34490444/152244696-7bdc0597-4baa-4531-9dfe-2e76edae13b7.png)
