### ISSUE TITLE
Test failures for org.protege.editor.owl.model.library.Folder_IT

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#700]
As of today, Protege does not compile for me. The following tests fail:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.protege.editor.owl.model.library.Folder_IT
Tests run: 17, Failures: 0, Errors: 17, Skipped: 0, Time elapsed: 13.591 sec <<< FAILURE! - in org.protege.editor.owl.model.library.Folder_IT
testUpdateDuplicate(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.736 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateDuplicate(Folder_IT.java:327)

testDontTouchExisting(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 1.589 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testDontTouchExisting(Folder_IT.java:124)

testFileDeleted(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.927 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testFileDeleted(Folder_IT.java:147)

testUpdateShadowed(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.493 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateShadowed(Folder_IT.java:235)

testUpdateShadower(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.49 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateShadower(Folder_IT.java:256)

testBaseline(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.93 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testBaseline(Folder_IT.java:50)

testUpdateWithRetainedShadows01(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.49 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateWithRetainedShadows01(Folder_IT.java:167)

testUpdateWithRetainedShadows02(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.805 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateWithRetainedShadows02(Folder_IT.java:193)

testAutoUpdateFalse(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 1.573 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testAutoUpdateFalse(Folder_IT.java:137)

testUpdateChange(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.573 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateChange(Folder_IT.java:92)

testUpdateNoChange(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 1.578 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateNoChange(Folder_IT.java:79)

testShadowed(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.49 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testShadowed(Folder_IT.java:68)

testUpdateWithDuplicate(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.635 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testUpdateWithDuplicate(Folder_IT.java:291)

testDeletedShadow(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.491 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testDeletedShadow(Folder_IT.java:218)

testDeleteDuplicate(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.641 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testDeleteDuplicate(Folder_IT.java:310)

testDeletedShadower(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.513 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testDeletedShadower(Folder_IT.java:277)

testDuplicate(org.protege.editor.owl.model.library.Folder_IT)  Time elapsed: 0.628 sec  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at org.protege.editor.owl.model.library.Folder_IT.testDuplicate(Folder_IT.java:108)
```

My system is MacOS 10.12.6

```
$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /opt/apache-maven-3.3.3
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```

Protege is compiled by
```
mvn clean install
```

**Comment by ykazakov** [comment]
Integration tests do not seem to run on travis with the command:
```
mvn test -B
```
That's why the build did not fail on travis.

**Comment by ykazakov** [comment]
Apparently the offender is the following dependency that was recently added:
```
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
            <version>4.8.0.201706111038-r</version>
            <scope>provided</scope>
        </dependency>
```
It is a actually a signed artefact, so when it is embedded 
(as per instructions: ``<Embed-Dependency>*;scope=provided;inline=true</Embed-Dependency>``) 
its signature is included in the jar file of protege-editor-owl, which causes the security exception:
```
$ unzip -l protege-editor-owl-5.2.1-SNAPSHOT.jar *.RSA *.SF
Archive:  protege-editor-owl-5.2.1-SNAPSHOT.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
     7794  06-12-2017 19:41   META-INF/ECLIPSE_.RSA
   179754  06-12-2017 19:41   META-INF/ECLIPSE_.SF
---------                     -------
   187548                     2 files
```
Luckily, this dependency is a bundle, so it should not be embedded, but simply included into Protege bundles.
