### ISSUE TITLE
Protégé freezes when opening entities tab

### ISSUE THREAD

**Issue by buergerj** [protegeproject/protege#764]
I already freshly installed Protégé 5.2.0, but this did not help.
When I open a ontology and click on the "Entities" tab, Protégé freezes completely. When running from the command line via run.sh, the messages below come up.
I need to restart Protégé and retry, a number of times until it works fine.

Maybe this is related to ? #336 

```
error rendering ontology 
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2141) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1524) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993) ~[org.apache.felix.main.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLRenderer.<init>(RDFXMLRenderer.java:92) ~[na:na]
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLRenderer.<init>(RDFXMLRenderer.java:74) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.RDFXMLRenderingViewComponent.renderOntology(RDFXMLRenderingViewComponent.java:19) ~[na:na]
	at org.protege.editor.owl.ui.view.ontology.AbstractOntologyRenderingViewComponent$1.run(AbstractOntologyRenderingViewComponent.java:116) ~[na:na]
Caused by: java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_40]
	at java.lang.Object.wait(Object.java:502) ~[na:1.8.0_40]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2136) ~[org.apache.felix.main.jar:na]
	... 8 common frames omitted
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]


```

**Comment by buergerj** [comment]
I like to add: the problem apparently is that I have (now had) the RDF XML view as part of the "individuals by type" view. Apparently, in some cases this cannot be initialized correctly if the given ontology has not been saved ?

**Comment by matthewhorridge** [comment]
@buergerj it sounds like it is related.  I take it that removing the view gets rid of the problem.

**Comment by ahmadanimom** [comment]
i have faced the same problem while i click on entity and the protege freeze but it is solved now. I open my project from recent tabs or from url and that's the reason for hanging or freezing protege. if you open from file and then open tab and select your project and load the files and you will see it could not hang. i hope it work
