### ISSUE TITLE
Can't find Java 7 on a Mac

### ISSUE THREAD

**Issue by OlivierBaudry** [protegeproject/protege#80]
/Applications/Protege_5.0_beta/run.command ; exit;
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/protege/osgi/framework/Launcher : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
logout

[Opération terminée]

**Comment by matthewhorridge** [comment]
Closing this as we now bundle Java 8 with the distribution.

**Comment by artodeschini** [comment]
Try it
1. Rename <protegeInstallFolder>\bin\felix.jar to something like felix.jar.bak
2. Download the latest Felix Framework Distribution (version 3.2.2 worked for me) at http://felix.apache.org/site/downloads.cgi
3. Extract felix.jar from felix-framework-3.2.2\bin\ inside your downloaded archive file to <protegeInstallFolder>\bin\felix.jar
