### ISSUE TITLE
Upgrade OWL API to 4.5.6

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#800]
See previous issue #799

**Comment by matthewhorridge** [comment]
@ignazio1977 still having some problems here.  Any ideas as to why the first three lines appear? (and then result in a NPE).  Things work fine with the platform independent version of Protege, but none of the OS specific distributions (macOs, Win, Linux) work at all because of this error.  I'm trying to get to the bottom of this, but any insights would be appreciated.

```java
2018-09-13 16:16:39.190 [Classification Thread] INFO  Injector    Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
2018-09-13 16:16:39.190 [Classification Thread] WARN  Injector    No files found for META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
2018-09-13 16:16:39.192 [Classification Thread] INFO  Injector    Injecting object null
2018-09-13 16:16:39.193 [Classification Thread] INFO  OWLReasonerManager    
2018-09-13 16:16:39.198 [Classification Thread] ERROR OWLReasonerManager    An error occurred during reasoning: null.
java.lang.NullPointerException: null
	at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:186) ~[na:na]
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:106) ~[na:na]
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.buildIndividualAutomata(ObjectPropertyInclusionManager.java:726) ~[na:na]
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.createAutomata(ObjectPropertyInclusionManager.java:197) ~[na:na]
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.<init>(ObjectPropertyInclusionManager.java:56) ~[na:na]
	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:156) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:208) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:199) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:173) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createHermiTOWLReasoner(ReasonerFactory.java:51) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:19) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
```

**Comment by matthewhorridge** [comment]
@ignazio1977 never mind.... figure it out

**Comment by c7hm4r** [comment]
@matthewhorridge Do you still know how you fixed this problem? It would be very helpful if you could explain that. We have a similar problem in relation to GATE.

**Comment by matthewhorridge** [comment]
@c7hm4r I'm sorry, I'm trying to remember what the problem was, but I can't.  I suspect that it might have been something to do with the Protege build rather than the OWL API.  Possibly a stale version or something like that.

**Comment by c7hm4r** [comment]
Ok, thank you very much anyway!
