### ISSUE TITLE
Nullpointer on empty class expression

### ISSUE THREAD

**Issue by woutermont** [protegeproject/protege#855]
Following exception is thrown when pressing 'OK' in the class expression editor without actually entering a class expression. The issue occurs both when adding a new description (after which nothing is actually added), and when editing an existing description (after which the original description remains). 

Nothing unworkable, but the exception should be caught, and personally I would find it more handy if after editing a description to an empty field it dissapeared rather than changing nothing.

```
ERROR  13:50:25  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: superclass cannot be null
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.checkNotNull(OWLAPIPreconditions.java:98) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLSubClassOfAxiom(OWLDataFactoryImpl.java:1443) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLSubClassOfAxiom(OWLDataFactoryImpl.java:1452) ~[na:na]
	at org.protege.editor.owl.ui.frame.cls.OWLSubClassAxiomFrameSectionRow.createAxiom(OWLSubClassAxiomFrameSectionRow.java:37) ~[na:na]
	at org.protege.editor.owl.ui.frame.cls.OWLSubClassAxiomFrameSectionRow.createAxiom(OWLSubClassAxiomFrameSectionRow.java:22) ~[na:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSectionRow.handleEditingFinished(AbstractOWLFrameSectionRow.java:96) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList.lambda$handleEdit$5(OWLFrameList.java:368) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList$6.componentHidden(OWLFrameList.java:450) ~[na:na]
	at java.desktop/java.awt.AWTEventMulticaster.componentHidden(AWTEventMulticaster.java:198) ~[na:na]
	at java.desktop/java.awt.AWTEventMulticaster.componentHidden(AWTEventMulticaster.java:197) ~[na:na]
	at java.desktop/java.awt.AWTEventMulticaster.componentHidden(AWTEventMulticaster.java:197) ~[na:na]
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6467) ~[na:na]
	at java.desktop/java.awt.Component.processEvent(Component.java:6412) ~[na:na]
	at java.desktop/java.awt.Container.processEvent(Container.java:2263) ~[na:na]
	at java.desktop/java.awt.Window.processEvent(Window.java:2049) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008) ~[na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) ~[na:na]
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[na:na]
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) ~[na:na]
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[na:na]
```

**Comment by csnyulas** [comment]
I can reproduce this. It is really surprising that nobody reported this yet in so many years. Thanks for catching it @woutermont!
Here are two ways to simply reproduce this:
**Scenario 1:**
1. Select a class
2. In the class description view press on the Add (+) icon in the "SubClass Of" section
3. Select the "Class expression editor" tab (if not already selected). The content of the editor should be empty.
4. Press OK.
**Scenario 2:**
1. Select a class that has a superclass
2. In the class description view press on the Edit (o) icon at the right of on of its superclasses in the "SubClass Of" section
3. Select the "Class expression editor" tab (if not already selected). The content of the editor should contain the name of the superclass.
4. Delete the name of the superclass, leaving the content of the class expression editor empty.
5. Press OK.

We need to decide what would be the best course of action in these situations. Perhaps the most appropriate solution would be to deactivate the "OK" button when the content of the class expression editor is empty. We do that in the other editors if nothing is selected, or even in the class expression editor if the class expression entered in the editor is invalid.
