### ISSUE TITLE
Error after creating integer annotation property

### ISSUE THREAD

**Issue by Disassem** [protegeproject/protege#887]
Protege version: 5.5.0
1. Run Protege with new ontology
2. Add data property
3. Add custom annotation property with type xsd:integer
4. Try to add one more annotation property and got error:
[AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658) ~[na:1.8.0_121]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryInternalsImplNoCache.getOWLLiteral(OWLDataFactoryInternalsImplNoCache.java:186) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLLiteral(OWLDataFactoryImpl.java:1854) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLConstantEditor.getEditedObject(OWLConstantEditor.java:186) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLConstantEditor.getEditedObject(OWLConstantEditor.java:38) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLAnnotationEditor.isValid(OWLAnnotationEditor.java:242) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLAnnotationEditor.addStatusChangedListener(OWLAnnotationEditor.java:248) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList.showEditorDialog(OWLFrameList.java:435) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList.handleEdit(OWLFrameList.java:367) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList.handleAdd(OWLFrameList.java:346) ~[na:na]
	at org.protege.editor.core.ui.list.MList.lambda$new$1(MList.java:44) ~[na:na]
	at org.protege.editor.core.ui.list.MList.handleMouseClick(MList.java:212) ~[na:na]
	at org.protege.editor.core.ui.list.MList.access$200(MList.java:22) ~[na:na]
	at org.protege.editor.core.ui.list.MList$3.mouseReleased(MList.java:107) ~[na:na]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_121]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[na:1.8.0_121]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6298) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]

**Comment by csnyulas** [comment]
I cannot reproduce it.
I tried many different interpretation, but none has produced an exception so far.

These are steps that are closest to what @Disassem described:
1. Open empty ontology
2. Create a data property (say `dp`)
3. Switch to "Annotation properties" view and create a top level annotation property (say `ap1`)
4. *Set range of that annotation property (`ap1`) to `xsd:integer`*
5. Create a new top-level annotation property (say `ap2`)

Do you get an exception by doing this @Disassem ? I do not. I highlighted the step which was not totally clear from the OPs report.

I can even play further, and add an annotation on either `dp` or `ap1` or `ap2` using the annotation property `ap1` or `ap2` and specifying a random string value, and Protege still would not complain about it. Although, perhaps it should, if we consider that `ap1`'s range is `xsd:integer` and I assign a string literal through it.

**Comment by Disassem** [comment]
Added screenshots.
![Screen 1](https://user-images.githubusercontent.com/11461847/56943362-5dae4f00-6b49-11e9-8b18-ed5316855347.png)
![Screen 2](https://user-images.githubusercontent.com/11461847/56943370-64d55d00-6b49-11e9-841f-1c2e88eadaa4.png)
![Screen 3](https://user-images.githubusercontent.com/11461847/56943373-6868e400-6b49-11e9-9c2d-3f1c77db763b.png)
![Screen 4](https://user-images.githubusercontent.com/11461847/56943375-6b63d480-6b49-11e9-9156-5da838a3814a.png)

**Comment by csnyulas** [comment]
I did a thorough testing to see which are all the situation where this bugs shows up. Here is what I found out:
- The problem appears when one creates an annotation of type `xsd:integer` **on any type of entity** (class, individual, data property, object property, etc), **and even on the ontology itself**.
- It does not matter what annotation property is used (it can be `rdfs:comment`, `rdfs:label`, or any user defined annotation), the problem appears for **all annotation properties**. 
- **The only annotation value type that causes problem is `xsd:integer`**. Specifying any other type for the annotation value (`xsd:decimal`, `xsd:byte`, `xsd:int`, `xsd:positiveInteger`, `rdf:PlainLiteral`, etc.), or not specifying a value type, would not exhibit the problem. 
- The problem does not appear even if the type of the annotation value is _deduced_ to be `xsd:integer` (i.e. providing a natural number as a value, e.g. 2, and leaving the type empty), but **only if the type is _explicitly_ set to `xsd:integer`**.
- Once the exception is thrown, it will not be possible to **add** any other annotation to any entity of that specific entity type (class, individual, data property, etc). However, for other entity types, where the bug was not triggered yet, adding annotations would still work. Existing annotation values can be still edited everywhere.

So, the easiest and cleanest way to reproduce the bug (which is pretty much a simplified and more explicit version of what @Disassem provided):
1. Open Protege (loading any ontology or just using the empty one shown by default)
2. Select `owl:Thing` (or any other class)
3. Click on the "Add" button in the "Annotations" section
4. Select `rdfs:comment` (or any other annotation property) on the left
5. Provide a number (e.g. 123) on the right hand side, and **select `xsd:integer` in the Type drop-down list**, at the bottom.
6. Accept it by clicking on "OK"
7. Click on the "Add" button, again, in the "Annotations" section

An exception will be thrown, and there is no way to add any new annotations to any of the classes.

**Comment by matthewhorridge** [comment]
Relevant stack trace

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658) ~[na:1.8.0_121]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryInternalsImplNoCache.getOWLLiteral(OWLDataFactoryInternalsImplNoCache.java:186) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLLiteral(OWLDataFactoryImpl.java:1854) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLConstantEditor.getEditedObject(OWLConstantEditor.java:193) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLConstantEditor.getEditedObject(OWLConstantEditor.java:39) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLAnnotationEditor.isValid(OWLAnnotationEditor.java:242) ~[na:na]
	at org.protege.editor.owl.ui.editor.OWLAnnotationEditor.addStatusChangedListener(OWLAnnotationEditor.java:248) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList.showEditorDialog(OWLFrameList.java:435) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList.handleEdit(OWLFrameList.java:367) ~[na:na]
	at org.protege.editor.owl.ui.framelist.OWLFrameList.handleAdd(OWLFrameList.java:346) ~[na:na]
	at org.protege.editor.core.ui.list.MList.lambda$new$1(MList.java:44) ~[na:na]
	at org.protege.editor.core.ui.list.MList.handleMouseClick(MList.java:212) ~[na:na]
	at org.protege.editor.core.ui.list.MList.access$200(MList.java:22) ~[na:na]
	at org.protege.editor.core.ui.list.MList$3.mouseReleased(MList.java:107) ~[na:na]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_121]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[na:1.8.0_121]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6298) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]
```

**Comment by matthewhorridge** [comment]
This is an OWL API bug.  I've filed an issue for it:

https://github.com/owlcs/owlapi/issues/846
