### ISSUE TITLE
Error importing ontologies

### ISSUE THREAD

**Issue by eliasweatherfield** [protegeproject/protege#911]
I am getting an error while trying to locally import the Turtle syntax files from https://github.com/CommonCoreOntology/CommonCoreOntologies. Opening the files directly works. Importing works after conversion to RDF/XML syntax.

>   ERROR  18:21:19  An error occurred whilst extracting the Ontology Id from the imported ontology: {}
java.lang.NullPointerException: null
	at org.protege.editor.owl.model.repository.MasterOntologyIDExtractor.getOntologyId(MasterOntologyIDExtractor.java:27) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.checkImport(AnticipateOntologyIdPage.java:109) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.lambda$new$0(AnticipateOntologyIdPage.java:44) [protege-editor-owl.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

**Comment by eliasweatherfield** [comment]
Could be a server configuration issue: https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/48

**Comment by cmungall** [comment]
Not an issue with Protege or the OWLAPI, see: https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/48

**Comment by eliasweatherfield** [comment]
OK. I am closing this for the time being.
