### ISSUE TITLE
protege-editor-core bundle contains package org.protege.editor.owl but does not export it

### ISSUE THREAD

**Issue by ykazakov** [protegeproject/protege#915]
The protege-editor-core bundle contains two org.protege.editor.owl.* packages, but apparently does not export it:

pom.xml exports only:

```
<Export-Package>
	org.protege.editor.core.*,
</Export-Package>
```

However, the protege-editor-owl bundle uses the interface
`org.protege.editor.owl.ui.renderer.HasUseSystemForeground`
located in this package.

Because of the missed export I get java.lang.NoClassDefFoundError for this class when running Protege in eclipse using [these instruction](https://github.com/protegeproject/protege/wiki/Setup-in-Eclipse-PDE) as soon as I can try to switch to the Entities tab:
```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.NoClassDefFoundError: org/protege/editor/owl/ui/renderer/HasUseSystemForeground
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:278) ~[na:na]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:716) ~[na:na]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:639) ~[na:na]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:607) ~[na:na]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:587) ~[na:na]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:566) ~[na:na]
...
```

It appears that Protege is running fine standalone (using the Apache Felix launcher instead of eclipse osgi launcher), although I do not understand how it resolves the dependencies in this case.

A simple workaround is to move the content of `org.protege.editor.owl.*` packages to the corresponding `org.protege.editor.core.*` package. It is a pity that it does not seem to be possible to test these kind of problems.

**Comment by matthewhorridge** [comment]
How odd... there's also ```MousePositionCache``` right?  Moving, as stated in the work around.

**Comment by ykazakov** [comment]
Unlike HasUseSystemForeground, MousePositionCache is not used outside of the bundle. Hence no export declaration was needed for this package before HasUseSystemForeground was added. I am just concerned why this problem does not show up with the Apache Felix launcher.
