### ISSUE TITLE
OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by donpellegrino** [protegeproject/protege#916]
When running Reasoner -> Start Reasoner on some ontologies, with HermiT 1.4.3.456 selected as the reasoner, a dialog is produced reporting:

> An error occurred during reasoning
> OutOfMemoryError: GC overhead limit exceeded

The log shows:

    INFO  14:10:54  ------------------------------- Running Reasoner -------------------------------
    INFO  14:10:56  Pre-computing inferences:
    INFO  14:10:56      - class hierarchy
    INFO  14:10:56      - object property hierarchy
    INFO  14:10:56      - data property hierarchy
    INFO  14:10:56      - class assertions
    INFO  14:10:56      - object property assertions
    INFO  14:10:56      - data property assertions
    INFO  14:10:56      - same individuals
    INFO  14:11:17  
    WARN  14:11:20  Exception thrown by listener: org.protege.editor.owl.model.OWLWorkspace$$Lambda$74/1388408248.  Detatching bad listener.
    ERROR  14:11:21  An error occurred during reasoning: GC overhead limit exceeded.
    java.lang.OutOfMemoryError: GC overhead limit exceeded
 	at java.util.HashMap.newNode(HashMap.java:1742) ~[na:1.8.0_121]
 	at java.util.HashMap.putVal(HashMap.java:630) ~[na:1.8.0_121]
	at java.util.HashMap.put(HashMap.java:611) ~[na:1.8.0_121]
	at java.util.HashSet.add(HashSet.java:219) ~[na:1.8.0_121]
	at org.semanticweb.HermiT.hierarchy.HierarchyNode.getDescendantNodes(HierarchyNode.java:147) ~[na:na]
	at org.semanticweb.HermiT.hierarchy.HierarchyNode.getDescendantNodes(HierarchyNode.java:116) ~[na:na]
	at org.semanticweb.HermiT.hierarchy.InstanceManager.addKnownConceptInstance(InstanceManager.java:777) ~[na:na]
	at org.semanticweb.HermiT.hierarchy.InstanceManager.readOffTypes(InstanceManager.java:656) ~[na:na]
	at org.semanticweb.HermiT.hierarchy.InstanceManager.readOffClassInstancesByIndividual(InstanceManager.java:518) ~[na:na]
	at org.semanticweb.HermiT.hierarchy.InstanceManager.initializeKnowAndPossibleClassInstances(InstanceManager.java:502) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.initialiseClassInstanceManager(Reasoner.java:694) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.realise(Reasoner.java:1675) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.precomputeInferences(Reasoner.java:596) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.precompute(OWLReasonerManagerImpl.java:447) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:388) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
    WARN  14:11:28  Exception thrown by listener: org.protege.editor.owl.ui.framelist.OWLFrameList$$Lambda$290/461978935.  Detatching bad listener.
    WARN  14:11:36  Exception thrown by listener: org.protege.editor.owl.ui.framelist.OWLFrameList$$Lambda$290/461978935.  Detatching bad listener.

Test system:

    INFO  13:59:07  ------------------------------------ Protege -----------------------------------
    INFO  13:59:07  Protege Desktop
    INFO  13:59:07  Version 5.5.0, Build 
    INFO  13:59:07  
    INFO  13:59:07  
    INFO  13:59:07  ----------------------------------- Platform -----------------------------------
    INFO  13:59:07  Java: JVM 1.8.0_121-b13  Memory: 466M
    INFO  13:59:07  Language: en, Country: US
    INFO  13:59:07  Framework: Apache Software Foundation (1.8) 
    INFO  13:59:07  OS: linux (3.10.0-957.27.2.el7.x86_64)
    INFO  13:59:07  Processor: x86-64
    INFO  13:59:07  
    INFO  13:59:07  ------------------------------------ Plugins -----------------------------------
    INFO  13:59:07  Plugin: OWLAPI RDF Library (3.0.0)
    INFO  13:59:07  Plugin: SPARQL Query Plugin (3.0.0)
    INFO  13:59:07  Plugin: Existential Query (2.0.0)
    INFO  13:59:07  Plugin: Explanation Workbench (3.0.0)
    INFO  13:59:07  Plugin: OntoGraf (2.0.3)
    INFO  13:59:07  Plugin: Browser View (OWLDoc) (3.0.3)
    INFO  13:59:07  Plugin: OWLViz (5.0.3)
    INFO  13:59:07  Plugin: HermiT Reasoner (1.4.3.456)
    INFO  13:59:07  Plugin: Cellfie Protege 5.0+ Plugin (2.1.0)
    INFO  13:59:07  Plugin: DL Query (4.0.1)
    INFO  13:59:07  Plugin: SWRLTab Protege 5.0+ Plugin (2.0.6)
    INFO  13:59:07  Plugin: OWL Code Generation Plug-in (2.0.0)
    INFO  13:59:07  
    INFO  13:59:07  Creating and setting up empty (default) editor kit
    INFO  13:59:07  OWL API Version: 4.5.9.2019-02-01T07:24:44Z

**Comment by donpellegrino** [comment]
Editing run.sh by adding "-XX:-UseGCOverheadLimit" seem to be a candidate work-around. With this change, HermiT ran and completed as expected on the same ontology. While I was in run.sh, I also commented out  "-Xmx500M -Xms200M -Xss16M." It is not clear why those limits are imposed by default.

**Comment by donpellegrino** [comment]
The issue with the limits (#865) may be related.

**Comment by aksstar** [comment]
**Earlier :** 
Java: JVM 1.8.0_121-b13  Memory: 466M 

**After adding  "-XX:-UseGCOverheadLimit" and removing "-Xmx500M -Xms200M -Xss16M." from run.sh**
Java: JVM 1.8.0_121-b13  Memory: 1828M 

The above solution by @donpellegrino  works :+1:
