### ISSUE TITLE
addAxioms deadlock in Protege 5.5.0

### ISSUE THREAD

**Issue by cjd218** [protegeproject/protege#954]
I'm trying to add multiple axioms to Protege in a new plugin, and occasionally the program hangs. After debugging, it appears to be a deadlock in Protege. Initially I was adding one axiom at a time. I tried adding all axioms at once with "addAxioms", and the issue is less common but still persists.

Basic plugin code
```
OWLOntology actOntology = modelManager.getActiveOntology();
OWLOntologyManager ontManager = actOntology.getOWLOntologyManager();
OWLDataFactory owlFactory = ontManager.getOWLDataFactory();
Set<OWLAxiom> newAxioms = new HashSet<OWLAxiom>();
// for loop adding axioms from a Jena model, essentially...
// OWLNamedIndividual sub = owlFactory.getOWLNamedIndividual(IRI.create(stmt.getSubject().getURI()));
// newAxioms.add(owlFactory.getOWLDeclarationAxiom(sub));
.
.
.
// HANG at this line
ChangeApplied status = ontManager.addAxioms(actOntology, newAxioms);
```

jstack indicates a deadlock has occurred.
```
Found one Java-level deadlock:
=============================
"Thread-8":
  waiting to lock monitor 0x0000000003c2cac8 (object 0x00000000e1219410, a java.awt.Component$AWTTreeLock),
  which is held by "AWT-EventQueue-0"
"AWT-EventQueue-0":
  waiting for ownable synchronizer 0x00000000e1449d50, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "Thread-8"

Java stack information for the threads listed above:
===================================================
"Thread-8":
        at java.awt.Component.enable(Component.java:1489)
        - waiting to lock <0x00000000e1219410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.enable(JComponent.java:3623)
        at java.awt.Component.enable(Component.java:1513)
        at java.awt.Component.setEnabled(Component.java:1478)
        at javax.swing.JComponent.setEnabled(JComponent.java:2680)
        at javax.swing.AbstractButton.setEnabled(AbstractButton.java:2091)
        at javax.swing.JMenuItem.setEnabled(JMenuItem.java:312)
        at javax.swing.AbstractAction.setEnabledFromAction(AbstractAction.java:102)
        at javax.swing.AbstractButton.actionPropertyChanged(AbstractButton.java:1218)
        at javax.swing.JMenuItem.actionPropertyChanged(JMenuItem.java:411)
        at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1364)
        at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1352)
        at javax.swing.ActionPropertyChangeListener.propertyChange(ActionPropertyChangeListener.java:88)
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
        at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
        at javax.swing.AbstractAction.firePropertyChange(AbstractAction.java:276)
        at javax.swing.AbstractAction.setEnabled(AbstractAction.java:236)
        at org.protege.editor.owl.ui.action.MakeAllIndividualsDifferent.updateState(MakeAllIndividualsDifferent.java:65)
        at org.protege.editor.owl.ui.action.MakeAllIndividualsDifferent.lambda$handleOntologyChanges$3(MakeAllIndividualsDifferent.java:75)
        at org.protege.editor.owl.ui.action.MakeAllIndividualsDifferent$$Lambda$517/967593510.accept(Unknown Source)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.protege.editor.owl.ui.action.MakeAllIndividualsDifferent.handleOntologyChanges(MakeAllIndividualsDifferent.java:75)
        at org.protege.editor.owl.ui.action.MakeAllIndividualsDifferent$$Lambda$130/1641669484.ontologiesChanged(Unknown Source)
        at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:38)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1711)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:693)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.addAxioms(OWLOntologyManagerImpl.java:785)
        at csvtordf.main.CsvWizard$5.call(CsvWizard.java:391)
        at csvtordf.main.CsvWizard$5.call(CsvWizard.java:345)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
"AWT-EventQueue-0":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000e1449d50> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
        at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.withReadLock(ConcurrentOWLOntologyImpl.java:160)
        at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getImportsClosure(ConcurrentOWLOntologyImpl.java:284)
        at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getOntologies(AbstractOWLMetric.java:99)
        at org.semanticweb.owlapi.metrics.ObjectCountMetric.getObjects(ObjectCountMetric.java:80)
        at org.semanticweb.owlapi.metrics.ObjectCountMetric.recomputeMetric(ObjectCountMetric.java:69)
        at org.semanticweb.owlapi.metrics.ObjectCountMetric.recomputeMetric(ObjectCountMetric.java:31)
        at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:82)
        at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:36)
        at org.protege.editor.owl.ui.metrics.MetricsTableModel.lambda$rebuild$0(MetricsTableModel.java:58)
        at org.protege.editor.owl.ui.metrics.MetricsTableModel$$Lambda$201/766081915.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.protege.editor.owl.ui.metrics.MetricsTableModel.rebuild(MetricsTableModel.java:58)
        at org.protege.editor.owl.ui.metrics.MetricsTableModel.getValueAt(MetricsTableModel.java:46)
        at javax.swing.JTable.getValueAt(JTable.java:2717)
        at javax.swing.JTable.prepareRenderer(JTable.java:5706)
        at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
        at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
        at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
        at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
        at javax.swing.JComponent.paintComponent(JComponent.java:780)
        at javax.swing.JComponent.paint(JComponent.java:1056)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x00000000e1219410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x00000000e1219410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x00000000e1219410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x00000000e1219410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JViewport.paint(JViewport.java:728)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x00000000e1219410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x00000000e1219410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
        at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
        at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
        at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
        at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Found 1 deadlock.
```

**Comment by cjd218** [comment]
I believe I found my issue...

The new plugin runs on JavaFX. The JavaFX Task was trying to update the OWLOntology on the JavaFX Thread, and Protege was trying to consume the same ontology on the Swing thread. The two different threads were not synchronized, hence the deadlock.

I modifed the plugin to modify the ontology on the Swing thread with...

`
SwingUtilities.invokeLater(addAxiomsTask);
`

Have not been able to reproduce the deadlock since, so closing this bug.
