### ISSUE TITLE
Failing to run Protege on debian 10 after building from source.

### ISSUE THREAD

**Issue by mthl** [protegeproject/protege#960]
Hello,

I am on Debian 10 with OpenJDK 11, when following [the instructions to build Protege from source](https://github.com/protegeproject/protege/wiki/Setup-in-Eclipse#get-and-build-the-source-code) on commit 093b336088e323afea9108eb7361dbcf4d8384c0 `mvn clean package` succeeds but when running `./protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/run.sh` things fails to start with the following error:

```
CompileCommand: exclude javax/swing/text/GlyphView.getBreakSpot
******************************************************************************** 
**                                  Protege                                   ** 
******************************************************************************** 
 
----------------- Initialising and Starting the OSGi Framework ----------------- 
FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory 
 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.util.SecureAction (file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bin/org.apache.felix.main.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.util.SecureAction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
The OSGi framework has been initialised 
------------------------------- Starting Bundles ------------------------------- 
Starting bundle org.protege.common 
Starting bundle org.eclipse.equinox.common 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle org.eclipse.equinox.registry 
Starting bundle org.protege.editor.core.application 
Starting bundle jul.to.slf4j 
Starting bundle org.apache.servicemix.bundles.aopalliance 
Starting bundle ch.qos.logback.core 
Starting bundle org.apache.commons.io 
Starting bundle org.eclipse.jgit 
Starting bundle slf4j.api 
Starting bundle org.eclipse.equinox.common 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle com.google.guava 
Starting bundle org.eclipse.equinox.registry 
Starting bundle log4j.over.slf4j 
Starting bundle com.googlecode.javaewah.JavaEWAH 
Starting bundle org.apache.servicemix.bundles.javax-inject 
Starting bundle org.protege.editor.owl 
Starting bundle org.protege.editor.core.application 
Starting bundle org.protege.common 
Starting bundle ch.qos.logback.classic 
Starting bundle org.jsr-305 
Starting bundle org.semanticweb.owl.owlapi 
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/protege-common.jar 
org.osgi.framework.BundleException: Unable to resolve org.protege.common [1](R 1.0): missing requirement [org.protege.common [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.7.0)(!(version>=2.0.0))) [caused by: Unable to resolve slf4j.api [11](R 11.0): missing requirement [slf4j.api [11](R 11.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))] Unresolved requirements: [[org.protege.common [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.7.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/org.eclipse.equinox.common.jar 
org.osgi.framework.BundleException: Unable to resolve org.eclipse.equinox.common [2](R 2.0): missing requirement [org.eclipse.equinox.common [2](R 2.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.osgi.service.datalocation) [caused by: Unable to resolve org.eclipse.equinox.supplement [3](R 3.0): missing requirement [org.eclipse.equinox.supplement [3](R 3.0)] osgi.ee; (|(&(osgi.ee=JavaSE)(version=1.4.0))(&(osgi.ee=CDC/Foundation)(version=1.0.0))(&(osgi.ee=JavaSE)(version=1.3.0)))] Unresolved requirements: [[org.eclipse.equinox.common [2](R 2.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.osgi.service.datalocation)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/org.eclipse.equinox.supplement.jar 
org.osgi.framework.BundleException: Unable to resolve org.eclipse.equinox.supplement [3](R 3.0): missing requirement [org.eclipse.equinox.supplement [3](R 3.0)] osgi.ee; (|(&(osgi.ee=JavaSE)(version=1.4.0))(&(osgi.ee=CDC/Foundation)(version=1.0.0))(&(osgi.ee=JavaSE)(version=1.3.0))) Unresolved requirements: [[org.eclipse.equinox.supplement [3](R 3.0)] osgi.ee; (|(&(osgi.ee=JavaSE)(version=1.4.0))(&(osgi.ee=CDC/Foundation)(version=1.0.0))(&(osgi.ee=JavaSE)(version=1.3.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/org.eclipse.equinox.registry.jar 
org.osgi.framework.BundleException: Unable to resolve org.eclipse.equinox.registry [4](R 4.0): missing requirement [org.eclipse.equinox.registry [4](R 4.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.osgi.service.debug) [caused by: Unable to resolve org.eclipse.equinox.supplement [3](R 3.0): missing requirement [org.eclipse.equinox.supplement [3](R 3.0)] osgi.ee; (|(&(osgi.ee=JavaSE)(version=1.4.0))(&(osgi.ee=CDC/Foundation)(version=1.0.0))(&(osgi.ee=JavaSE)(version=1.3.0)))] Unresolved requirements: [[org.eclipse.equinox.registry [4](R 4.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.osgi.service.debug)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/protege-editor-core.jar 
org.osgi.framework.BundleException: Unable to resolve org.protege.editor.core.application [5](R 5.0): missing requirement [org.protege.editor.core.application [5](R 5.0)] osgi.wiring.package; (&(osgi.wiring.package=ch.qos.logback.classic.spi)(version>=1.1.0)(!(version>=2.0.0))) [caused by: Unable to resolve ch.qos.logback.classic [17](R 17.0): missing requirement [ch.qos.logback.classic [17](R 17.0)] osgi.wiring.package; (&(osgi.wiring.package=ch.qos.logback.core)(version>=1.1.0)(!(version>=2.0.0))) [caused by: Unable to resolve ch.qos.logback.core [8](R 8.0): missing requirement [ch.qos.logback.core [8](R 8.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.6))]] Unresolved requirements: [[org.protege.editor.core.application [5](R 5.0)] osgi.wiring.package; (&(osgi.wiring.package=ch.qos.logback.classic.spi)(version>=1.1.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/jul-to-slf4j.jar 
org.osgi.framework.BundleException: Unable to resolve jul.to.slf4j [6](R 6.0): missing requirement [jul.to.slf4j [6](R 6.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.spi)(version>=1.7.12)) [caused by: Unable to resolve slf4j.api [11](R 11.0): missing requirement [slf4j.api [11](R 11.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))] Unresolved requirements: [[jul.to.slf4j [6](R 6.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.spi)(version>=1.7.12))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/logback-core.jar 
org.osgi.framework.BundleException: Unable to resolve ch.qos.logback.core [8](R 8.0): missing requirement [ch.qos.logback.core [8](R 8.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.6)) Unresolved requirements: [[ch.qos.logback.core [8](R 8.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.6))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/org.eclipse.jgit.jar 
org.osgi.framework.BundleException: Unable to resolve org.eclipse.jgit [10](R 10.0): missing requirement [org.eclipse.jgit [10](R 10.0)] osgi.wiring.package; (osgi.wiring.package=javax.crypto) Unresolved requirements: [[org.eclipse.jgit [10](R 10.0)] osgi.wiring.package; (osgi.wiring.package=javax.crypto)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/slf4j-api.jar 
org.osgi.framework.BundleException: Unable to resolve slf4j.api [11](R 11.0): missing requirement [slf4j.api [11](R 11.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0)) Unresolved requirements: [[slf4j.api [11](R 11.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/log4j-over-slf4j.jar 
org.osgi.framework.BundleException: Unable to resolve log4j.over.slf4j [13](R 13.0): missing requirement [log4j.over.slf4j [13](R 13.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.helpers)(version>=1.6.0)) [caused by: Unable to resolve slf4j.api [11](R 11.0): missing requirement [slf4j.api [11](R 11.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))] Unresolved requirements: [[log4j.over.slf4j [13](R 13.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.helpers)(version>=1.6.0))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/protege-editor-owl.jar 
org.osgi.framework.BundleException: Unable to resolve org.protege.editor.owl [16](R 16.0): missing requirement [org.protege.editor.owl [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=javax.annotation.processing) Unresolved requirements: [[org.protege.editor.owl [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=javax.annotation.processing)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/logback-classic.jar 
org.osgi.framework.BundleException: Unable to resolve ch.qos.logback.classic [17](R 17.0): missing requirement [ch.qos.logback.classic [17](R 17.0)] osgi.wiring.package; (&(osgi.wiring.package=ch.qos.logback.core)(version>=1.1.0)(!(version>=2.0.0))) [caused by: Unable to resolve ch.qos.logback.core [8](R 8.0): missing requirement [ch.qos.logback.core [8](R 8.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.6))] Unresolved requirements: [[ch.qos.logback.classic [17](R 17.0)] osgi.wiring.package; (&(osgi.wiring.package=ch.qos.logback.core)(version>=1.1.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Error starting file:/home/mthl/these/src/protege/protege-desktop/target/protege-5.6.0-beta-1-SNAPSHOT-platform-independent/Protege-5.6.0-beta-1-SNAPSHOT/bundles/owlapi-osgidistribution.jar 
org.osgi.framework.BundleException: Unable to resolve org.semanticweb.owl.owlapi [19](R 19.0): missing requirement [org.semanticweb.owl.owlapi [19](R 19.0)] osgi.wiring.package; (osgi.wiring.package=javax.crypto) Unresolved requirements: [[org.semanticweb.owl.owlapi [19](R 19.0)] osgi.wiring.package; (osgi.wiring.package=javax.crypto)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
The OSGi framework has been started 
 
```
I am not familiar with OSGI, I have no clue how to solve the issue here.
I have tried with tag `v5.5.0` with the same result. Am I overlooking any implicit build requirement ?

**Comment by matthewhorridge** [comment]
@mthl a Java 8 runtime is required

**Comment by mthl** [comment]
Thanks it works perfectly with OpenJDK 8.

Shall I update https://github.com/protegeproject/protege/wiki/Building-from-Source to mention this requirement? Maybe you have a better suggestion where this information should be put ?
