### ISSUE TITLE
Cannot load FaCT++ reasoner

### ISSUE THREAD

**Issue by AndreyMZ** [protegeproject/protege#98]
**STR**:
0. Fix https://github.com/protegeproject/protege/issues/97
1. Go to File -> Check for plugins... in main menu. 
2. Check checkbox 'install' for 'FaCT++ reasoner' (available version '1.6.3'). 
3. Click Install.

**Actual result:**
In console log:
```
Downloading FaCT++ reasoner
Download URL: https://docs.google.com/uc?export=download&id=0B688Ilel_jz_dmhQQzl3bVBjN1E
Temp file name: uk.ac.manchester.cs.owl.factplusplus.jar
Copying FaCT++ reasoner
Loading FaCT++ reasoner
Exception caught installing plugins
org.osgi.framework.BundleException: Unresolved constraint in bundle uk.ac.manchester.cs.owl.factplusplus [22]: No matching native libraries found.
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:942)
        at org.protege.editor.core.update.PluginInstaller.installPlugin(PluginInstaller.java:264)
        at org.protege.editor.core.update.PluginInstaller.install(PluginInstaller.java:106)
        at org.protege.editor.core.update.PluginInstaller.access$100(PluginInstaller.java:34)
        at org.protege.editor.core.update.PluginInstaller$1.run(PluginInstaller.java:60)
        at java.lang.Thread.run(Unknown Source)
```

**Root cause:**
This is a bug in Apache Felix Framework before version 4.4.1: https://issues.apache.org/jira/browse/FELIX-4534

**Solution:**
Upgrade Apache Felix Framework to 4.4.1 (the latest) version:
```patch
diff --git a/pom.xml b/pom.xml
index 0ede81c..e1db0c1 100644
--- a/pom.xml
+++ b/pom.xml
@@ -124,7 +124,7 @@
             <dependency>
 				<groupId>org.apache.felix</groupId>
 				<artifactId>org.apache.felix.main</artifactId>
-				<version>4.2.1</version>
+				<version>4.4.1</version>
 			</dependency>
 
 		</dependencies>
```

**Workaround:**
Add OS name "win" to the MANIFEST file in the .jar file:
```patch
--- "a/uk.ac.manchester.cs.owl.factplusplus-P4.3-v1.6.3\\META-INF\\MANIFEST.MF"
+++ "b/uk.ac.manchester.cs.owl.factplusplus-P4.3-v1.6.3\\META-INF\\MANIFEST.MF"
@@ -16,6 +16,7 @@ Require-Bundle: org.protege.common,
  org.protege.editor.owl,
  org.semanticweb.owl.owlapi
 Bundle-NativeCode: lib/native/64bit/FaCTPlusPlusJNI.dll;
+ osname=win ;
  osname=WindowsNT ;
  osname=Windows NT ;
  osname=WinNT ;
@@ -32,6 +33,7 @@ Bundle-NativeCode: lib/native/64bit/FaCTPlusPlusJNI.dll;
  processor=x86_64 ;
  processor = amd64 ,
  lib/native/32bit/FaCTPlusPlusJNI.dll;
+ osname=win ;
  osname=Windows95 ;
  osname=Windows 95 ;
  osname=Win95 ;
```

**Comment by tsarkov** [comment]
Thanks Andrey. I've updated FaCT++ with your workaround and submitted pull request to properly fix the problem.
